### ISSUE TITLE
Can only deny tnt in main config and not in a region any longer

### ISSUE THREAD

**Issue by Capri205** [EngineHub/WorldGuard#1539]
Hi. Are we not able to control explosions in a region with flags any more?

We've always prevented tnt explosions doing any damage in our regions by setting a number of flags like tnt, other-explosion and creeper-explosion to deny. However, I discovered these flags weren't effective for some reason and tnt now causes block damage. The only way to prevent it is to now set block-tnt, blobk-tnt-block-damage to true in the main worldguard config.yml. I keep WorldGuard up to date, but I don't always test out the flags when upgrading, so not sure when this change might have occurred.

We are running the latest spigot build and I tested this with both the latest 7.0.2 stable and 7.0.3 snapshot. I upgraded from 7.0.1 which I think I deployed last August, but did not test the controls.

An example of our region flags which used to prevent tnt without the main config having it set:

        flags: {other-explosion: deny, lava-fire: deny, use: allow, snow-fall: deny,
            block-trampling: deny, leaf-decay: deny, ice-melt: deny, vehicle-destroy: allow,
            interact: allow, chest-access: allow, firework-damage: deny, ride: allow,
            fire-spread: deny, enderdragon-block-damage: deny, vehicle-place: allow,
            ravager-grief: deny, entity-painting-destroy: deny, wither-damage: deny,
            lighter: deny, enderman-grief: deny, pvp: deny, mob-spawning: allow, creeper-explosion: deny,
            snow-melt: deny, frosted-ice-melt: deny, lava-flow: deny, tnt: deny, entity-item-frame-destroy: deny,
            ghast-fireball: deny}

On our build server it's ok to set these restrictions at the world level, but on some of our other pvp servers we rely on this control at the region level.

Cheers, C

**Comment by wizjany** [comment]
chances are you're just testing as op/with bypass perms or something. no issues on WG's end.

**Comment by Capri205** [comment]
I deop'd myself for the test, but will check the permissions plugin isn't
acting up. thanks.
