### ISSUE TITLE
Setting Difficulty in a selected Region

### ISSUE THREAD

**Issue by emanuele3d** [EngineHub/WorldGuard#1544]
Hi there, and thank you for the excellent work with WorldGuard. It's a really useful tool. 

I am trying to get monsters spawning in a small region of an otherwise creative/peaceful world. It appears the peaceful setting of the world prevents even the placement of zombie eggs to spawn zombies. 

I therefore thought I could change the difficulty setting of the region but I cannot find a command/flag that does that. Is there one?

**Comment by wizjany** [comment]
not how the game works.
