### ISSUE TITLE
SpawnEntityEvent

### ISSUE THREAD

**Issue by LucidAPs** [EngineHub/WorldGuard#1548]
MC 1.15
WorldGuard : 2029
Please make the event asynchronously.
https://pastebin.com/raw/TNQfjDSH

**Comment by wizjany** [comment]
That's not how this works.

**Comment by LucidAPs** [comment]
This what? Plugin? Request? Site? Bug report? Life?

**Comment by wizjany** [comment]
you can't just make an event asynchronous. that's not even for worldguard to decide. a player is killing an entity on the main thread, so events get called on the main thread. why LP doesn't have the user data cached isn't our problem.

**Comment by LucidAPs** [comment]
Thanks for taking the time to explain. Love you.
