### ISSUE TITLE
If the group has a displayname, then max-region-count-per-player will work as for default

### ISSUE THREAD

**Issue by HauserGrim** [EngineHub/WorldGuard#1550]
Reproduce: 
1. Install WG, Vault, LuckPerms
2. Create new group in LP, give permissions for claiming
3. Set limit for new group in max-region-count-per-player (Here we can still create regions)
4. Set displayname for new group (Now the max-region-count-per-player option does not see this group)

No errors in console.
Paper 1.15.2 b158
Plugins: Vault, Luckperms 5.0.72, WorldGuard 7.0.0, WorldEdit 7.1.0

**Comment by wizjany** [comment]
Nothing on our end here. We just use the group list that LP provides through vault.

**Comment by HauserGrim** [comment]
> Nothing on our end here. We just use the group list that LP provides through vault.

I even double-checked and found something else.
WG considers displayname as the name of the group.
For example, if you add the "5regions" group with a limit of 5 regions and make the player group displayname "5regions", then it will have a limit of 5 regions.

**Comment by wizjany** [comment]
we consider whatever LP tells us is the name of the group as the name of the group.
it literally just returns an array of strings and we match that array with the list you put in the `max-region-counts` config: https://github.com/EngineHub/WorldEdit/blob/master/worldedit-bukkit/src/main/java/com/sk89q/wepif/VaultResolver.java#L110
