### ISSUE TITLE
Block-break event doesn't work

### ISSUE THREAD

**Issue by Plixe** [EngineHub/WorldGuard#1551]
Tested with:

- [x] WorldGuard 7.0.2-SNAPSHOT;bf2593e
- [x] WorldGuard 7.0.3-SNAPSHOT;2029
- [x] Spigot 1.15.2 (latest)
- [x] Paper-166 (minecraft 1.15.2)

I have created a region with flags and even if the deny message is showed, player can place blocks. But they can't break them, maybe a PlaceBlockEvent bugs, there is nothing on the console logs... :/
I don't have an other plugin with region system or prevention system. 

Flags used:
- interact: allow
- break-block: deny
- place-block: deny

**Comment by me4502** [comment]
If the message shows up WorldGuard has prevented it. It’s most likely another plugin overriding WorldGuard.
