### ISSUE TITLE
latest version for 1.14.4 and 1.15.2 flag issus on 1.14.4

### ISSUE THREAD

**Issue by dryter97** [EngineHub/WorldGuard#1554]
well literaly all flag i tested is not working. they are apply but not working. paper(243) spigot 1.14.4.

i dont get a lot of info about the issus exept i know flag are not working properly. ho and the pvp deny flag just return hey sorry but you cant pvp here and leave player do damage. invincible is not carring, fall-damage deny not denying fall damage, water flow i denying nothing etc. thats my conclusion atm.

**Comment by wizjany** [comment]
join discord and provide relevant info (logs, region info, etc) if you want support. this is a bug tracker.

**Comment by dryter97** [comment]
nvm thats another plugins interfering
