### ISSUE TITLE
ignore-hopper-item-move-events not working properly?

### ISSUE THREAD

**Issue by Th3Builder45** [EngineHub/WorldGuard#1555]
Despite setting "ignore-hopper-item-move-events" to "true" in the configuration, WorldGuard still seems to contribute a great deal to hopper lag (according to Timings reports). 
This seems to be the case on the newest official WG build as well as the latest snapshot build.

During a stress test with a ton of active hoppers, the "InventoryMoveItemEvent" from WorldGuard was responsible for up to 50% of the hopper lag. See link:
https://timings.aikar.co/?id=f94557754c5a4d3eb3b996efd353f71a
Here you can also see CoreProtect, which is a plugin we do want checking hoppers, is only taking up 5% in comparison.

My servers are running Paper.

**Comment by wizjany** [comment]
this is probably mostly going to be down to bukkit's api snapshotting inventory holders. 130ms seems incredibly high though. would be interested to see a proper sampler/profiler there to confirm my suspicions.
regardless, WG does essentially the minimum possible check there. i don't really care for timings in edge cases like this.
