### ISSUE TITLE
Security bug with usernames

### ISSUE THREAD

**Issue by Floffah** [EngineHub/WorldGuard#1556]
So, today my a user managed to bypass worldguard restrictions. He explained to me that he did it because he used a username that the server sees as a regex query and somehow that bypassed the restrictions. If you want more info from me contact me on discord at Floffah#6791 and the hacker at iTsToastz#2870.

**Comment by wizjany** [comment]
Whatever issue you're attempting to describe sounds like it has nothing to do with WG.
