### ISSUE TITLE
time-lock flag sometimes affects times outside of region

### ISSUE THREAD

**Issue by Carbonixx** [EngineHub/WorldGuard#1557]
Upon spawning in for the first time or logging in inside a region with this flag, an issue sometimes occurs where after you leave the region the time still stays the same, I have checked flags for __global__ and have made sure that there isn't an extra region covering the world which there isn't.  I am using latest WorldGuard version and am running PaperSpigot 182 version 1.15.2. This issue is fixed when relogging.

**Comment by wizjany** [comment]
latest is not a version
