### ISSUE TITLE
time-lock flag does not update when players leave region effected by time-lock

### ISSUE THREAD

**Issue by Carbonixx** [EngineHub/WorldGuard#1558]
WorldEdit version: 7.1.0
WorldGuard version: 7.0.2
Platform version: PaperSpigot 185 MC 1.15.2
I am using WorldGuard 7.0.2 on PaperSpigot 185 MC 1.15.2. I have a "spawn" region with the flag time-lock set to 6000, for players who join for the first time, upon leaving spawn the time-lock flag still effects them staying set to 6000, when asked to relog they can then see the normal server time. This also occurs when logging in when in inside "spawn" region and leaving the region. This also happens when teleporting to "spawn" region then leaving spawn region through teleport. __global__ region has no flags edited.
**To Reproduce**
This bug does not always happen.
I have a "spawn" region with the flag time-lock set to 6000, for players who join for the first time, upon leaving spawn the time-lock flag still effects them staying set to 6000, when asked to relog they can then see the normal server time. This also occurs when logging in when in the "spawn" region and leaving the region. This also happens when teleporting to "spawn" region then leaving spawn region through teleport. __global__ region has no flags edited.
**Expected behavior**
I expected when players leave the region for their client time to be synced with the __global__ region time instead of being stuck at the "spawn" region time.

**Issue Illustrated**
https://www.youtube.com/watch?v=ICdUrtjZFDQ&feature=youtu.be

**Comment by wizjany** [comment]
Unable to reproduce. Have you modified the use-player-move/teleport-events in your config? That's generally the only place this stuff might go wrong.
Can you set a greeting/farewell flag on the region and ensure they trigger when entering and leaving the region correctly? If they do, time-lock should also be triggering.

**Comment by Carbonixx** [comment]
I do have a greeting/farewell and people always comment on how large it is, these same people have encountered these issues. I have not modified use-player-move or teleport-events. I shall log in with an alt account to reproduce the issue I am experiencing.

**Comment by Carbonixx** [comment]
> Unable to reproduce. Have you modified the use-player-move/teleport-events in your config? That's generally the only place this stuff might go wrong.
> Can you set a greeting/farewell flag on the region and ensure they trigger when entering and leaving the region correctly? If they do, time-lock should also be triggering.

I have now added a link to the original post

**Comment by wizjany** [comment]
they're both true by default, and if the titles are working then the time-lock should be going off too.

**Comment by Carbonixx** [comment]
I dont have a teleport-events in the config but user-player-move is set to true

**Comment by Carbonixx** [comment]
Ok so imma say this again, I have not actually edited the worldguard config in any way other than setting time lock in a certain region, global region does not have time lock. But the world still stays at day time. This is becoming a bigger issue as more player join.

**Comment by wizjany** [comment]
I'm still unable to reproduce 10 times out of 10. The only other thing I can say is ensure you're actually using the correct version of WG. Something was fixed around this stuff back before 7.0.1. https://github.com/EngineHub/WorldGuard/commit/96d15d6dbf77ed159c4e2b1564e9536285d65630

Without some dependable reproduction method there's not much I can do here.
