### ISSUE TITLE
I can't turn off invincibility

### ISSUE THREAD

**Issue by Ranbee** [EngineHub/WorldGuard#1559]
So I made a server, and the problem is that neither I can hit anyone, nor mobs cant hit anyone. Everyone is just god. I don't know how it happened, because auto-invincibility was turned off in the first place. I already tried turning it on and off, and typing ungod on people, but that doesnt work. Everyone is just invincible, and I don't want that. I know it's the issue of this plugin in particular, because when i removed it everything started working. Please help, this plugin is really useful and I don't want to get rid of it.

**Comment by wizjany** [comment]
Please don't delete the template. Outside of `/god` and the invincible flag, this is unlikely to be a WG issue, especially since you're the only person with it.
