### ISSUE TITLE
enderdragon-block-damage does not work on my server

### ISSUE THREAD

**Issue by Korleony** [EngineHub/WorldGuard#1561]
WorldEdit version: 7.1.0;8e55131
WorldGuard version: 7.0.2-SNAPSHOT;bf2593e
Platform version: Spigot 1.15.2

**Describe the bug**
I have a world in which spawns dragons for the users who are going to kill them.
In the __global__ of that world I have the flag enderdragon-block-damage with the value deny.
Still, the dragon keeps breaking blocks.
In previous versions I never had any problem.

**Additional context**
The dragon is created by the Mythic mobs plugin. From within this plugin you can create the mob indicating that it does not break blocks. And it certainly doesn't break blocks.

When a reset is made the dragon loses its bond with the Mythic Mobs and remains in the world as a dragon of the natural end. And that's when it starts breaking blocks.
I am working like this since the spigot version of Minecraft 1.8 and World Guard has always protected me. Now it seems that something is wrong with that flag. At least for me.

**Comment by Korleony** [comment]
I have been able to verify that the flag does not block neither the dragons generated with Mythic Mobs, not the ones that remain after the reboots, nor the natural ones that have nothing to do with other plugins.

**Comment by wizjany** [comment]
can't reproduce https://i.imgur.com/qlqGr5W.png
