### ISSUE TITLE
Right-click with tools protection too strict

### ISSUE THREAD

**Issue by UltraFaceguy** [EngineHub/WorldGuard#1565]
**Versions**
WorldGuard version: Bukkit-Official(7.1.0;8e55131)
Platform version: Paper-226

**Describe the bug**
Players cannot access containers, use doors, etc in regions that have allowed interaction if they are holding a tool with a right-click function (axe, hoe, shovel). This results in extremely confusing scenarios especially regarding enderchests in protected areas, and tons of bug reports that I have to deal with.

**To Reproduce**
1) Protect a region
2) Set flags to allowing interacting with containers/anything
3) Watch in horror as you can't interact with anything while holding an axe

**Expected behavior**
Containers and doors can be opened when holding an axe, shovel, hoe... etc

**Comment by wizjany** [comment]
closed by #1566
