### ISSUE TITLE
Hopper are destroyed when they try to pass items into a chest and certain flags are activated

### ISSUE THREAD

**Issue by LordRazen** [EngineHub/WorldGuard#1572]
**Versions**
WorldEdit version:
	Full Name: WorldEdit v7.1.0;8e55131
	Version: 7.1.0;8e55131

WorldGuard version:
	Full Name: WorldGuard v7.0.2-SNAPSHOT;bf2593e
	Version: 7.0.2-SNAPSHOT;bf2593e

Platform version:
Bukkit Version: 1.15.2-R0.1-SNAPSHOT
Implementation: Paper git-Paper-213 (MC: 1.15.2)

**Describe the bug**
If you try to pass an item to a chest via hopper, the hopper is destroyed if certain flags are activated:
- build deny
- chest-access deny

**To Reproduce**
- Place a hopper leading to a chest /direction seem to be umimportant)
- drop an item so the hopper gets it. 

As soon as the item is in the hopper, the hopper drops the item and itsself with a certain chance. 
The bug doesnt appear with a 100% chance, but like around 70% from my testings. 

**Expected behavior**
The dropper dont drop

**Screenshots**
http://prntscr.com/sckayn
http://prntscr.com/sckbdz

**Comment by wizjany** [comment]
Not really sure what you're expecting here. This happens 100% of the time when you set those flags.

**Comment by LordRazen** [comment]
I expect it not to happen. 

Worldguard flags offer possibilities to grief a region - Isnt that what you should protect regions from?

I understand you have to handle the event somehow. But wouldnt deleting the item be a lot more useful then deleting the block (hopper)?

**Comment by daniel-pg** [comment]
For anyone else having the same problem, if you MUST allow hoppers on protected regions, all you have to do is change these configs in `plugins/WorldGuard/config.yml`:
```yaml
ignore-hopper-item-move-events: true
break-hoppers-on-denied-move: false
```
