### ISSUE TITLE
2x2 spruce trees set Podzol on foreign regions 

### ISSUE THREAD

**Issue by TheoRetisch1** [EngineHub/WorldGuard#1575]
**Versions**
WorldEdit version: WorldEdit version 7.2.0-SNAPSHOT+4997-2363440
WorldGuard version: WorldGuard version 7.0.3-SNAPSHOT;2033-5e7829c
Platform version: git-Paper-267 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Describe the bug**
If a 2x2 tree grows at the edge of a region Podzol blocks are placed in the neighbouring build deny region.
![2020-05-10_14 47 39](https://user-images.githubusercontent.com/24480321/81499722-ecfa5080-92cd-11ea-9534-043ac78ad28e.png)

**To Reproduce**
1. Create two neighbouring regions. Give yourself rights on one region and set the other region to build deny.
2. Plant a 2*2 spruce on the border of the build deny region and let it grow using bone meal.

**Expected behavior**
In regions where building is not allowed, block changes should not be possible.

**Additional context**
There are no errors in the log.

**Comment by wizjany** [comment]
last time i looked at this, bukkit just doesn't tell us about these blocks being created. might need investigation.

**Comment by wizjany** [comment]
just to double check... "let it grow using bonemeal" is contradictory...if you are *forcing* it to grow using bonemeal, the player using the bonemeal is included in the cause and the tree will grow if that player has build perms (or has bypass, etc). if you *let it grow* naturally, then it should be protected.

I think your case falls into the former, as I can't reproduce this with natural growth.

**Comment by TheoRetisch1** [comment]
A player can place leaves and podzol in a region for which he has neither a bypass nor building permissions by growing a tree using bonemeal. As long as he has permissions for the area of the trunk, the rest of the tree generation process does not take neighboring regions into account. If I understand your comment correctly, the player should not be able to grow a tree if it could affect regions where he is not allowed to build. This system does not work correctly under the circumstances described in the ticket.

**Comment by wizjany** [comment]
you can say that but it's not going to convince me when i just tested this myself.
natural growth https://i.imgur.com/uzofyy3.png
bonemeal no perms: https://i.imgur.com/p83xIQ9.png
bonemeal with perms: https://i.imgur.com/idbw9cN.png

**Comment by TheoRetisch1** [comment]
Uff I need to figure out my problem then, thank you for your help!

**Comment by TheoRetisch1** [comment]
I finally figured it out, WorldGuardExtraFlags caused the issue, it's fixed! Thank you for your help!

**Comment by stonar96** [comment]
![grafik](https://user-images.githubusercontent.com/18699205/102267364-13463580-3f1a-11eb-8ecf-82b1a9ccda82.png)
GG :P

Joke aside, I already saw you commenting on my WGEF issue, so I knew you have already noticed it. For future reference: https://github.com/aromaa/WorldGuardExtraFlagsPlugin/issues/152
