### ISSUE TITLE
Pistons not working related to build permissions in a region

### ISSUE THREAD

**Issue by speed-MikeM** [EngineHub/WorldGuard#1577]
So I just noticed in 1.15.2 sticky pistons nor pistons will work (push/stick to blocks) if a region is set to: Build: deny

Is there a possibilty to have an exception for pistons?

**Reason**:
In a spawn, redstone doors won't work when build is set to false
In a deathrun: Piston traps won't work as it won't stick to blocks when build is set to false.

If you set build to true in the selected region, then the pistons will work as they should.

**Comment by hvm2308** [comment]
Just don't set the build flag. If you wanna prevent people from building, set `passthrough deny`. [See docs](https://worldguard.enginehub.org/en/latest/regions/flags/#flag-listing).
