### ISSUE TITLE
coral-fade flag doesn't exist

### ISSUE THREAD

**Issue by Aqre** [EngineHub/WorldGuard#1578]
**Versions**

WorldEdit version: 7.1.0
WorldGuard version: 7.0.2
Platform version: Paper 1.15.2 

**Describe the bug**
The flag "coral-fade" doesn't exist. I have a spawn region named "spawn" and typed in the command "/rg flag spawn coral-fade deny" and received "Unknown flag specified: coral-fade". On the WorldGuard documentation, it says coral-fade is a valid flag from the list of flags.

**To Reproduce**
1. Make a region (Skip to Step 2 if you have one already)
2. Type in "/rg flag {region} coral-fade {deny/allow}" and replace {region} with the name of your region.

**Expected behavior**
This flag was supposed to allow coral outside of water without fading its color.

**Screenshots**
None

**Additional context**
None

**Comment by wizjany** [comment]
was literally just added, get a dev build if you need it right now.

**Comment by Aqre** [comment]
Where do I get a dev build? (I'm a little new to Github so I don't know where to look)
