### ISSUE TITLE
Damages

### ISSUE THREAD

**Issue by AliceDeane** [EngineHub/WorldGuard#1579]
**Versions**

WorldEdit version: 7.1.0
WorldGuard version: 7.0.2
Platform version: 1.15

**Describe the bug**
I have disabled fall damages and pvp. Players can't hurt each others but can shoot at each other with a bow (If the bow is power 5 they can kill each other, otherwise it won't do anything). Also Player aren't taking falling damages but when they fall from really high they just die.
It seems that when the damages can "one shot" the player it just does so. I have enabled the invincible flag in the region but it doesn't seem to do anything
Thanks for the support

**To Reproduce**

1. Set fall damage flag on deny
2. Set pvp flag on deny
3. Shoot another player with a bow power 5 (a player without armor)
4. Jump from a high altitude (very high)

**Expected behavior**

I was hoping that the players won't takes any damages

**Screenshots**

**Additional context**

**Comment by wizjany** [comment]
as from discord convo, i need more precise repro. possibly some other plugin is breaking things but i can't reproduce on a test environment:

[4:38 PM] wizjany: ok here's fall damage https://gfycat.com/WaterloggedSecondhandGoldfish
[4:39 PM] wizjany: pvp: https://gfycat.com/nauticalgrimyhorsechestnutleafminer

**Comment by TomyLobo** [comment]
This sounds like the damage handler is working, but the death handler isn't. maybe some other plugin breaks it.
Or maybe some other plugin does even funkier shit, we don't know.
Can you reproduce it with just WorldEdit and WorldGuard installed?
If not, figure out which of your other plugins need to be present in order for the issue to occur.
Then, we (or more likely the author of one of the other plugins) can figure out what causes it.
