### ISSUE TITLE
teleport-on-void-falling not working

### ISSUE THREAD

**Issue by Decme** [EngineHub/WorldGuard#1580]
Test setup:

Paper version 313 - fresh world

Plugins:
worldedit-bukkit-7.2.0-SNAPSHOT-dist (Bukkit-Official(7.2.0-SNAPSHOT+5013-6b918e6))
worldguard-bukkit-7.0.3-SNAPSHOT-dist (Bukkit-Official (7.0.3-SNAPSHOT;2038-9905d22))

No setting changes made except:
teleport-on-void-falling: false -> true

I have ensured there are solid blocks above the void area I jump into

Expected: to be teleported upwards to one of the solid blocks above me.

Actual results: void damage is disabled with the abovementioned setting set to true, meaning you fall forever & never die, and never teleport.

Note, disable-void-damage: is set to false

**Comment by wizjany** [comment]
https://gfycat.com/VerifiableFoolishBeagle
can't repro

**Comment by Decme** [comment]
It's definitely happening: falling below y= -1000 in this video
https://gfycat.com/generalflawedcuttlefish

**Comment by wizjany** [comment]
Not saying it's not happening, I'm saying I can't reproduce, and the code looks fine, so I'm not sure what else I can do here. The alternative is that WG *doesn't* cancel the void damage when attempting to teleport you, so you die, but I think falling forever (and having a chance to get tp'd back) is better than dying and losing stuff. /shrug

**Comment by Decme** [comment]
Any chance you could upload a copy of the WG config you were using?

**Comment by wizjany** [comment]
it's just that option changed, as in your original post
