### ISSUE TITLE
Option to disable Effect.SMOKE in the method playDenyEffect

### ISSUE THREAD

**Issue by dwesolowski** [EngineHub/WorldGuard#1581]
**Feature Request**
I would like a option to disable the Effect.SMOKE in the playDenyEffect on lines 1189 and 1195 in the EventAbstractionListener class, players seem to spam it because they think it's cute or something.

**Describe the solution you'd like**
A config option to disable this effect.

**Comment by wizjany** [comment]
the fact that you went to find the line of code but didn't see the conditional confuses me.

**Comment by dwesolowski** [comment]
I do see a conditional if (!event.isCancelled()), but what do I set to cancel it?

**Comment by wizjany** [comment]
That's not on line 1189 and 1195?

**Comment by dwesolowski** [comment]
Thanks, never mind. I licated it.
particleEffects = config.getBoolean("use-particle-effects", true);
