### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by jobbedf** [EngineHub/WorldGuard#1582]
Does anyone know what command is needed to allow them to place a sign with eg [Buy] or [Sell] in a worldguard locked area?

**Comment by me4502** [comment]
This is an issue tracker, use the discord for support.

Also - WorldGuard doesn’t protect signs, so it’s not WorldGuard causing that.

**Comment by IRazzberryI** [comment]
its probably spawn protection

**Comment by wizjany** [comment]
please don't bump old issues
