### ISSUE TITLE
Flags resetting themselves

### ISSUE THREAD

**Issue by paulalouisee** [EngineHub/WorldGuard#1585]
**Versions**
WorldEdit version: 7.1.0
WorldGuard version: 7.0.2
Platform version: Paper

**Describe the bug**
I am using a plugin called AreaShop along with worldguard and whenever I set flags on areashop regions, they reset, randomly, throughout the day. It is the Use, Interact, Block place and Block break flags that reset.

**Comment by wizjany** [comment]
take it up with areashop? WG doesn't set anything by itself
