### ISSUE TITLE
problem with fly-flag

### ISSUE THREAD

**Issue by M1904** [EngineHub/WorldGuard#1586]
**Versions**
WorldEdit version: 7.1.0;8e55131
WorldGuard version: 7.0.3-SNAPSHOT;2038-9905d22
Platform version: git-Spigot-2f5d615-aae46f8 (MC: 1.15.2)

**Describe the bug**
If I am in a region with flag fly and I am porting out there, I can also fly in all other region without fly-flags (all in gamemode survival without op or fly-permission). When I leave the region across the border, the fly is deactivated. (how it always should be)

**To Reproduce**

1. go in region with fly-flag
2. tp to spawn (or other players or coords)
3. always able to fly

**Expected behavior**
You should not be able to fly outside fly-regions

**Screenshots**
**Additional context**

**Comment by wizjany** [comment]
WorldGuard doesn't have a fly flag.
