### ISSUE TITLE
[API] PlayerDomain.getPlayers() (from ProtectedRegion) returns an empty Set

### ISSUE THREAD

**Issue by Aurelien30000** [EngineHub/WorldGuard#1588]
**Versions**

WorldEdit version: 7.1.0;8e55131
WorldGuard version: 7.0.3-SNAPSHOT;2041-f4a3e8a
Platform version: git-Paper-355 (MC: 1.15.2)

**Describe the bug**

PlayerDomain.getPlayers() (from ProtectedRegion) returns an empty Set / without any members or owners

**To Reproduce**

- Through the API, get a ProtectedRegion with members or owners
- Then, call the method getMembers() or getOwners() that returns a DefaultDomain
- Finally, call getPlayers() on both and see the result, Set is empty :/

**Expected behavior**

Returned Set should contains player names if the region has at least one member or owner.

Thanks ! :)

**Comment by wizjany** [comment]
getUniqueIds

**Comment by Aurelien30000** [comment]
Thanks, but you should remove this method if it's unusable and useless :/

**Comment by wizjany** [comment]
not really
