### ISSUE TITLE
Hoppers in protected area break down

### ISSUE THREAD

**Issue by MrKiller01** [EngineHub/WorldGuard#1591]
**Versions**

WorldEdit version:[20:42:02] [Server thread/INFO]: WorldEdit version 7.2.0-beta-01+0eb9ac7

WorldGuard version:[20:42:27] [Server thread/INFO]: WorldGuard version 7.0.1-beta-01;14e7525
(Problem seems to be there since 1.15 or maybe earlier....)

Platform version:[20:41:14] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-16d7899-4ff609e (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[20:41:14] [Server thread/INFO]: Checking version, please wait...
[20:41:14] [Thread-19/INFO]: You are running the latest version

**Describe the bug**
<As I think this is a bug, correct me if i'm wrong. Hoppers stationed in protected areas (flags set build = deny, block-break = deny, chest-access = deny). First place a construction of a few hoppers connected (doesn't matter horizontal or vertical) and a chest on top to fill. Then make a region around that construction, set those flags of that area i named before, and place 64 stone in the chest to let transport. If all is right as I noticed, the first connected hopper breaks down when you enter the 64 stone in the chest.>

**To Reproduce**

1. ...First place a construction of a few hoppers connected (doesn't matter horizontal or vertical) and a chest on top to fill. 
2. ...Then make a region around that construction, set those flags of that area i named before, and place 64 stone in the chest to let transport. If all is right as I noticed, the first connected hopper breaks down when you enter the 64 stone in the chest.

**Expected behavior**
<obviously, I'd expect the items placed in the chest being transported without breaking the line if I want this area to be protected from griefers, thieves, tax collectors.> (-:

**Screenshots**

**Additional context**

**Comment by MrKiller01** [comment]
WHY?

**Comment by MrKiller01** [comment]
I take carefully the time to describe my problem and You just close it without anything to say? That is a way to get rid of problems.... At least TELL ME what is wrong here!!!!

**Comment by wizjany** [comment]
literally using a year old build and this is a support request not a bug report and you literally denied all the flags to make this happen

**Comment by MrKiller01** [comment]
Year old build of what?

**Comment by MrKiller01** [comment]
Did you not read it has happened to me before, maybe already in 2018.....

**Comment by MrKiller01** [comment]
and what flags did I deny???? I am not posting here rubbish, because I think that you can help this problem go away..... but, as you stated, I will try to find the newest, worldguard I presume, and test it again.

**Comment by MrKiller01** [comment]
ps and about what you wrote "this is a support request not a bug report " then something is wrong with the website, I clearly went to Worldguard and clicked on BUG REPORT....

**Comment by wizjany** [comment]
yes, github is a place to file bug reports. i'm telling you this isn't a bug, you just have no clue how to use the plugin. clicking "new issue" here on github even tells you to go to discord if you have questions.

**Comment by MrKiller01** [comment]
Oh, I'm sorry if I disturbed you, You know exactly what this is and how to make it go away, we as server owners who do not get paid also, have to remember over a hundred things every day, so excuse me if I did not go to that babble box and tried to get some info, I do not have the time for that, sorry.
Close this and maybe in a year or so I ll ask again.

**Comment by Ek2100** [comment]
Hey wizjany. This bug is still present in the latest build 😄!

**Comment by aurorasmiles** [comment]
see https://worldguard.enginehub.org/en/latest/config/#event-handling
not a bug

**Comment by Ek2100** [comment]
How can you resolve the issue so that the hoppers dont instantly self destruct
