### ISSUE TITLE
Constant rain

### ISSUE THREAD

**Issue by BenRulez** [EngineHub/WorldGuard#1592]
**Versions**

WorldEdit version: 7.2.0-beta-01
WorldGuard version: 7.0.2
Platform version: git-spigot-16d7899-4ff609 (MC:1.16.1_

**Describe the bug**
Before updating to 1.16.1 one of the regions had Weather Lock Sun, when i updated that region turned to constant rain, even when i remove the weather lock flag, clear the weather, even with the plugin uninstalled its always rain now.

**To Reproduce**
Add region weather lock in 1.15.2
Update server + plugins to latests versions 1.16.1

**Expected behavior**
not rain

**Screenshots**

**Additional context**

**Comment by wizjany** [comment]
weather-lock is entirely client side, it doesn't touch world weather.
if the issue persists even without the plugin it's not the plugin causing it.
