### ISSUE TITLE
mob-spawning broken

### ISSUE THREAD

**Issue by palyons** [EngineHub/WorldGuard#1596]
**Versions**
WorldEdit: * Bukkit-Official(7.2.0-beta-01+0eb9ac7)
WorldGuard: WorldGuard 7.0.4-beta1
Platform version: git-Paper-"c63757c1" (MC: 1.16.1)

**Describe the bug**
Mobs (Skeleton, Husk, Pillager, Creepers(absent, can't summon/spawn for some reason) are still spawning in a defined region, with:
Flags: mob-spawning: deny
Other flags:
        flags: {other-explosion: deny, lava-fire: deny, water-flow: deny, invincible: allow,
            greeting: Welcome to Survival!, interact: allow, vehicle-destroy: deny,
            chest-access: allow, fire-spread: deny, enderdragon-block-damage: deny,
            sleep: allow, vehicle-place: deny, snowman-trails: deny, mob-damage: deny,
            entity-painting-destroy: deny, lightning: deny, wither-damage: deny, lighter: deny,
            enderman-grief: deny, pvp: deny, enderpearl: deny,
            creeper-explosion: deny, item-pickup: allow, damage-animals: deny, tnt: deny,
            lava-flow: deny, ghast-fireball: deny, entity-item-frame-destroy: deny,
            farewell: 'Now leaving the spawn area, good luck, and have fun!'}

**Expected behavior**
Mobs should not be spawning in the defined region

**Comment by wizjany** [comment]
can't repro

**Comment by IRazzberryI** [comment]
I have this issue to! I do mob-spawning deny but monsters still keep spawning in that region!!

**Comment by TechnicallyCoded** [comment]
I have the same issue
