### ISSUE TITLE
Itemframes can be placed down and broken even when disabelde

### ISSUE THREAD

**Issue by Cryptics1999** [EngineHub/WorldGuard#1600]
**Versions**
1.16

WorldEdit version:
worldedit-bukkit-7.2.0-beta-01.jar
WorldGuard version:
worldguard-bukkit-7.0.4-beta1.jar
Platform version:
Paper version 1.16.1 aPi 1.16.1 -R0.1 -snapshot

**Describe the bug**

People can place down and break itemframes

**To Reproduce**

1. download what I got and
2. have build and place on deny and itemframe-entinty-destroy on deny
3: player without perm can destroy

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by wizjany** [comment]
None of those flags should be set to protect a region. Also can't reproduce anyway, gonna need more info.
