### ISSUE TITLE
Cant break blocks in nether

### ISSUE THREAD

**Issue by iWisd0M5d** [EngineHub/WorldGuard#1605]
**Versions**

WorldEdit version: 7.2.0 beta 01

WorldGuard version: 7.0.4 beta1

Platform version: Paper

**Describe the bug**

 i cant break blocks in the nether 1.16.1
**To Reproduce**

1. ... diamond pickaxe 
2. ... try to break netherrack or gold and nothing

**Expected behavior**

 Should broke the block

**Screenshots**

**Additional context**

**Comment by wizjany** [comment]
do you get a message or something? have you reproduced without other plugins?
doesn't seem like a WG issue at all..
