### ISSUE TITLE
Signs don't show what was pre-written to hem.

### ISSUE THREAD

**Issue by MegaKoe** [EngineHub/WorldGuard#1606]
**Versions**

WorldEdit version:
7.2.0-beta-02
WorldGuard version:
7.0.4-beta1
Platform version:
git-Paper-88 (mc: 1.16.1)

Problem/bug : 
Signs in a certain area protected by worldguard have the chance of not showing all words that are written on there until the player breaks the sign and then sign respawns properly (these players are no members/owners of the region, flags in the attached picture).

To Reproduce:
1. Write alot of rules/guidelines on signs in a protected area (spawn).
2. New people join and notice that the sentences and the words don't add up thus not understanding what all the rules are.

Expected behavior:
The signs should display all pre-written text to all players.

Additional context:
I've tested it without texturepack and other plugins than WE and WG. It's not always the same text that dissapears and not everybody has it.

report and screenshot:

[report.txt](https://github.com/EngineHub/WorldGuard/files/4907562/report.txt)

![screenshotworldguard](https://user-images.githubusercontent.com/68165848/87233388-30a13180-c3c7-11ea-99aa-1be6d9f54137.PNG)

**Comment by wizjany** [comment]
going to need some more compelling evidence that this has anything to do with WG at all.
