### ISSUE TITLE
Turtle eggs

### ISSUE THREAD

**Issue by Nastroszona** [EngineHub/WorldGuard#1609]
WorldEdit version: 7.1.0;8e55131

WorldGuard version: 7.0.2-SNAPSHOT;bf2593e

Platform version: git-Paper-374 (MC: 1.15.2) (Implementing API version 1.15.2-R9.1-SNAPSHOT)

Describe the bug
When player throw items on turtle's eggs they will be break down.

To Reproduce

Take some cobblestone
Throw it on eggs

Expected behavior
Turtle's eggs won't be break down.

Screenshots
https://zapodaj.net/39e6552585846.png.html

P.s. sorry for the other post, I misunderstood the matter..

**Comment by wizjany** [comment]
please don't create duplicate issues.

**Comment by Nastroszona** [comment]
It's other post, please, remove the other post...
