### ISSUE TITLE
Lack of RGB support

### ISSUE THREAD

**Issue by NotStarRift** [EngineHub/WorldGuard#1610]
![image](https://user-images.githubusercontent.com/17240279/87602499-f4fab600-c6ab-11ea-90c8-b02de995bbdb.png)

**Comment by wizjany** [comment]
not even using the template...

**Comment by NotStarRift** [comment]
> not even using the template...

I really don't care. The screenshot and title alone is pretty self explanatory as to what the project is lacking and what room there is for improvement. I'm just saving everyone time here.
