### ISSUE TITLE
HopperMinecarts not working properly

### ISSUE THREAD

**Issue by gt2416** [EngineHub/WorldGuard#1611]
Worldguard Version 7.03
Minecraft Version: 1.16.1
Server Version: Paper 1.16.1 build 99

**Is your feature request related to a problem? Please describe.**
If you place a hopper minecart with a trapdoor above it, with another hopper minecart on top of the trapdoor, the bottom one does not pick up items from the top one within a builders region. Even if the builder replaces the blocks it still doesnt work. This is fixed as soon as the region is removed. 
This mechanic is used in most villager crop farms.

**Describe the solution you'd like**
It should work like vanilla when you have appropriate permissions.

**Comment by wizjany** [comment]
either allow chest-access or disable hopper protection in the config.

**Comment by gt2416** [comment]
Ok, I dont want to allow chest access but cant find a way to change the hopper protection, could you please tell me how to do that.
