### ISSUE TITLE
New flag suggestion

### ISSUE THREAD

**Issue by zasnaz** [EngineHub/WorldGuard#1614]
Hello,
I have a suggestion which is adding a new flag called "rebuild".
What this flag does is saving the selected buildings and every thing inside the region as it is and auto rebuilding it after a specific minutes, By this feature we can allow the players to build and break but they can't grief for a long time.
For example :
/region flag spawn rebuild 10m.
Thank you.

**Comment by wizjany** [comment]
don't think this really belongs in WG, would do much better as a separate plugin using the API.
