### ISSUE TITLE
MagmaBlock/Soulsand Water-flow bug

### ISSUE THREAD

**Issue by TheRealAws** [EngineHub/WorldGuard#1616]
WorldGuard version:
7.0.4-beta1

Platform version:
1.16 Paper-127

**Bug Description**
When a magma block or soulsand block is placed below water I.E to create a water elevator, with the region flag of water-flow deny, water will flow outwards by 1 block and then stop which causes an issue like this: https://gyazo.com/1493b4f811f15aa2df60b23cc4375448

**To Reproduce**
1. /rg flag __global__ water-flow deny
2. Place water inside of "water-elevator"
3. Placed magmablock or soulsand at bottom of water-elevator 
4. (Or place magma/soulsand first then water) causes same issue either way around.

**Expected behavior**
Denies water-flow to only the 1 block.

**Screenshots**
https://gyazo.com/1493b4f811f15aa2df60b23cc4375448

**Comment by wizjany** [comment]
https://i.imgur.com/qTF3UpC.png ? am I doing something wrong? your image is honestly really unclear.

**Comment by wizjany** [comment]
ok the whole water elevator thing was a complete red herring.
actual reproduction steps are:
1. place magma or soul sand
2. place water directly on top of that block
3. let the water turn into a bubble column and then trigger a block update.
(or even just set a bubble column on top of any block. 1 & 2 are just the natural way to make a bubble column)
