### ISSUE TITLE
Prevent Nether Portal creation in guarded regions

### ISSUE THREAD

**Issue by javaarchive** [EngineHub/WorldGuard#1619]
**Is your feature request related to a problem? Please describe.**
well I found out I could make a nether portal in the nether that corresponds to a world guarded area in the overworld causing a nether portal to appear there. It was annoying the admins so they world guarded the nether also but in 1.16.1 we'll probaly want to make strider highways.

**Describe the solution you'd like**
Make a flag to disable players creating nether portals from either side if the other side is world guarded and the player doesn't have permission. Simply prevent the portal from being lit and show a message. 

**Describe alternatives you've considered**
Not really sure about alternatives

**Additional context**
Unfortunately I don't have any screenshots on this computer

**Comment by wizjany** [comment]
Likely just need to turn the config option on as it was default false before mojang changed how portals work. As for preventing it from being lit to begin with, there's literally no way to know where the portal will end up before the player tries to go through it, so that's not going to happen.
