### ISSUE TITLE
Slimefun Seismic axe

### ISSUE THREAD

**Issue by 100petr** [EngineHub/WorldGuard#1624]
**Versions**

WorldEdit version:
WorldEdit 7.2.0-SNAPSHOT - Bukkit-Official(7.2.0-SNAPSHOT+5135-624e416)
WorldGuard version:
WorldGuard 7.0.4-SNAPSHOT -  Bukkit-Official (7.0.4-SNAPSHOT+2062-58eaf31)
Platform version: 
Paper-133 (MC: 1.16.1)

**Describe the bug**

Using a seismic axe from slimefun drops blocks in WG region. 

**To Reproduce**

1. Install Slimefun 4 and CS-Corelib
2. Create any region
3. Set the block-place in region to deny
4. Use seismic axe - it drop blocks
https://youtu.be/2yXhXcwvb-Y

**Expected behavior**
The blocks will not drop if block-place is deny

**Screenshots**

![Screenshot_2](https://user-images.githubusercontent.com/29830635/89672640-49790600-d8e5-11ea-8590-bcfa99a58a39.png)

**Additional context**

We wrote it on slimefun github, they wrote that it is a worldguard problem. https://github.com/TheBusyBiscuit/Slimefun4/issues/2114

**Comment by wizjany** [comment]
while this is technically a bug, I'll point out that it won't happen if you don't mess with those flags, as it clearly tells you not to.

**Comment by 100petr** [comment]
thank you
