### ISSUE TITLE
1.16 Redstone Dots Changeable by Non-owners of Regions

### ISSUE THREAD

**Issue by ThatBenKraft** [EngineHub/WorldGuard#1625]
**Versions**

WorldEdit version: 7.2.0 beta 02

WorldGuard version: 7.0.4 beta 1

Platform version: Minecraft 1.16.1

**Describe the bug**

In regions owned by a specific player, non-owners can interact with redstone dust dots, changing the property of how the redstone acts.

**To Reproduce**

1. Create a region
2. Place a single redstone dust
3. Any player can interact with the redstone cross/dot state

**Expected behavior**

The ability for any player other than an owner to not be able to change a redstone dot/cross.

**Additional context**

A recent mechanic was added in 1.16 in which you can interact with a redstone dust block to change it from powering the blocks around it by default (a cross) to only powering below it (a dot).

**Comment by wizjany** [comment]
has been fixed in dev for like a month or something now
