### ISSUE TITLE
Nether __global__ expansion

### ISSUE THREAD

**Issue by voigtman** [EngineHub/WorldGuard#1626]
My recommendation is a split global region for the Nether - above and below the upper bedrock. 

A secondary global region above the nether bedrock would enable server owners to better manage this region of space. 
It would give owners the ability to deny certain commands above bedrock (i.e. deny /sethome or /setwarp) It could be used to deny fire-spread above the nether bedrock. It would also useful for server owners the ability to deny or allow ender-pearling, give the area it's own welcome and exit messages, deny spawning of certain mobs.. etc.

Ultimately, as stated before, it would enable server owners to have greater control over this entire region of the nether world.

**Comment by wizjany** [comment]
Is there anything this actually accomplishes that you can't just do with normal regions?

**Comment by voigtman** [comment]
Yes it gives control over the global region above the nether without affecting the lower region in anyway

**Comment by wizjany** [comment]
Please re-read the question. Why can't you just make a normal region for this?

**Comment by voigtman** [comment]
Please lose the attitude, we are both adults. Are you suggesting making a smaller region?

**Comment by wizjany** [comment]
I don't have an attitude. I asked a question and you completely missed it.

**Comment by voigtman** [comment]
and you still haven't answered mine

**Comment by wizjany** [comment]
clearly this isn't going anywhere so i'm assuming this doesn't actually accomplish anything you can't do already.
