### ISSUE TITLE
temporary unprotect after teleport

### ISSUE THREAD

**Issue by totoserver** [EngineHub/WorldGuard#1627]
server ver: 1.14.4-R0.1-SNAPSHOT
plugin ver: 7.0.1;f2118aa
Plugins: ![2020-08-16_21 26 15](https://user-images.githubusercontent.com/69592017/90334233-37931380-e007-11ea-8052-8e10242a6725.png)

when i teleport then build its temporary not Protected

**Comment by wizjany** [comment]
don't even know how i'm supposed to go about reproducing this.
worldguard doesn't even care where you are when you build, it only cares if the block is protected.
