### ISSUE TITLE
Add a way to configure whether region bypass is on by default

### ISSUE THREAD

**Issue by bitrot-alpha** [EngineHub/WorldGuard#1630]
**Is your feature request related to a problem? Please describe.**

I expect protection plugins to always protect by default, and right now, one mis-click means I need to recover blocks broken by myself or other admins. Whenever I log in with my admin account on my server, if I forget to turn off region bypass, I end up breaking something at the spawn when I'm not paying attention.

`basically add idiot protection for server admins who don't want to mess up player builds by accident`

**Describe the solution you'd like**

- **config.yml**
Add a line to set whether region bypass is ON or OFF by default for admins

**and/or**

- **Region flags**
Add a flag to set whether region bypass is automatically ON/OFF

- **Permissions**
A permission that can be denied to set region bypass to off by default, but not actually deny region bypassing altogether

- **Additional Idiot Protection**
A special message the first time you break a block in a protected WG region to run `/rg bypass` if it is off, and a warning if it is on.

**Describe alternatives you've considered**

Previously, I've used the Safezone feature from a Factions plugin, but have moved away from that because of the versatility and ease of use of WorldGuard regions. The one thing missing is that I don't have "idiot protection" like the Factions plugin did.

**Additional context**

_Note:_ I am using the `*` permissions node for my server's highest rank, Owner, and only denying permissions to that rank that break expected behavior/gameplay from plugins. I realize that there are _many_ worldguard permissions to set, so if I missed something, I'll happily close this issue if this feature already has an implementation.

_Kudos:_ I appreciate how well documented this family of plugins is. It only took me ten minutes to figure out that I needed to run `/rg bypass` to test if I was using WorldGuard properly.

**Comment by wizjany** [comment]
0e73b50d6faf4dbb9566f87bea56165074b5e163
