### ISSUE TITLE
damage-animals flag should protect striders

### ISSUE THREAD

**Issue by phemmer** [EngineHub/WorldGuard#1634]
**Is your feature request related to a problem? Please describe.**

Not sure if bug (update needed for 1.16), or feature request, but currently the `damage-animals` flag doesn't protect striders like it does with other passive mobs. As striders can hold equipment, such as saddles, and it takes effort to gather them, I think they should be protected.

**Describe the solution you'd like**

When permission is set to deny on the damage-animals flag, striders should not be able to be damaged.

**Describe alternatives you've considered**

None

**Additional context**

WorldGuard version 7.0.4 beta 1

**Comment by wizjany** [comment]
Bukkit classifies them as a Monster, not a passive mob. Not entirely sure it makes sense for us to break that classification here, but maybe I'm missing some gameplay context. Are they somehow tameable but not normally passive?

**Comment by phemmer** [comment]
They're always passive. But you don't tame them. Just have to throw a saddle on them and go.

I'm not sure what being classified as a "monster" is about, but it doesn't seem to do with "passiveness", as neither phantoms or magma cubes (and probably others, but those 2 I recall off the top of my head) are classified as monsters, but both are hostile.

**Comment by me4502** [comment]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Mob.html, the `all known subclasses` section here are all the entities that Bukkit considers monsters

**Comment by wizjany** [comment]
I said passive because you did. Specifically the interface in question is https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Monster.html
A few hostiles were manually added to the hostile list because mojang/bukkit doesn't classify them as monsters. https://github.com/EngineHub/WorldGuard/blob/master/worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/util/Entities.java#L151

**Comment by phemmer** [comment]
@me4502  you linked `Mob`, not `Monster`. Monster is here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Monster.html

**Comment by phemmer** [comment]
> I said passive because you did. Specifically the interface in question is https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Monster.html
> A few hostiles were manually added to the hostile list because mojang/bukkit doesn't classify them as monsters. https://github.com/EngineHub/WorldGuard/blob/master/worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/util/Entities.java#L151

Ok, but to be honest, I'm not sure what you're getting at. Are you saying we should use the `isHostile()` check to determine whether striders should be protected?

**Comment by wizjany** [comment]
No, I was explaining why phantoms and magma cubes (and slimes, ghasts, enderdragons, and shulkers) are considered "not passive" despite being "not monsters".

**Comment by phemmer** [comment]
Sorry, I'm really confused as to how this is relevant to the issue. The original statement was:

> Bukkit classifies them as a Monster, not a passive mob.

But you're saying whether it's classified as monster or not is not directly related to whether it's passive. So then how does this relate to whether Striders are protected or not?

**Comment by wizjany** [comment]
The original statement (yours) was
>  but currently the damage-animals flag doesn't protect striders like it does with other passive mobs
I was saying that striders, according to bukkit, are a monster, unlike "other passive mobs". You're the one who started asking about hostiles, I was just answering questions.

**Comment by wizjany** [comment]
doesn't seem to actually be an issue, seems striders aren't even monsters.
