### ISSUE TITLE
item-drop protection falsely triggers with command blocks / console commands

### ISSUE THREAD

**Issue by cyberkitsune** [EngineHub/WorldGuard#1635]
**Versions**
WorldEdit version: 7.2.0-beta-04

WorldGuard version:WorldGuard 7.0.4-beta1

Platform version: Bukkit-Official(7.2.0-beta-04+98f71a3)

**Describe the bug**
Giving a player an item via minecraft:give from the console or a commandblock while item-drop is false in the region results in "You can't drop items here" and a duplicate item is given to the player.

**To Reproduce**
1. Run `/region flags __global__ item-drop deny`
2. Create a command block with `minecraft:give @p dirt 1`
3. Have a non-privileged player trigger the command block twice
4. Note the permission warning on the second run and the duplicated item

**Expected behavior**
Only one item should be given to a player when a command block or console command is triggered, and worldguard should not block this.

**Screenshots**
https://assets.cyberkitsune.net/share/2020-09-01_17-52-11.gif

**Comment by wizjany** [comment]
https://github.com/EngineHub/WorldGuard/issues/1274
