### ISSUE TITLE
mob-spawning set to deny doesn't seem to work.

### ISSUE THREAD

**Issue by cavinnhobbes** [EngineHub/WorldGuard#1636]
**Version information**:
WorldEdit version:
7.2.0-beta-04
WorldGuard version:
7.0.3
Platform version:
git-Spigot-b5a13e6-3980640

**Description**:
After creating a region, setting its bounds, and setting up all the flags the way it needed to be, I discovered that even with mob-spawning set to deny, mobs still continued to spawn in the selected region.
I figured perhaps it was because a list of mobs to deny was required under deny-spawn, so I made a list of the natural mobs I didn't want spawning in the region, however after doing this it still spawned the mobs defined in the list.
Multiple server restarts and tests were done to ensure the formatting of the list was correct, and as far as I'm aware, it is.

**Steps to reproduce are as follows**:
1. Create and define a region space.
2. Define the flag for mob-spawning to DENY.
3. Define the flag for deny-spawn to be any list of namespaced mob IDs, ex: ['minecraft:bat','minecraft:creeper'].

**Expected functionality**:
What should be expected is for the mobs listed in the deny-spawn list while mob-spawning is set to DENY to not spawn in the defined region, this however does not seem to be the case, at least with the versions I'm running.

**Results from /wg report -p**:
https://paste.enginehub.org/JAZKdxemj.report

**Comment by wizjany** [comment]
you turned off the creature spawn event in WG config.
