### ISSUE TITLE
time limit on region flags

### ISSUE THREAD

**Issue by elaineandsparky** [EngineHub/WorldGuard#1643]
For example. I would like players to be able to temporarily buy the ability to block phantoms for everyone in my __global__ region. So a flag with a time limit would be one way I can think of to be able to do this and as far as i can see this is not currently an option. The command could be something like /rg flag __global__  deny-spawn phantom 1hr true 

Other uses would be if i wanted to host a time limited event such as pvp i could set a timer for pvp to be allowed globally or in a set region. I wouldn't need to be online at the end of the event to turn pvp back off. Or if i wanted to grant players access to gmc temproarily and not have to be online at the end of that time. etc etc etc.

**Comment by wizjany** [comment]
I don't believe this fits in the scope of WG. Much better suited to a third-party plugin using the API.
