### ISSUE TITLE
Resolving error when Offline mode

### ISSUE THREAD

**Issue by wanou067** [EngineHub/WorldGuard#1646]
WorldGuard version:
6.2.2
Platform version:
Spigot 1.12.2

When i Try to add a player of my server who is disconnect and do not have a mojang account because my server allow offline mode, i can't add it.

**To Reproduce**
1. Set online mode to false and join with a name that is not used by any mojang account
2. Disconnect
3. Execute /rg addmember yourregion -w world playername
4. The message is: Failed to add new members: Unable to resolve the names "playername"

**Expected behavior**
Possibility to add this user !

**Comment by wizjany** [comment]
old versions and offline mode are unsupported.

**Comment by wanou067** [comment]
Seriously...

**Comment by Scarldoc** [comment]
https://github.com/EngineHub/WorldGuard/issues/1652
dont even try
