### ISSUE TITLE
WG/ WE Cause console spam and crashes

### ISSUE THREAD

**Issue by Scarldoc** [EngineHub/WorldGuard#1652]
**Version**
WorldEdit version: FAWE-302 

WorldGuard version: 7.0.0

Platform version: git-spigot01a3504a-dfa7583 (MC: 1.13.2) API 1.13.2-R0.1-Snapshot

**Describe the bug**
As soon as a finite selection of players join the console is instantly spammed with the text within the mcpaste link.
oh, and the plots world died, that might be some information of value (when I tp the server freaks out and wont let my type or warp)

**To Reproduce**

1. Have this this specific player join your server "CalebHatesLag"
2. Bam, Console freaks out and the TPS dies

**Expected behavior**

The server not to crash, get spammed and drop in TPS. I don't know?

**Screenshots**

![image](https://user-images.githubusercontent.com/67122107/96373020-c89a7e00-1161-11eb-9fea-fdc52ba754e7.png)

**Additional context**

https://mcpaste.io/b0ac9f29d3418e2f

**Comment by wizjany** [comment]
FAWE isn't supported.

**Comment by Scarldoc** [comment]
I forgot to mention that I also used WorldEdit 7.1.0 and the same issue occurs. please dont make me do this again

**Comment by wizjany** [comment]
would need an actual full log with WE then.

**Comment by Scarldoc** [comment]
https://mcpaste.io/c7195866f1f97582 this was it when i had WE 7.1.0. I can try and find one that doesnt have the same message continuously, but i do have the crash report from then 
[crash-2020-10-17_22.53.01-server.txt](https://github.com/EngineHub/WorldGuard/files/5397767/crash-2020-10-17_22.53.01-server.txt)

**Comment by wizjany** [comment]
still completely useless.

**Comment by Scarldoc** [comment]
ah here you are https://mcpaste.io/700cf8ed816a882b

**Comment by wizjany** [comment]
still no. please stop wasting my time with useless logs. you're not even running a supported version.

**Comment by Scarldoc** [comment]
that was a startup, if you go to line 426 it starts there
