### ISSUE TITLE
Sticky pistons do not work with block-place and block-break denied

### ISSUE THREAD

**Issue by DaAwesomeP** [EngineHub/WorldGuard#1653]
**Versions**

WorldEdit version:  7.2.0-beta-05+e575ffe

WorldGuard version: 7.0.4

Platform version: Paper-220

**Describe the bug**

Sticky pistons do push or pull blocks with `block-break` and `block-place` set to `deny` (I did not test with normal pistons).

**To Reproduce**

1. Set `__global__` `block-break` and `block-place` to `deny`. `build` has not been set.
2. Sticky pistons no longer push/pull blocks (I did not test with normal pistons)
3. Attempt to create a region in side `__global__` with `pasthrough` `allow` and `block-break` and `block-place` to `deny` as a workaround.
4. Sticky pistons still do not push or pull blocks. Setting `pistons` to `allows` also does not work.

**Expected behavior**

Pistons should push and pull blocks regardless of `block-place` and `block-break`. The tested pistons were not destroying blocks.

**Additional context**

Use case is preventing building/breaking a world after a competition so but still allowing all redstone, pistons, interactions, etc.

**Comment by DaAwesomeP** [comment]
Why was this immeadietly marked as invalid?

**Comment by wizjany** [comment]
it literally gives you a big red warning in chat when you touch those flags.

**Comment by DaAwesomeP** [comment]
OK, but then I read 3 full pages of docs including [this page](https://worldguard.enginehub.org/en/latest/regions/flags/) which says that `block-break` ONLY affects pistons if pistons are breaking blocks. It says nothing about stopping pistons entirely. The chats has some red text, but the docs say only "Whether blocks can be mined" and "Whether blocks can be placed."

If I am trying to do this incorrectly, then what is the recommended method to allow all region permissions to players by default except placing and breaking blocks?
