### ISSUE TITLE
Add SSL server identity verification

### ISSUE THREAD

**Issue by cfw34683** [EngineHub/WorldGuard#1654]
simply put need a setting in the config.yml under

    sql:
        use: true
        usessl: true/false
        verifyServerCertificate: false/true
        dsn: jdbc:mysql://localhost/worldguard
        username: worldguard
        password: worldguard
        table-prefix: wg_

reason being is that after MySQL 5.5.45 and on these are required vavlues if you have ssl on for Mysql 8.0 which now comes with ssl build in and ca files ready and pem finles ready. just need to actiavte it. doing so breaks worldguard and coreprotect for that matter. LUCKPERMS has no issue as it has those commands added in under a properties secition for mysql

**Comment by me4502** [comment]
The MySQL backend isn't really supported. It's not recommended to use it.

**Comment by cfw34683** [comment]
well even if its not i found a way around the warnings.. and i think you could turn on ssl with this as long as you had server verification witth you CA and pem files setup. which mysql 8.0 comes preinstalled now with. in short.. this activates it and with false settings suppresses all warnings

Database: jdbc:mysql://localhost:3306/worldguard?autoReconnect=true&useSSL=false&verifyServerCertificate=false

**Comment by wizjany** [comment]
i mean you'd have to set it to true but yes that's pretty standard and people have been using it for ages. really no sense making an extra config since all that would do is append the params for you.
