### ISSUE TITLE
new Placeholders or fix old

### ISSUE THREAD

**Issue by NESTOWL** [EngineHub/WorldGuard#1656]
**Is your feature request related to a problem? Please describe.**
when 2 regions intersect, then in the placeholder they constantly change in turn

**Describe the solution you'd like**
 logical to display a higher priority region, or they should be listed separated by commas

example of placeholders:
`%worldguard_region_name_priority%` - the name of the priority region
`%worldguard_region_names%` - names of all regions in this position, separated by commas!

**Describe alternatives you've considered**
I have not found alternative solutions

**Additional context**
![1111111111](https://user-images.githubusercontent.com/45520187/96707553-b4908f80-13a0-11eb-901b-0c4737d1861d.gif)

**Comment by JOO200** [comment]
WorldGuard doesn't provide any placeholders. Ask the plugin developer from the placeholders for support.

**Comment by NESTOWL** [comment]
Okay, I apologize for not writing there
Opened here [#495](https://github.com/PlaceholderAPI/PlaceholderAPI/issues/495)

**Comment by NESTOWL** [comment]
wtf? I was sent back to here

**Comment by me4502** [comment]
No you weren't, they told you go somewhere else

**Comment by NESTOWL** [comment]
I figured out where to go, thanks!
Sorry again for writing in the wrong place.
