### ISSUE TITLE
Spam in console

### ISSUE THREAD

**Issue by sergyops** [EngineHub/WorldGuard#1664]
**Versions**
WorldEdit version: WorldEdit versión 7.2.0-rc2

WorldGuard version: WorldGuard 7.0.4

Platform version: git-Paper-240 (MC: 1.16.3)

**Describe the bug**
A lot of spam in console from world guard

**Screenshots**
![image](https://user-images.githubusercontent.com/70977028/97784780-410d3000-1ba1-11eb-8bb8-5b8636bc6b8d.png)

**Comment by wizjany** [comment]
not a bug, just means something is changing regions constantly.
