### ISSUE TITLE
Cache Breaks Worldguard

### ISSUE THREAD

**Issue by headblockhead** [EngineHub/WorldGuard#1666]
**Versions**

WorldEdit version:
 7.2.0
WorldGuard version:
7.0.4
Platform version:
git-Paper-246 (MC:1.16.3)

**Describe the bug**

When joining or interacting with the server in any way the console if flooded with errors 
"[12:39:47 WARN]: [WorldGuard] Task # 642 for WorldGuard v7.0.4+f7ff984 generated an exception" and 
"[12:41:13 ERROR]: Could not pass event PlayerQuitEvent to WorldGuard v7.0.4+f7ff984"
and worldguard doesn't work ( Breaking and placing is not replied to by "HEY!" in the chat or any consequences in the world )

**Screenshots**

![image](https://user-images.githubusercontent.com/26520767/99073627-2d54c700-25ae-11eb-9382-d8deceace0fb.png)

**Additional context**
This can be solved by deleting the "cache" folder inside plugins/WorldGuard but upon the next restart of the server, it will go back to producing errors

**Comment by me4502** [comment]
Looks like you're just missing WorldEdit?

Use the discord for support.

**Comment by headblockhead** [comment]
![image](https://user-images.githubusercontent.com/26520767/99074342-7c4f2c00-25af-11eb-97b1-80a47a663ea0.png)

**Comment by me4502** [comment]
I'm just telling you what your logs say.

As I said, use the discord for support

**Comment by headblockhead** [comment]
ok
