### ISSUE TITLE
[BUG] Denying vine-growth does not effect lateral growth between blocks

### ISSUE THREAD

**Issue by OreoKirby** [EngineHub/WorldGuard#1668]
**Versions**
WorldEdit version:
7.2.0-beta-05
WorldGuard version:
7.0.4+f7ff984
Platform version:
Paper-251 (1.16.3)

**Describe the bug**
Vines are growing laterally across blocks in 1x1 gaps if vine-growth is disabled using flags or the world config.yml file.

**To Reproduce**
1. Create a region and deny vine-growth and/or disable globally in the world config.yml file.
2. Place 2 blocks down with a 1 block gap between. 
3. Place vines on the inner side of one block, facing the other block. 
4. Wait for vine growth to trigger.

**Expected behavior**
Vines will not grow from block to block.

**Screenshots**
https://imgur.com/2z2Wt2L
https://paste.enginehub.org/_l8zzDWcS.report

**Comment by wizjany** [comment]
Issue in spigot, they're not throwing the spread event for intra-block growth, only inter-block.
