### ISSUE TITLE
Denying crop-growth does not prevent nether warts from growing

### ISSUE THREAD

**Issue by OreoKirby** [EngineHub/WorldGuard#1669]
**Versions**
WorldEdit version:
7.2.0-beta-05
WorldGuard version:
7.0.4+f7ff984
Platform version:
Paper-251 (1.16.3)

**Describe the bug**
Crops/Nether Wart are growing if crop-growth is disabled using flags or the world config.yml file.

**To Reproduce**
1. Create a region and deny crop-growth and/or disable globally in the world config.yml file.
2. Place stage 0 Wheat/Nether Wart on Farmland/Soul Sand. 
3. Wait for crop growth to trigger.

**Expected behavior**
Wheat/Nether Wart will not grow.

**Screenshots**
https://imgur.com/2z2Wt2L
https://paste.enginehub.org/_l8zzDWcS.report

**Comment by wizjany** [comment]
Can't reproduce this with wheat, nether wart is fixed though.
