### ISSUE TITLE
Wither doesn't destroy blocks in WorldGuard regions

### ISSUE THREAD

**Issue by LaoTheLizard** [EngineHub/WorldGuard#1672]
Versions:
WorldEdit version: 7.2.0
WorldGuard version: 7.0.4
Platform version: Paper-288 (1.16.4)

Description:
Wither doesn't destroy obsidian blocks when he follow me in WorldGuard region where I'm not a member/owner. Even if I set all flags about wither to ON.
If I turn /op on (or delete region) - wither destroys blocks by witherheads and destroy obsidian blocks by its body. If I turn /op off - he doesn't destroy any blocks in region, but continues to destroy beyond.

To Reproduce:
1. make a region for another player
2. go in that region (you are not an operator, you're not a member/owner)
3. create wither somewhere nearby
4. damage him to 1/2 or less HP
5. target him to you while you're walking in this region

Expected behavior:
As you see below, I tuned all to make able to destroy all blocks in regions by wither. But I can't reach it. What should I do?

Screenshots:
I set my config.yml like that: https://prnt.sc/vphc62
I tuned global region like here: https://prnt.sc/vphb1t
And this is the region where I tested it after: https://prnt.sc/vphbe9
(player SteelNat is not me)
This is a scene (no obsidian, no other blocks is destroyed): https://prnt.sc/vphgb3
And this is a same scene, when that region was just deleted (obsidian damaged): https://prnt.sc/vphhho and https://prnt.sc/vphhvt

Additional context:
Why did you close my previous bug report?

**Comment by me4502** [comment]
Creating multiple of the same reports doesn't change anything? Reply to the original one.

**Comment by wizjany** [comment]
please don't spam our bug tracker, you can reply to the original

**Comment by LaoTheLizard** [comment]
> please don't spam our bug tracker, you can reply to the original

Ok, I see now. I wrote there right now.
