### ISSUE TITLE
WorldGuard::Event: c.s.w.b.l.EventAbstractionListener (InventoryMoveItemEvent) lag

### ISSUE THREAD

**Issue by hkkongou** [EngineHub/WorldGuard#1676]
**Versions**

WorldEdit version: 7.3.0-snapshot +5491 5ae691

WorldGuard version:7.0.4+f7ff984

Platform version:tuinity 576e2cc / paper 253 1.16.3

**Describe the bug**

**To Reproduce**

no procedure 

**Expected behavior**

WorldGuard::Event: c.s.w.b.l.EventAbstractionListener (InventoryMoveItemEvent) is shown in timings report and is the first priority laggest plugin 
**Screenshots**

![image](https://user-images.githubusercontent.com/61608872/100569710-cbb08e80-3309-11eb-88c6-3941a927c75f.png)

**Additional context**

https://timings.aikar.co/?id=9bd613c0ce6944bf9b748bd53d1e0283#plugins

**Comment by wizjany** [comment]
generally a sign of too many hoppers but this isn't a bug by any means. please use discord for general support/questions
