### ISSUE TITLE
Block / allow command flag not functioning

### ISSUE THREAD

**Issue by detoxv** [EngineHub/WorldGuard#1678]
**Versions**
WorldEdit version: 7.2.0

WorldGuard version: 7.0.4

Platform version: Paper spigot 1.16.3

**Describe the bug**
Using the blocked commands or allowed commands flag in the region it does not successfully block the command. It prompts in chat successfully "Hey you are now allowed to use that command here" but the command executes regardless. This goes for any plugin commands, it seems the commands have priority to execute / bypass world guards deny.

**To Reproduce**
1. Create a region
2. Apply the flag blocked-cmds or allowed-cmds
3. Ensure you are de-opped and of no permissions
4. Try execute /spawn, /home, or any other command that has been chosen to be blocked
5. It will announce you cannot do that in chat...
6. But the command will execute regardless.

**Expected behavior**
I expect the command not to run and for worldguard to successfully block the command just like all the other flags.

This is very frustrating as i am in need of this feature and it is currently not possible for me.

**Comment by wizjany** [comment]
generally means some other plugin is bypassing cancelled command events. if WG gives the deny message it's done on our end and it's up to other plugins to not fuck things up.
