### ISSUE TITLE
Command autocompletion does not work for non-admins

### ISSUE THREAD

**Issue by Silthus** [EngineHub/WorldGuard#1679]
**Versions**

WorldEdit version: 7.2.0
WorldGuard version: 7.0.4
Platform version: Bukkit-Official 7.2.0+a51fa43

**Describe the bug**
Command autocompletion does not work with non admin permissions. 
For example when players only have the `worldguard.region.addmember.own.*` permission and click on the action in the `/region info ...` dialog they do not get autocompletion for valid player names.
The autocompletion does not work either when giving `worldguard.region.addmember.*` permission.
It starts working when giving the `worldguard.region.*` permission.

**To Reproduce**

1. Give a player the `worldguard.region.addmember.*` permission
2. Try to execute the `region addmember` command and see if autocompletion works - it should not
3. Now give them the `worldguard.region.*` permission - autocompletion now works

**Expected behavior**

Autocompletion for commands should work for sub permissions without giving full access to all regions.

**Screenshots**

[wg report output](https://paste.enginehub.org/w43KkYm-u.report)
![error](https://user-images.githubusercontent.com/755327/101291904-6c241880-380c-11eb-90f0-c977ebf00700.png)

**Comment by wizjany** [comment]
"fixed" in dev builds, though this isn't really a bug as you may think.
