### ISSUE TITLE
/region /rg not shown as a command 

### ISSUE THREAD

**Issue by Anusshan** [EngineHub/WorldGuard#1681]
**Versions**

WorldEdit version:7.20

WorldGuard version:7.0.4

Platform version:1.16.4 spigot

**Describe the bug**

I tried to create a new region but there is no command with /rg  or /region.

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by me4502** [comment]
Use the discord for support
