### ISSUE TITLE
Armor-Stands

### ISSUE THREAD

**Issue by RicePerson** [EngineHub/WorldGuard#1682]
**Versions**

WorldEdit version:
7.2.0-beta-04
WorldGuard version:
7.0.4-beta1
Platform version:
Bukkit

**Describe the bug**
Players are able to harvest armor from armor-stands even with regions prohibiting it

**To Reproduce**

1. Attach Armor to an armor stand
2. Create region with flags for protection
3. Go into adventure mode
4. Grab a piece of armor from the stand

**Expected behavior**
It would prohibit you from grabbing the armor

**Screenshots**

![image](https://user-images.githubusercontent.com/75872275/101973626-0ca87d00-3bff-11eb-983e-e2c8080ed0b7.png)

**Additional context**

**Comment by wizjany** [comment]
that's the global region, you didn't even protect it, and your everything is outdated.
