### ISSUE TITLE
Protected regions are not protected from the growth of melons or pumpkins

### ISSUE THREAD

**Issue by stonar96** [EngineHub/WorldGuard#1683]
**Versions**

WorldEdit version: 7.2.0

WorldGuard version: 7.0.4

Platform version: git-Paper-323 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Describe the bug**

Protected regions are not protected from the growth of melons or pumpkins.

**To Reproduce**

1. Create a protected region (no further settings required).
2. Place melon or pumpkin stems on wet farmland next the region border outside of the region, such that the melons or pumpkins can grow into the region.
3. Wait until the melons or pumpkins grow.

**Expected behavior**

Similar to growing saplings (without bone meal), the melons and pumpkins should not grow into the region because the stem is not a member of the region.

**Screenshots**

![2020-12-14_06 26 50](https://user-images.githubusercontent.com/18699205/102045003-4bddf600-3dd8-11eb-98f7-58eb23d69589.png)

**Additional context**

None.

**Comment by wizjany** [comment]
Don't think spigot tells us the source of growth events.

**Comment by stonar96** [comment]
Probably true, I also thought that. However, I didn't check. Just wanted to note that this is a thing.

**Comment by wizjany** [comment]
yea not sure there's a correct solution aside from making your regions one-wider. unless something changes upstream nothing for us to do here.
