### ISSUE TITLE
Option to disable Respawn Anchor explosion block damage

### ISSUE THREAD

**Issue by jnxyp** [EngineHub/WorldGuard#1684]
In Minecraft 1.16, the Respawn Anchor was added to the game. When the changed anchor was used in overworld, it will explode and damange the blocks around it. I want to simply avoid this block damage. I've tried to set the `respawn-anchors` region flag to `deny` for the __global__ region, but it seems to be not doing anything. Therefore, I would like to request an option to disable the anchor explosion damage, just like for the TNT blocks.

Thanks!

**Comment by wizjany** [comment]
respawn anchors flag is working fine for everyone else, so don't really understand what you're getting at here. if this is a bug report you need to follow the proper template (and not delete it all).
