### ISSUE TITLE
Region flag USE

### ISSUE THREAD

**Issue by MrSmiley21** [EngineHub/WorldGuard#1685]
WorldEdit version: 7.2.0-dist

WorldGuard version: 7.0.4-dist

Platform version: yatopia-1.16.4-paperclip-b17

**Describe the bug**
If you set the flag - use: allow, then other players can still open doors, press buttons, use levers, plates, trapdoor, fence gate.
If you set the flag - use: deny, then even the creator of the region cannot use the above.

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by wizjany** [comment]
yes.

**Comment by MrSmiley21** [comment]
> yes.

So it should be or is it a bug?

**Comment by baailey** [comment]
it works as intended. if you dont want ppl to use doors etc when they're not added to the region, remove the flag.
