### ISSUE TITLE
Maybe this future... Problem with flag time-lock

### ISSUE THREAD

**Issue by maganiczny** [EngineHub/WorldGuard#1688]
**Versions**
WorldEdit version:
Bukkit-Official(7.2.0+a51fa43)

WorldGuard version:
Bukkit-Official(7.0.4+f7ff984)

Platform version:
CraftBukkit git-spigot-628435a-768d7fc (MC: 1.16.4) (API: 1.16.4-R0.1-SNAPSHOT)(latest)

At the first i can sorry for language, but i have a problem and I want to present him.
**Describe the bug**
I have on the server many plugins, but two plugs are affected by this issue: multiserve (with "portals") and wordedit+guard (i'm sure, this two plugin i "install" as first). So, when i set flag time-lock on one from many worlds connected with portals, on the rest worlds strange things are happening. You know this problem from other issues: outside region who have set flag "lock-time" with number value, inherits flag but dont know what is time. From five worlds only two have set this flag, other have problem with time. Somtime is ok, somtime time is the same like one from this two worlds. I don't looking on code but i have idea: add one more flag who say ignore or not time-lock, a.e bool "true" or false", then it will give more precision in configuration. I thing current "flagset" can't get precision. When "ingonore-lock-time" set true (or invert: enable-lock-time set false) then flag is ignored. 

In my opinion or multiserve have problem, dont reset flags when change world in any way or world* have problem with set flags or reseting him.

**To Reproduce**
1. Create many worlds, minimum 3 (reproduce is for 3 worlds).
2. Set at first world flag lock-time with a any number value.
3. Create on first world portal to the second world and do the same on step 2.
4. Repeat second step for second world and third step to connect second world to third world.
5. On the third world set flag pvp deny and create portal to second world.
6. Teleport to first world (on us "spawn") typing "mv tp spawn"
7. walk on teleport in first, then second to third world and back to second.
8. observe the time and position of the sun.

**Expected behavior**
Time in some one world is different than expected.

**Screenshots**
In this place more suitable are is gif or screen record. But if first world (i think) are set flag lock-time, second world stuck time not necessarily in the same place.

EDIT:
This screenshot and listing maybe is the best:
![Screenshot_249](https://user-images.githubusercontent.com/62204514/102724236-8121a100-430e-11eb-9337-5ba175830303.png)
You can seen output from commands who set day and two trying query of time and the "sun" on the background.

**Comment by wizjany** [comment]
not sure what the issue is - the time returned by the command is different from the time the player sees? that's absolutely correct, that's the point of the flag.

**Comment by maganiczny** [comment]
Yes but on this world when do screenshot flag is "unset value"

**Comment by wizjany** [comment]
yea I don't follow. the description is an incomprehensible wall of text and the description if full of portals and other flags and plugins and I haven no clue if they're relevant. in fact as far as I can tell the worlds are irrelevant unless some other plugin is setting times per-world or something, since from WG's perspective going between worlds is basically the same as entering and exiting regions in the same world.

**Comment by maganiczny** [comment]
Thank You, Your answer resolved my doubts about the plugin's operation. Best regarsds

**Comment by maganiczny** [comment]
Hello everyone. If You have this same problem, resolve is very easy. You can set the flag with +0 or -0 value, like this: /rg flag -w "{world}" __global__ time-lock +0
...and this work very good. I reboot server with only plugins from world* and multiverse "family". I don't know what is this but this solutnion work for me.
