### ISSUE TITLE
Ravagers still trample crops while disable-creature-trampling: true

### ISSUE THREAD

**Issue by mrcoffee1026** [EngineHub/WorldGuard#1691]
**Versions**
[17:26:54 INFO]: WorldGuard 7.0.4
[17:26:54 INFO]: http://www.enginehub.org
[17:26:54 INFO]: ----------- Platforms -----------
[17:26:54 INFO]: * Bukkit-Official (7.0.4+f7ff984)
[17:27:29 INFO]: WorldEdit version 7.2.0
[17:27:29 INFO]: https://github.com/EngineHub/WorldEdit/
 This server is running Paper version git-Paper-339 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Describe the bug**
Ravagers are able to trample crops while the option disable-creature-trampling is set to true.
Set

**To Reproduce**
1. Set disable-creature-trampling to true for the world.
2. Spawn a Ravanger near or on some planted crops, watch them be destroyed.
**Expected behavior**

**Screenshots**
Crops should be protected from mob damage by this setting.
**Additional context**
All other mobs seem properly restricted by this setting, ravagers just get a "free pass" somehow.

**Comment by wizjany** [comment]
ravagers basically work entirely differently, they aren't trampling the soil like other mobs. this is essentially intended behavior, and ravagers have their own flag for breaking crops/leaves/etc.
