### ISSUE TITLE
Exit: DENY should allow a member to exit a region after becoming a member while inside the region.

### ISSUE THREAD

**Issue by 0RadicalLarry0** [EngineHub/WorldGuard#1692]
**Versions**

WorldGuard version: Bukkit-Official (7.0.4+f7ff984)

Platform version: 1.16.4 Paper/Spigot

**Describe the bug**
Can't exit region after becoming a member of the region whilst inside said region.

**To Reproduce**

1. Set the `exit` flag to `DENY` on a region.
2. As a nonmember, enter the region.
3. Make yourself a member of the region.
4. Try to walk out of the region. (AS A NON-OP)

**Expected behavior**

You should be able to walk out of the region as you are now a member.

**Screenshots**

(Exit was set to deny previously, I have removed the flag from the region)
![2020-12-23_23 23 05](https://user-images.githubusercontent.com/54878890/103063193-2db18c00-4576-11eb-9a2d-c5e69e2dcd97.png)
(Exit was set to deny previously, I have removed the flag from the region)
![2020-12-23_23 23 10](https://user-images.githubusercontent.com/54878890/103063203-31dda980-4576-11eb-824d-391305f504a7.png)
(Exit was set to deny previously, I have removed the flag from the region)

**Additional context**

I stumbled across this problem when trying to set a player as a member 3 seconds after they enter a region, only to then remove them as a member after they exit.

**Comment by wizjany** [comment]
`/wg flushstates [player]`
