### ISSUE TITLE
EXP-Drops flag doesnt work

### ISSUE THREAD

**Issue by JHarris12345** [EngineHub/WorldGuard#1693]
**Versions**

WorldEdit version: 7.2.0+a51fa43

WorldGuard version: 7.0.4+f7ff984

Platform version: 1.16.4

**Describe the bug**

The EXP-DROPS flag is set to deny yet players still lose EXP when they die

**To Reproduce**

1. ... Set the expdrop flag to deny
2. ... Die

**Expected behavior**

It shouldnt lose exp

**Screenshots**

**Additional context**

**Comment by wizjany** [comment]
the flag is about dropping xp, not keeping xp. behavior is as intended.
