### ISSUE TITLE
/rg redefine

### ISSUE THREAD

**Issue by Uranusak** [EngineHub/WorldGuard#1694]
WorldEdit version: 7.3.0-SNAPSHOT+5491
WorldGuard version: 7.0.5-SNAPSHOT+2085
Platform version: PaperMC-344

I use permission:
worldguard.region.redefine.own.*

The /rg redefine command does not check if there are foreign regions in the selection. I assume this is a bug and the "/ rg redefine" command should check the selection as a '/rg claim or /rg define" command. The command can be used to rob players.

**Comment by wizjany** [comment]
define and redefine aren't held to the same limits as claim. there is no "reclaim" command and there is unlikely to be. the claim system is intentionally left rudimentary.
