### ISSUE TITLE
WorldGuard For Spongeforge / Forge ?

### ISSUE THREAD

**Issue by MrTeaRexx** [EngineHub/WorldGuard#1697]
Hello :) I was wondering if it would be possible to get WorldGuard for Spongeforge, or a mod version for it on Forge. I only trust WorldGuard with my development of my projects and with both worldedit being on forge and sponge feels weird WorldGuard isn't there. when I used Cauldron I used both Bukkit Versions with mods but these days its very limiting since the hybrids are gone

**Comment by wizjany** [comment]
not the place for questions. no.
