### ISSUE TITLE
teleport-on-void-falling makes one fall forever

### ISSUE THREAD

**Issue by TheoRetisch1** [EngineHub/WorldGuard#1701]
**Versions**
WorldGuard version: WorldGuard version 7.0.5-SNAPSHOT+2088-282425f
Platform version: git-Paper-367 1.16.4
Worldedit version: WorldEdit version 7.3.0-SNAPSHOT+5562-7a268b0

**Describe the bug**
`Teleport-on-void-falling: true` makes one fall forever. When a player jumps into the void of the end, he or she neither gets damage nor is he or she teleported. One will just fall forever. The problem also occurs with an older version of Worldguard (7.0.4). If you disable Worldguard and jump into the void, you get damage and die.

**To Reproduce**
1. Set the following config options in the player-damage section, as listed below:
```
    disable-void-damage: false
    teleport-on-void-falling: true
    reset-fall-on-void-teleport: false
```
2. Enter the end.
3. Jump into the void.

**Expected behavior**
The player's fall should be stopped by damage or teleport to a safe location.

**Additional context**
[report.txt](https://github.com/EngineHub/WorldGuard/files/5761632/report.txt)
Multiverse-Core version 4.2.3-SNAPSHOT-b818

**Comment by wizjany** [comment]
didn't we just go over this? I suggest you just not use this feature if it doesn't do what you want it to do.

**Comment by TheoRetisch1** [comment]
Uuuhm, well I was hoping that the bug could be fixed that you fall down for ages in the void. The endless falling in the void is not an intended feature, is it?

**Comment by kikelkik** [comment]
But why doesn't that glass appear anymore when WorldGuard is disabled?

**Comment by wizjany** [comment]
it's never been meant to make glass appear? Maybe you're thinking of WorldEdit's /up?

**Comment by TheoRetisch1** [comment]
I specifically created this bugreport without mentioning a word about glass, so we can focus on the bug and the ticket won't be closed again like the last one.

**Comment by kikelkik** [comment]
It really kinda fell like /up, but the glass is always being placed at y=0.
That safe teleportation might cause that block to spawn if there's no other block ahead of the player?
Maybe it's something in WorldEdit, starting at 
https://github.com/EngineHub/WorldGuard/blob/master/worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/listener/WorldGuardEntityListener.java#L173

**Comment by kikelkik** [comment]
any idea?
