### ISSUE TITLE
MAYOR BUG

### ISSUE THREAD

**Issue by MrmaximoExcssum** [EngineHub/WorldGuard#1702]
This plugin is very bad optimized and VERY resource demanding on my server.
Would ble glad if you could try making this better

**Comment by me4502** [comment]
WorldGuard is not resource demanding. It's likely actually something else.

But without any information there's literally nothing we can do

**Comment by TomyLobo** [comment]
Maybe he's talking about this? https://disney.fandom.com/wiki/Mayor_Bugg

Jokes aside, we need you to eliminate all your other plugins one by one until the issue disappears.
Only if the issue persists with only WorldGuard (and its dependencies) installed, but does not exist without WorldGuard, can you conclude that WorldGuard has a bug.
That's at least true for resource consumption issues like this.
