### ISSUE TITLE
PVP off

### ISSUE THREAD

**Issue by zackito11** [EngineHub/WorldGuard#1706]
**WorldGuard 7.0.4 (MC 1.16+)**Paper

**Describe the bug**
Whenever i install worldguard it turns off the pvp of all worlds and regions without doing anything, i tried to get help in discord server but i got disrespected and banned for asking for help without breaking any rules ¯\_(ツ)_/¯. They said to me that i should try deleting the other plugins, but even creating a server with only WorldGuard makes global pvp off.

**To Reproduce**
Install WorldGuard

**Comment by wizjany** [comment]
as mentioned multiple times, WG blocks nothing by default. you have either done something, contrary to your description, or it is not caused by worldguard.

**Comment by zackito11** [comment]
dude i just want help
