### ISSUE TITLE
Unexpected error after placing a bunch of portals. 

### ISSUE THREAD

**Issue by UntouchedOdin0** [EngineHub/WorldGuard#1707]
**Versions**

WorldEdit version:
7.2.1
Bukkit-Official(7.2.1+299386a)

WorldGuard version:
Bukkit-Official(7.04+f7ff984)

Platform version:
1.16.4

**Describe the bug**

For some reason if I spawn a ton of NETHER_PORTAL's it causes WorldGuard to get angry. 

**To Reproduce**

1. ... Make a quick plugin what sets NETHER_PORTAL's via a for loop from WorldEdit's selection
2. ... Generate the nether portal and it should cause a error 

**Expected behavior**

There should be no bug at all

**Screenshots**

https://i.imgur.com/uJyEQDI.png
https://i.imgur.com/dq4j4FN.png

**Additional context**

**Comment by wizjany** [comment]
Unfortunately getting angry is not a bug. Thanks for following the template but unfortunately there's no bug reported here. Feel free to edit your message if you find one.
