### ISSUE TITLE
Allowed-cmds not working with global regions

### ISSUE THREAD

**Issue by SoRadGaming** [EngineHub/WorldGuard#1710]
WorldEdit version:
7.2.0
WorldGuard version:
7.0.4
Platform version:
Paper 1.16.4-395

**Describe the bug**
The flags for allowed-cmds doesn't work in regions created with /rg define -g name

**To Reproduce**
1. create global region with -g
2. setup flags for allowed-cmds and deny-message

**Expected behavior**
To block non-wihtelisted commands

This works on cuboid world guard regions, that is not an option in this case I need global per world.

**Comment by wizjany** [comment]
that's not what global regions are. you should probably read the docs.

**Comment by SoRadGaming** [comment]
is there anyway to set undefined/infinite value for a world guard region, how else would I have different per world flags using this plugin with multiverse?

**Comment by me4502** [comment]
You should look at the default `__global__` region that exists in each world

**Comment by SoRadGaming** [comment]
Oh that is per world, ok thanks, the only issue would be using the placeholder API %world_guard_region% would be useless, been using it for the conditional events plugin
