### ISSUE TITLE
Mysql questions/error

### ISSUE THREAD

**Issue by heraqu** [EngineHub/WorldGuard#1711]
Hi, how can I switch off SSL connection? I try connect worldguard to mysql
![image](https://user-images.githubusercontent.com/46068203/104590793-15f88f80-566c-11eb-9869-ef3f8f30d0cb.png)

![image](https://user-images.githubusercontent.com/46068203/104590826-26a90580-566c-11eb-97c5-7afb779859dc.png)
![image](https://user-images.githubusercontent.com/46068203/104591208-a59e3e00-566c-11eb-98e5-07d211f35c74.png)

worldedit-bukkit-7.2.1-dist.jar
WorldGuard version:

worldguard-bukkit-7.0.4.jar

**Comment by wizjany** [comment]
1) this isn't a bug. questions belong on discord
2) this is handled by your jdbc connection string anyway
3) dont use sql https://worldguard.enginehub.org/en/latest/regions/storage/
