### ISSUE TITLE
Wither does no Damage when "Ghast Fireball" is off.

### ISSUE THREAD

**Issue by TreemanKing** [EngineHub/WorldGuard#1715]
**Versions**
WorldEdit version:
7.2.0
WorldGuard version:
7,0.4+f7ff984
Platform version:
Tuinity 1.16.4 (8056d13)

**Describe the bug**
When disabling Ghast Fireballs on the flag, it will disable **Wither** damage to players.
**To Reproduce**
1. Disable Ghast Fireballs
2. Spawn Wither
3. Wither does no Damage to players.

**Expected behavior**
Withers to do damage

**Comment by wizjany** [comment]
do you mean the wither skulls? if so then yes that's intended.
