### ISSUE TITLE
WorldGuard Region offset of +0.5 blocks in the West and North direction

### ISSUE THREAD

**Issue by SuperFurias** [EngineHub/WorldGuard#1718]
**Versions**

WorldEdit version:
WorldGuard 7.0.4
http://www.enginehub.org
----------- Platforms -----------
* Bukkit-Official (7.0.4+f7ff984)
WorldGuard version:
(FAWE) FastAsyncWorldEdit-560 created by Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault
(FAWE) FAWE version:\n - Date Jan 16, 2021 12:00:00 AM\n - Commit f976a01d\n - Build 560\n - Platform Bukkit
(FAWE) Wiki: https://wiki.intellectualsites.com/FastAsyncWorldEdit/index
(FAWE) ------------------ Platforms ------------------\n* Bukkit-Official(1.16-560;6895fe3)\n
(FAWE) ---------------- Capabilities ----------------\nGAME_HOOKS: Bukkit-Official\nCONFIGURATION: Bukkit-Official\nUSER_COMMANDS: Bukkit-Official\nPERMISSIONS: Bukkit-Official\nWORLDEDIT_CUI: Bukkit-Official\nWORLD_EDITING: Bukkit-Official\n
Platform version:
This server is running Yatopia version git-Yatopia-17 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Yatopia-10 (MC: 1.16.5)

**Describe the bug**

When I create a region, the region creates it for me where I have done previously // pos1 and // pos2, but when I go to see the actual region which area it covers, I notice that the region is shifted by
+0.5 blocks to West and North and -0.5 blocks to South and East
This is very annoying in my PVP region, as some players can hit mid-block before entering the pvp region 
**To Reproduce**

1. ... //pos1 x,y,z
2. ... //pos2 x,y,z
3. ... /rg create TEST
4. ... Check the exact position of the region block by block

**Expected behavior**

checking the region margins block by block, even if using / rg info test (or in the regions.yml file) gives you the correct coordinates, the region is offset by 0.5 blocks in West and North 
**Screenshots**

![image](https://user-images.githubusercontent.com/34806112/106513200-eacac880-64d2-11eb-8548-f679b2a5b596.png)
![image](https://user-images.githubusercontent.com/34806112/106513210-f0281300-64d2-11eb-9aaa-d5ff67160e6f.png)

https://paste.enginehub.org/dHDW5x2Q3.report
**Additional context**

In the screenshots I only show the offset of the North direction since the other one did not have time and making a new region annoyed me

**Comment by wizjany** [comment]
1) unsupported environment
2) we use whatever coordinates the server tells us your player is at, we're not doing hitbox checks or something to see if you're overlapping more than one block.
