### ISSUE TITLE
1.16.5 lava flow

### ISSUE THREAD

**Issue by 0b-wan** [EngineHub/WorldGuard#1722]
WorldEdit version: WorldEdit 7.2.1 (1.13.2 - 1.16.4) and WorldEdit 7.2.2 (1.13.2 - 1.16.5)

WorldGuard version: WorldGuard 7.0.4 (MC 1.16+)

Platform version: Paper #463 1.16.5

Tried adding the flag lava-flow DENY to regions and it just doesn't do anything. Everything else works fine as intended just not this flag. I tried it on my SMP server and nothing, also tried it on a fresh server and same behavior.

**Comment by me4502** [comment]
You've likely disabled the high frequency flags option in the config
