### ISSUE TITLE
WorldGuard mob-spawning flag not cancelling CreatureSpawnEvent (Not working)

### ISSUE THREAD

**Issue by TechnicallyCoded** [EngineHub/WorldGuard#1725]
**Versions**
WorldEdit version: FAWE-581
WorldGuard version: 7.0.4
Platform version: Paper 1.16.5 (465)

**Describe the bug**
Using the mob-spawning deny flag doesn't block mob spawning.
Using deny-spawn flag doesn't block mob spawning either

**To Reproduce**
Set the mob-spawning flag to DENY on \_\_global\_\_
Make sure no other regions exist
/kill all mobs of one type (in my example I tried cows, sheep, rabbits, etc..)
wait a little bit
re-run previous kill command - new mobs have been killed which should be impossible (these are natural spawns, I even teleported to them to verify that other players were not somehow creating mobs)

**Expected behavior**
No mobs should be able to spawn when setting these flags

**Screenshots**
N/A

**Additional context**
Hypothesis: Some other plugins that we have are possibly conflicting with wg? Here are some of the plugins that I am uncertain about regarding worldguard mob spawning compatibility:  FAWE, Insights, Lands, WorldGuardExtraFlags, Multiverse-Core (multiverse has spawning settings, but I tried force disabling mobs there too and no change..)

**Comment by wizjany** [comment]
1) fawe isn't supported, it's known to break various parts of WE/WG (though I haven't heard of it breaking mob spawning)
2) if other plugins are breaking things there's not much we can do about it
3) can't repro under proper environment anyway
