### ISSUE TITLE
InventoryMoveItemEvent lag in the nether

### ISSUE THREAD

**Issue by itsBeaco** [EngineHub/WorldGuard#1730]
**Versions**

WorldEdit version: worldedit-bukkit-7.2.2-dist.jar

WorldGuard version: worldguard-bukkit-7.0.5-SNAPSHOT-dist.jar

Platform version: PurPur 1.16.5

**Describe the bug**
 Hey! The issue I'm having is I seem to be getting a bunch of lag in the nether, I have pre-generated the map 3 times with 3 separate plugins. I have ran a timings report (provided below) and I'm getting lag from World Guard (as far as I can see, could be wrong), specifically "WorldGuard::Event: c.s.w.b.l.EventAbstractionListener (InventoryMoveItemEvent)". The only region I have in the nether is a 200x200 area that I use as a shopping district and I only stop some nether mobs from spawning, deny pvp and deny tnt.

**To Reproduce**

1. ...
2. ...
Sorry I'm not sure, please let me know if you need any details about this.

**Expected behavior**

**Screenshots**
 Here is a timings report for your convenience: https://timings.pl3x.net/?id=70924ac76916456ba707d6727666d005

**Additional context**

**Comment by itsBeaco** [comment]
The only region flags I have in the nether:

regions:
    hub:
        min: {x: -100, y: 0, z: -100}
        max: {x: 100, y: 255, z: 100}
        members: {}
        flags:
            tnt: deny
            pvp: deny
            deny-spawn: ['minecraft:blaze', 'minecraft:piglin', 'minecraft:zombified_piglin',
                'minecraft:enderman', 'minecraft:magma_cube', 'minecraft:wither_skeleton',
                'minecraft:ghast', 'minecraft:hoglin']
        owners: {}
        type: cuboid
        priority: 0

**Comment by wizjany** [comment]
generally indicates too many hoppers. the timings report seems to show around 120/tick. there's an option to ignore hoppers.
