### ISSUE TITLE
Players keep time-lock after leaving the region

### ISSUE THREAD

**Issue by DMan1629** [EngineHub/WorldGuard#1733]
**Versions**

WorldEdit version: FastAsyncWorldEdit-560

WorldGuard version: WorldGuard 7.0.4

Platform version: Paper 1.16.5

**Describe the bug**

Sometimes, when a player leaves an area with a "time-lock" flag, their time stays the same as the time-locked area and doesn't reset until they relog.

**To Reproduce**

1. Make a region and add the "time-lock" flag.
2. Enter the region and disconnect while still in it,
3. Log back in and leave the area - regular or TP, doesn't matter.
4. Time appears to stay locked even when outside the region.
5. Relog to remove the time-lock.

**Expected behavior**

The time-lock should be removed from the player when they leave the region with the time-lock - not matter how they leave it,

**Screenshots**

Will attach a video later if necessary.

**Additional context**

The problem occurs no matter how the player leaves the area - by foot, flying, teleporting.
The problem also seems to ALWAYS happen when their login place is a region with the "time-lock" flag.

**Comment by wizjany** [comment]
as with the last few times this has been reported (use the search...), can't repro. also fawe isn't supported tho no clue if they could manage to break this too.
