### ISSUE TITLE
Armor delete after drop

### ISSUE THREAD

**Issue by Prototest34** [EngineHub/WorldGuard#1735]
**Versions**

WorldEdit version: Bukkit-Official(7.2.0+a51fa43)

WorldGuard version: Bukkit-Official (7.0.4+f7ff984)

Platform version: spigot 1.16.5

**Describe the bug**

When your inventory is full and you drop your armor directly in an area where dropping is prohibited, your armor is deleted

**To Reproduce**

1. Equip armor
2. Fill your inventory
3. Go to an area where dropping is prohibited
4. Open your inventory
5. Put your mouse on an armor
6. Press your drop key 

**Expected behavior**

The armor should go straight back to its armor slot

**Screenshots**

https://paste.enginehub.org/-rBqrUzjV.report (test region)

**Additional context**

**Comment by wizjany** [comment]
we just cancel the drop event, the server is responsible for restoring the state of your items. nothing WG can do here.

edit 4 years later: https://github.com/PaperMC/Paper/pull/12475
