### ISSUE TITLE
knockback through regions with entry deny flag

### ISSUE THREAD

**Issue by AggerTV** [EngineHub/WorldGuard#1744]
**Versions**

WorldEdit version: 
`26.03 11:17:47 [Server] INFO FastAsyncWorldEdit version 1.16-616;99ea64f
26.03 11:17:47 [Server] INFO Blazingly fast world manipulation for builders, large networks and developers.
26.03 11:17:47 [Server] INFO Website: https://www.spigotmc.org/resources/13932/
26.03 11:17:47 [Server] INFO Authors: Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault`

WorldGuard version:
`26.03 11:15:25 [Server] INFO WorldGuard 7.0.4
26.03 11:15:25 [Server] INFO http://www.enginehub.org
26.03 11:15:25 [Server] INFO ----------- Platforms -----------
26.03 11:15:25 [Server] INFO * Bukkit-Official (7.0.4+f7ff984)`

Platform version:
`26.03 11:18:21 [Server] INFO This server is running Tuinity version git-Tuinity-"9ac33d1" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
26.03 11:18:21 [Server] INFO You are 13 version(s) behind
26.03 11:18:21 [Server] INFO Previous version: git-Tuinity-"5b6d8be" (MC: 1.16.5)`

**Describe the bug**

https://gyazo.com/ccecf4efc283601a84f9f20d4955f4bc
in the picture, you can see a room with a 1 block long diamond block boarder, this represents a region that have the flag "entry deny" set to true.
Under normal conditions, players that are not added to the region, cannot enter, but if they are hit with a object enchanted with knockback, they can easily be pushed through the region.

**To Reproduce**

1. make a 1 block long region with the flag "entry deny" set to true
2. have a player that shouldn't have acces to pass through the region stand in front of the region.
3. Hit that player with an object enchanted with knockback
4. the player will pass through the region even though they are not supossed to

**Expected behavior**

1. make a 1 block long region with the flag "entry deny" set to true
2. have a player that shouldn't have acces to pass through the region stand in front of the region.
3. Hit that player with an object enchanted with knockback
4. the player will not pass through the region

**Screenshots**

https://paste.enginehub.org/D0Pbbgm1V.report

**Additional context**

this is also an issue when using worldedit, so please don't blame it on fawe and disregard the issue based on that.

**Comment by wizjany** [comment]
nothing we can do here, we get exactly what bukkit gives us.
