### ISSUE TITLE
Block-trampling flag not working with crops

### ISSUE THREAD

**Issue by Bloodlex** [EngineHub/WorldGuard#1746]
**Versions**

WorldEdit version:
7.2.4

WorldGuard version:
7.0.4

Platform version:
This server is running Paper version git-Paper-550 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Describe the bug**
**Block trampling flag not working on wheat crops (probably all others too).**

**To Reproduce**

1. Define a cuboid with block-trampling set to DENY
2. Jump on crops - they get destroyed

**Expected behavior**
Crops should not have been destroyed.

**Additional context**
It works when turning globally of in configuration file, but not on specific cuboids.

Config file:
[https://pastebin.com/b65hH6VW](https://pastebin.com/b65hH6VW)

**Comment by wizjany** [comment]
more likely you have bypass perms or something.
