### ISSUE TITLE
Endermen spawn when denied

### ISSUE THREAD

**Issue by Bloodlex** [EngineHub/WorldGuard#1749]
**Versions**

WorldEdit version:
7.2.4

WorldGuard version:
7.0.4

Platform version:
Paper version git-Paper-581 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Describe the bug**
Endermen can spawn, although denied in deny-spawn flag

**To Reproduce**

1. Create a region
2. Deny spawn of endermen in deny-spawn flag
3. Endermen still spawn

**Expected behavior**
Endermen should not spawn when listed in deny-spawn or when mob-spawning is deny.

**Comment by wizjany** [comment]
are you sure they're not just teleporting in? can you `/summon enderman` in the region?

**Comment by Bloodlex** [comment]
> are you sure they're not just teleporting in? can you `/summon enderman` in the region?

I can't summon, spawnmob from Essentials or create them from the spawning egg. So it's possible they just teleport in there, right?

**Comment by wizjany** [comment]
likely to be the case - alternative is some bad plugin is spawning them by bypassing bukkit api so plugins like WG can't block it, but that's also not a WG issue. the fact that normal means like summon, eggs, etc are nonfunctional absolve WG here.
