### ISSUE TITLE
entity-item-frame-destroy deny does not prevent break or place of item frame in __global__ or world 

### ISSUE THREAD

**Issue by hawkfalcon** [EngineHub/WorldGuard#1753]
**Versions**
WorldEdit version:
v7.2.2+fc3c499
WorldGuard version:
v7.0.4+f7ff984
Platform version:
git-Paper-564 (MC: 1.16.5)

**Describe the bug**
If I set the flag entity-item-frame-destroy deny in a cuboid region, it prevents it from being broken and placed. If I set it either in world file or in __global__, it doesn't.

**To Reproduce**
1. set flag entity-item-frame-destroy deny in __global__
2. Break a item frame, then place it

**Expected behavior**
entity-item-frame-destroy deny should prevent breaking and placing for global regions

**Comment by wizjany** [comment]
To be clear, that flag refers to *non-player* entities.
It has no effect on players breaking (and especially not placing) item frames. Likely in the first case the region was just...protected...as regions are, so frames couldn't be placed/broken.
