### ISSUE TITLE
New allow-spawn flag

### ISSUE THREAD

**Issue by baailey** [EngineHub/WorldGuard#1754]
**Is your feature request related to a problem? Please describe.**

Currently, if you deny-spawn a mob on the global region, there is no flag to override that setting. My current problem is that we have the wither denied globally but are trying to set up an arena where players can go to spawn the wither as much as they wish without causing damage to the rest of the player base. However, without a way to override the global deny-spawn, the wither cannot be spawned.
**Describe the solution you'd like**

My suggestion is the introduction of a new flag called `allow-spawn` that will have a higher priority than deny-spawn. This will allow specific mobs access to spawning in designated regions without impacting the rest of the server.
**Describe alternatives you've considered**

N/A
**Additional context**

N/A

**Comment by wizjany** [comment]
https://worldguard.enginehub.org/en/latest/regions/commands/#flag
