### ISSUE TITLE
Sky is shaking on time-lock flag

### ISSUE THREAD

**Issue by paj1s** [EngineHub/WorldGuard#1758]
Hi, i have a region with time-lock and i have night set there. But the sky is constantly "shaking" it just repeatedly going back again so my request is: Wouldn't it be fine if there was an option to set an interval to this to make it faster? This way it's really annoying to see the stars and moon moving there and back. Or do it differently, a bit like it is in the gamerules.

**Comment by wizjany** [comment]
We just use the bukkit api to set the time once, the server implementation is out of our control.
