### ISSUE TITLE
WorldGuard Messages

### ISSUE THREAD

**Issue by KolakZ** [EngineHub/WorldGuard#1761]
It would be really cool to see a messages.properties file added where you can customize WorldGuard messages!

**Comment by stonar96** [comment]
You can change the deny messages and some other messages via region flags. See for example: `deny-message`, `entry-deny-message`, `exit-deny-message`, `greeting`, `farewell`, `teleport-message`.

For build permissions there is a `deny-message` setting in the config.

**Comment by wizjany** [comment]
duplicate
