### ISSUE TITLE
"invincible" flag starts to work only after leaving the region

### ISSUE THREAD

**Issue by oskarkk** [EngineHub/WorldGuard#1762]
**Versions**
WorldEdit version:
[10:00:24 INFO]: WorldEdit version 7.2.4
Bukkit-Official(7.2.4+5723-e3bfc64)

WorldGuard version:
[09:59:21 INFO]: WorldGuard 7.0.4
[09:59:21 INFO]: * Bukkit-Official (7.0.4+f7ff984)

Platform version:
This server is running Paper version git-Paper-543 (MC: 1.16.5)

**Describe the bug**
If you're setting the "invincible" flag for a region, those who were in that region when the flag was set are not invincible until they leave and that region and go back into it.

**To Reproduce**
1. `/rg flag __global__ invincible allow`
2. Try to take fall damage - you will take it like the flag wasn't set
3. Leave the server and join again - from now on you won't take damages

You can also try this with a regular region. Set the flag when you're in the region - you're vulnerable. Leave the region, go back in - you're invincible.

**Expected behavior**
All players in the region becoming invincible right after setting the flag.

**Comment by wizjany** [comment]
This is basically intentional. https://worldguard.enginehub.org/en/latest/commands/#regions
