### ISSUE TITLE
region time lock sometimes persist in the whole world.

### ISSUE THREAD

**Issue by paj1s** [EngineHub/WorldGuard#1771]
I have time lock set at night in my spawn region but when i tp to my island (skyblock world) the time lock persists, its still night and the sky is shaking. Sometimes it doesn't happen (e.g. after restart) but most of the time it does.

**Comment by wizjany** [comment]
missing template.
notably i need solid reproduction steps, people have reported this before but none of them can give that and i can't reproduce locally.
