### ISSUE TITLE
/region command available only if bypass subcommand are allowed

### ISSUE THREAD

**Issue by molor** [EngineHub/WorldGuard#1774]
**Versions**

WorldEdit version: 7.2.5
WorldGuard version: 7.0.5
Platform version: This server is running Paper version git-Paper-753 (MC: 1.16.5)

**Describe the bug**
/region or /rg command are not sent (via PlayerCommandSendEvent) to any player if they don't have `worldguard.region.toggle-bypass` permission. I can give it acces to /rg list, /rg claim, /rg flag, /rg remove, but WG don't care about this and /rg command in chat will always displayed as unavailable red (although, of course, it works if player pressed [Enter]).

**To Reproduce**
Remove operator status from player and any permissions, give it `worldguard.region.wand`, `worldguard.region.claim` and `worldguard.region.list.own`. Rejoin the server. Type /rg in chat and see fancy red color. Give it `worldguard.region.toggle-bypass`, rejoin and see gray color of new available command.

**Expected behavior**
Fancy gray colored command.

It would be nice if you also add autocompletion of the subcommands that the player has access to, but I think that it will not come to that soon..

**Comment by JOO200** [comment]
There is no WG version "7.0.5".

Update to the latest dev build, it's already fixed.

**Comment by molor** [comment]
> There is no WG version "7.0.5".

Sorry, I mean 7.0.5-SNAPSHOT. OK, I'll try an even newer version now
