### ISSUE TITLE
Issue with JDBC connection to MariaDB

### ISSUE THREAD

**Issue by trilliumhq** [EngineHub/WorldGuard#1782]
**Versions**

WorldEdit version: worldedit-bukkit-7.3.0-SNAPSHOT  Build #5790

WorldGuard version: worldguard-bukkit-7.0.5-SNAPSHOT Build #2116

Platform version:Paper 1.16.5-588
[latest.log](https://github.com/EngineHub/WorldGuard/files/6605103/latest.log)

**Describe the bug**

Worldguard having issue with connection to DB
Suspected cause: Related to papermc updating the mysql-connector-java to 8.0.23
https://github.com/PaperMC/Paper/commit/d560151ecdad2eabccda797883c9e699b0985104

Console Log;

[latest.log](https://github.com/EngineHub/WorldGuard/files/6605104/latest.log)

**Comment by wizjany** [comment]
unrelated and also unsupported. don't use sql.

**Comment by trilliumhq** [comment]
How is this unrelated? in logs I'm running only worldedit and worldguard. Worldguard config is using sql connection which is supported no?

**Comment by wizjany** [comment]
https://worldguard.enginehub.org/en/latest/regions/storage/
