### ISSUE TITLE
disable-soil-dehydration: true seems to not work

### ISSUE THREAD

**Issue by robjwa20** [EngineHub/WorldGuard#1785]
**Versions**

WorldEdit version:

WorldGuard version:
worldguard-bukkit-7.0.5-dist
Platform version:
Paper 1.16.5

**Describe the bug**
Is seems that the deny soil-dry flag and disable-soil-dehydration: true in config is not working.

**To Reproduce**

1. Deny soil drying in a region
2. Set disable-soil-dehydration: true in config
3. Soil still dehydrates.

**Expected behavior**
Not to dehydrate

**Comment by wizjany** [comment]
can't reproduce. https://i.imgur.com/ucT3zmn.png

**Comment by lthoerner** [comment]
I am having this issue as well, running Paper 1.20.1 and WG 7.0.9-beta1

**Comment by wizjany** [comment]
you may be experiencing #1879 instead. the flag/config mentioned here do what they were made to do at the time they were made.
