### ISSUE TITLE
Port to fabric?

### ISSUE THREAD

**Issue by Samisaprogrammer** [EngineHub/WorldGuard#1794]
**Is your feature request related to a problem? Please describe.**
I don't like that this isn't available for fabric which makes being super close to vanilla and having performance at the same time hard.

**Describe the solution you'd like**
I'd like if you ported this to fabric.

**Describe alternatives you've considered**
You could maybe port to Sponge?

**Additional context**
This is just a sugesstion, if you don't wanna do this just give me a reason (too little people use it, too hard to maintain, etc) and close this. Thank you!

**Comment by wizjany** [comment]
no.
