### ISSUE TITLE
I want WorldGuard to delete the world that DungeonsXL built

### ISSUE THREAD

**Issue by KENKTS** [EngineHub/WorldGuard#1796]
I want WorldGuard to delete worlds created by DungeonsXL because if WorldGuard doesn't delete worlds created by DungeonsXL, my server will not load. can you help me

https://www.img.in.th/images/a3084e2e0f9e2616c679eb2591fbd25e.png

**Comment by wizjany** [comment]
delete themem yourself. WG has no way of knowing if a worldedit is something set up temporarily for a plugin or meant to stick around long-term.
