### ISSUE TITLE
Change the default deny-message

### ISSUE THREAD

**Issue by Gumpah** [EngineHub/WorldGuard#1799]
**Is your feature request related to a problem? Please describe.**

Hello, I want to be able to change the default build deny message, which is "Hey! Sorry, but you can't break that block here.". I know that I can change it in regions, but I want to be able to change the default one, when the deny-message flag is not set.

**Describe the solution you'd like**

The solution for me is to remove the message from the code and put it in a separate file, a lang file or the config.yml file.

**Additional context**

The message that I'm talking about : 
![SrEFQkE](https://user-images.githubusercontent.com/22190868/126233021-e12b42da-b1d8-43e8-8dbf-493a70b51691.png)

Thank you for your help!

**Comment by Gumpah** [comment]
Hello, may I have some information on the invalid status?

**Comment by stonar96** [comment]
Use the global region, see docs.

**Comment by Gumpah** [comment]
Hello, thank you for your response!
That's what I've been doing, but I think having a config line in the config.yml file is a pretty basic feature. Having to set it for every world is not as intuitive and as simple as having a config line, it's also how all of the plugins are working, setting it for every global region of every world seems more like a workaround than the real solution to the problem. Just saying.
