### ISSUE TITLE
Blacklist command_block_minecart on-use=deny not working

### ISSUE THREAD

**Issue by Antal1609** [EngineHub/WorldGuard#1800]
**Versions**
WorldEdit version: FastAsyncWorldEdit-51
WorldGuard version: WorldGuard 7.0.6-SNAPSHOT+2137-7e817c3
Platform version: Paper version git-Paper-108 (MC: 1.17.1)

**Describe the bug**
Blacklist deny placing command_block_minecart does not work as intended.

**To Reproduce**
1. /minecraft:give @p minecraft:command_block_minecart
2. Set-up blacklist for your current world
```
[tnt_minecart,hopper_minecart,command_block_minecart]
on-use=deny
```
3. Placing tnt minecart is blocked, placing hopper minecart is blocked, placing command block minecart is **not** blocked.

**Expected behavior**
Command block minecart can not be placed if on-use is denied.

**Comment by wizjany** [comment]
https://i.imgur.com/VPd9HpD.png

**Comment by Antal1609** [comment]
I tried again and as of now it's working correctly... we didn't restart the server or reload anything. Thanks for verifying!
