### ISSUE TITLE
Glow Berries can be duplicated

### ISSUE THREAD

**Issue by baailey** [EngineHub/WorldGuard#1801]
**Versions**

WorldEdit version: Bukkit-Official(7.3.0-SNAPSHOT+5884-a383d91)

WorldGuard version: Bukkit-Official (7.0.6-SNAPSHOT+2138-682942b)

Platform version: git-Tuinity-"2310a94" (MC: 1.17.1)

**Describe the bug**

When there is a Glow Berry plant inside a region that has interact set to allow, any user who is not added to the region can right click the Glow Berries to 'harvest' them. This results in the 'Hey! Sorry, but you can't break that block here' message appearing, but the Glow Berries drop and then regenerate due the WorldGuard trying to block them 'breaking' them.
**To Reproduce**

1. Place or find Glow Berries like this https://i.imgur.com/8auAGlX.png
2. Create a region around them
3. Set interact to allow
4. Right click the Glow Berries

**Expected behavior**

Either block the user from 'breaking' the Glow Berries or allow them to harvest the plant
**Screenshots**

Here is a video: https://gfycat.com/DelectableCapitalDogwoodclubgall
**Additional context**

**Comment by baailey** [comment]
Trying to add Glow Berries to the blacklist to deny `on-interact` and `on-break` doesn't work either, it simply just bypasses the block.

**Comment by JOO200** [comment]
Unable to reproduce with:
> This server is running Paper version git-Paper-124 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 170382f)
You are running the latest version

Make sure to update your server software and/or to use a supported plattform (spigot or paper)
