### ISSUE TITLE
WorldGuard crashes on server start-up.

### ISSUE THREAD

**Issue by specsource** [EngineHub/WorldGuard#1802]
**Versions**
WorldEdit version:
Bukkit-Official (6.1.9;caf0ad9)

WorldGuard version:
6.2.2-SNAPSHOT;8eeab68

Platform version:
git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Describe the bug**
WorldGuard disables by itself on the server start-up.

**To Reproduce**
1. Start the server.

**Expected behavior**
It should work.

**Screenshots**
https://pastebin.com/raw/6gcQfHJV - on startup
https://pastebin.com/raw/aj6YUj7t - /wg report

**Comment by wizjany** [comment]
you broke your config(s).
