### ISSUE TITLE
/Heal command works without permission

### ISSUE THREAD

**Issue by JericNisperos** [EngineHub/WorldGuard#1806]
Hi, it seems here that the /heal command doesn't respect permissions. I already disabled the permission worldguard.heal  but still be able to use it. Is there a way to fix this?

Currently using the latest WorldGuard 7.0.6 beta 1 (MC 1.17+)
Server Version: 1.17.1 Airplane

**Comment by JOO200** [comment]
You didn't use the template, no logs attached and you're using a not supported server fork.

For further help join our discord
