### ISSUE TITLE
(1.17.1) Attempting to place a Powdered Snow Bucket in a protected region will turn grass blocks white.

### ISSUE THREAD

**Issue by NightFuryStrike** [EngineHub/WorldGuard#1810]
**Versions**

WorldEdit version: 7.2.6-beta-01+1415e6f

WorldGuard version: 7.0.6-beta1+0b66f3e

Platform version: Paper 1.17.1 (Build 157)

**Describe the bug**

Attempting to place a Powdered Snow Bucket in a protected zone on top of a grass block will turn the grass white.

**To Reproduce**

1. Create a protected WorldGuard region.
2. Attempt to place a Powdered Snow Bucket on some grass blocks within the protected region. It will correctly remove the snow, however the top of the grass block will remain white.

**Expected behavior**

The grass block should be reverted to the correct color.

**Screenshots**

![image](https://user-images.githubusercontent.com/56176412/128278707-d18e380e-2e8e-4819-bb38-b3a162c22a7a.png)

**Comment by wizjany** [comment]
the server is responsible for restoring state on cancelled events, not WG

**Comment by aurorasmiles** [comment]
See https://github.com/PaperMC/Paper/issues/6630
