### ISSUE TITLE
EntityDamageByEntityEvent doesn't get canceled when player gets hit in no pvp region

### ISSUE THREAD

**Issue by MagicCheese1** [EngineHub/WorldGuard#1811]
**Versions**

WorldEdit version: bukkit-7.2.6-beta-02

WorldGuard version : bukkit-7.0.6-beta1-dist

Platform version: This server is running Paper version git-Paper-123 (MC: 1.17.1)

**Describe the bug**

I listen to the EntityDamageByEntityEvent in my plugin. When I hit a player in a region with disabled pvp the EntityDamageByEntity event does not get canceled. The player doesn't get damaged.

**To Reproduce**

1. Listen to EntityDamageByEntity event and check if event#isCanceled is true.
2. Hit a player in a region with disabled pvp.

**Expected behavior**

The event should be canceled.

**Screenshots**

**Additional context**

**Comment by wizjany** [comment]
not sure what you think WG is doing but i assume this is a mis-use on your part of the bukkit api and not relevant to WG at all.
