### ISSUE TITLE
Anti-Creeper Block Damage Flag (Not in Config)

### ISSUE THREAD

**Issue by FlamerAwesome** [EngineHub/WorldGuard#1813]
**Is your feature request related to a problem? Please describe.**

I'm frustrated because the config creeper block damage will turn off creeper block damage everywhere instead of only in certain regions,. The block-break flag works, but I want players to be able to break blocks without having creeper explosions, this flag should be similar to the TNT flag. I would like to keep explosive health damage but not block damage.
**Describe the solution you'd like**

A solution that turns off creeper explosions in certain areas, just like the TNT flag or the ender dragon block damage flag.
**Describe alternatives you've considered**
block-break, but it just doesn't really work with what I want, block-break stops pistons from working, and players from breaking. (My main issue is the pistons)

Only alternative I considered was block-break, but as I already mentioned pistons and anything that moves or breaks blocks will not function properly which is an issue for my build and players cannot break blocks as well, using block-break will sacrifice many features I intend to use.
**Additional context**
I have a maze which uses pistons + other builds that require players to break blocks and fight against creepers, I don't want the creepers to leave block damage, but I still want them to have player health damage.

**Comment by FlamerAwesome** [comment]
Let me know if you need anything for context that suits your needs because I really want this feature as it jeopardizes many of my builds :)

**Comment by wizjany** [comment]
duplicate, also already possible via config toggle for explosion flags
