### ISSUE TITLE
Cannot invoke "Object.getClass()" because "o" is null

### ISSUE THREAD

**Issue by DaDiGui** [EngineHub/WorldGuard#1815]
**Versions**

WorldEdit version: bukkit-official (7.2.5+57d5ac9)

WorldGuard version: worldguard-bukkit-7.0.5-dist

Jar Server: arclight-forge-1.16.5-1.0.20-368b0cb

Forge version: forge-1.16.5-36.2.0

**Describe the bug**
It does not allow me to perform the //copy command (when the selection is already specified) with either vanilla or modded blocks.

**To Reproduce**
1. I select position 1 with the axe.
2. I select position 2 with the axe.
3. I execute the command //copy
4. A message appears in the chat saying: 
 - https://i.imgur.com/pjN6S0R.png

**Expected behavior**
Copy the selection of blocks to paste elsewhere.

**Screenshots**
https://paste.enginehub.org/GJOVxfNAa.report

**Additional context**

**Comment by wizjany** [comment]
unsupported platform
