### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by SavageSheepYT** [EngineHub/WorldGuard#1820]
**Versions**

WorldEdit version:
worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar
WorldGuard version:
worldguard-bukkit-7.0.5-dist.jar
Platform version:
Spigot 1.17.1

**Describe the bug**
Server will not start until you delete cache folder, problem solved by deleting it.

**To Reproduce**
1. install worldguard
2. attempt to boot server

**Expected behavior**
server starts without crashing or hanging

**Additional context**
server generates no crash log, just stops

**Comment by wizjany** [comment]
can't really do anything without logs. presumably not a WG error anyway.

**Comment by SavageSheepYT** [comment]
yeah, once you delete the folder it boots normally, but as soon as you restart it wont boot until the folder is gone
