### ISSUE TITLE
BUG - automatic mode change between worlds [Survival] [Creative]

### ISSUE THREAD

**Issue by vdl19** [EngineHub/WorldGuard#1823]
**Versions**

WorldEdit version:
worldedit-bukkit-7.2.6+4b2d1e7

WorldGuard version:
worldguard-bukkit-7.0.6-SNAPSHOT-dist 7.0.6-SNAPSHOT+2150-5a6b6eb
I also did some tests after with the previous versions below with the same results:
+ WorldGuard 7.0.6 beta 1 (MC 1.17+)
+ WorldGuard 7.0.5 (MC 1.16.5)

Platform version:
Paper 1.17.1 #233

**Describe the bug**
I have an official server in Paper 1.16.5 #788 with WorldEdit: "Bukkit-Official(7.2.6-beta-01+1415e6f)" and WorldGuard "Bukkit-Official (7.0.5+3827266)".
On this server I have from my spawn a portal that sends to a "Creative" world, on this server everything works. When you go through the portal you arrive in "creative" mode and when you come back you are in "survival" mode.

This server I put it on my test server in 1.17.1 so all the settings are the same I made the update of all the possible plugins on it. 
But the problem is that when I pass the portal to the "creative" world I arrive in "Survival" I can leave and return always the same.
I have just tried to change to "creative" the small zone of arrival of the world survival, that notes it well but when I go there I remain in survival!
So the problem is that the system to change and make the players in creative does not work anymore on my test server in 1.17.1 even with the version of Worldguard 7.0.5 that I do not know adapted but I tried just in case when I saw that nothing works.

**To Reproduce**
1. create a world and set it to "survival" mode by default
2. create a world and set it to "creative" mode by default
3. make a portal (I use multiverse-portal) to go and come back and just use it

**Expected behavior**
What happens on my 1.16.5 server is that players automatically switch to "creative" mode when they arrive in the "creation" world and that they switch back to "survival" mode when they return to the "Spawn" world, as has been done for a long time on my 1.16.5 server

**Screenshots**
![image](https://user-images.githubusercontent.com/80985545/131544911-3e448482-2ef6-4f97-8281-cd16e99476bd.png)

Thank you for your time

**Comment by wizjany** [comment]
worldguard does not "set [worlds] to 'creative/survival' mode by default" so I'm not sure how this is a worldguard issue.

**Comment by vdl19** [comment]
I didn't say that Worldguard create "Survival" or "Creative" worlds by default, it's me who set them with worldguard so that it's the setting that the player must have when arriving in these worlds. I have trouble using the words I'm French, it's a translation.
So it's me who set the worlds in "survival" or "creative" mode with WorldGuard and so the explanation I gave corresponds well to my problem that I don't have on my server 1.16.5 but impossible to make the players switch to creative when they arrive on this same world once the server is set to 1.17.1

![image](https://user-images.githubusercontent.com/80985545/131562087-4a0a0b87-7f33-406c-8ffa-223ef6a7a302.png)

**Comment by vdl19** [comment]
I have redone the application removing "by default" which was misunderstood when you read.

https://github.com/EngineHub/WorldGuard/issues/1824

**Comment by wizjany** [comment]
WG hasn't changed anything in the way game mode is handled between 1.16 and 1.17.

Teleporting into a world with the gamemode flag set to creative on the global region works fine, so if for some reason it's not changing for you that sounds like another plugin is overriding Worldguard.

**Comment by vdl19** [comment]
Well thanks I'll manage, but I don't know what else to do because I don't have any other plugin that manages protections like worldguard, I just deleted all my plugins except the 4 on the image below and I still have this problem, the "free creation" world is in "creative" but it doesn't change anything when you take the portal to go there you don't change survival in creative. Knowing that this same world configure exactly the same works in 1.16.5 and all plugins in place for months.

![image](https://user-images.githubusercontent.com/80985545/131637152-fa8e5be2-cac6-4484-aa88-8c8a2072dd83.png)

**Comment by vdl19** [comment]
Well I give my last tests anyway!
I deleted the test server.

> So from 0 I put :
"paper-1.17.1-236"

+ the following plugins:
EssentialsX-2.19.0-dev+257-4bee159
EssentialsXSpawn-2.19.0-dev+257-4bee159
Multiverse-Core-4.3.1-SNAPSHOT
Multiverse-Portals-4.2.2-SNAPSHOT
worldedit-bukkit-7.2.6
worldguard-bukkit-7.0.6-SNAPSHOT-dist

I put myself OP.

Create a new world : 
/mvcreate porto normal

Made the World Spawn:
/setspawn

Builds a portal on World :
/mvp create p1

> Select a zone then (World) :
//expand green
/region define capital
/rg list
/rg flag __global__ build allow (+ block-break & block-place)
/rg flag capital build allow (+ block-break & block-place)
> put on survival : __global__ + capital

> World Porto :
/mvtp porto
/mvsetspawn
/mvp create p2
/mvp modify dest p:p1
/mvp select p1
/mvp modify dest p:p2

> Select a zone then (port) :
//expand green
/region define city
/rg flag __global__ build allow (+ block-break & block-place)
/rg flag city build allow (+ block-break & block-place)
/rg list
> put in creative : __global__ + city

> Test of the portal while being OP = HS (the portal works but I stay in survival no change)

- Installation and configuration of LuckPerms + adding permissions for "Multiverse Portal" so that players can use them:
LuckPerms-Bukkit-5.3.64

- Restart of the server
- I "/deop vdl19" to be a normal player

- Restart of the server
- I "/deop vdl19" to be a normal player

RESULT: 
It doesn't work, I stay in "Survival" and never switch to "Creative"

>To finish the tests I remove :
EssentialsX-2.19.0-dev+257-4bee159
EssentialsXSpawn-2.19.0-dev+257-4bee159

> I deop myself:
Then I restart the server and I start again the test by taking the portal while being deop = HS there is no change of mode I remain in "survival"

![image](https://user-images.githubusercontent.com/80985545/131654927-c93b29e9-543f-4f55-b66a-33b692690d5c.png)

![image](https://user-images.githubusercontent.com/80985545/131655044-22141bf4-b90e-4204-b612-81925714e6a1.png)

> I can't test anything anymore, since I can't remove any plugin now. 
So there is a problem, I don't know if it's your plugin but the problem is either on PAPER or on one of the 5 remaining plugins at the end of the test:

![image](https://user-images.githubusercontent.com/80985545/131655541-195e48ca-6a8c-4f94-befb-5bf4ad7c544b.png)
![image](https://user-images.githubusercontent.com/80985545/131655590-870fec7e-0df6-44b4-9890-5f2998f5b4e7.png)

**Comment by wizjany** [comment]
I would note that multiverse very specifically has settings that force player gamemode per world so your "minimal reproduction" is not at all minimal.

**Comment by vdl19** [comment]
Ok it's "Multiverse-Core-4.3.1-SNAPSHOT" involved, I removed the plugin and using a nether portal it works once put back it doesn't work anymore. 
Thank you good continuation

**Comment by vdl19** [comment]
I will specify for information that it is Multiverse-Core with Paper 1.17.1, because I have just tested by putting Multiverse-Core-4.2.2 which is on my server 1.16.5 and which functions very well with WorldGuard thus on the server 1.17.1, it functions but Worldguard cannot make the change of mode to the players.
Thanks

**Comment by vdl19** [comment]
I was able to solve the problem with the order: 
/mvm set gamemode 1
I don't find the perfect solution because it prevents to make a creative zone in a survival zone but I'll deal with it.

**Comment by wizjany** [comment]
i mean you'd have to find some way to make multiverse *not* enforce gamemode at all and let worldguard regions handle it, but that's not a WG issue
