### ISSUE TITLE
 BUG - automatic mode change between worlds [Survival] [Creative]-

### ISSUE THREAD

**Issue by vdl19** [EngineHub/WorldGuard#1824]
**Versions**

WorldEdit version:
worldedit-bukkit-7.2.6+4b2d1e7

WorldGuard version:
worldguard-bukkit-7.0.6-SNAPSHOT-dist 7.0.6-SNAPSHOT+2150-5a6b6eb
I also did some tests after with the previous versions below with the same results:
+ WorldGuard 7.0.6 beta 1 (MC 1.17+)
+ WorldGuard 7.0.5 (MC 1.16.5)

Platform version:
Paper 1.17.1 #233

**Describe the bug**
I have an official server in Paper 1.16.5 #788 with WorldEdit: "Bukkit-Official(7.2.6-beta-01+1415e6f)" and WorldGuard "Bukkit-Official (7.0.5+3827266)".
On this server I have from my spawn a portal that sends to a "Creative" world, on this server everything works. When you go through the portal you arrive in "creative" mode and when you come back you are in "survival" mode.

This server I put it on my test server in 1.17.1 so all the settings are the same I made the update of all the possible plugins on it. 
But the problem is that when I pass the portal to the "creative" world I arrive in "Survival" I can leave and return always the same.
I have just tried to change to "creative" the small zone of arrival of the world survival, that notes it well but when I go there I remain in survival!
So the problem is that the system to change and make the players in creative does not work anymore on my test server in 1.17.1 even with the version of Worldguard 7.0.5 that I do not know adapted but I tried just in case when I saw that nothing works.

**To Reproduce**
1. create a world and set it to "survival" mode
2. create a world and set it to "creative" mode
3. make a portal (I use multiverse-portal) to go and come back and just use it

**Expected behavior**
What happens on my 1.16.5 server is that players automatically switch to "creative" mode when they arrive in the "creation" world and that they switch back to "survival" mode when they return to the "Spawn" world, as has been done for a long time on my 1.16.5 server

**Screenshots**
![image](https://user-images.githubusercontent.com/80985545/131567548-ff048ca6-aad4-4291-aae7-c8e3baba5936.png)

![image](https://user-images.githubusercontent.com/80985545/131567658-0c48d981-a2fb-464d-9873-efbd87052fb4.png)

Thank you for your time

**Comment by wizjany** [comment]
please don't create duplicate issues. additional information should be added/edited in the original.
