### ISSUE TITLE
Deprecated driver when using mysql

### ISSUE THREAD

**Issue by Tobi-Jakka** [EngineHub/WorldGuard#1825]
**Versions**
WorldEdit version:
![image](https://user-images.githubusercontent.com/42676160/132105902-3602077f-66db-4962-8dbf-c88ac26e1e6a.png)

WorldGuard version:
![image](https://user-images.githubusercontent.com/42676160/132105881-d94a12d6-a437-4b50-bbbd-a0460394ecae.png)

Platform version:
![image](https://user-images.githubusercontent.com/42676160/132105891-478afe82-3a50-495e-a60a-ccb437cee25c.png)

**Describe the bug**
![image](https://user-images.githubusercontent.com/42676160/132105845-669c3d1f-e331-4427-8d79-f537da8dfa92.png)

**To Reproduce**
1. use mysql in the main config.yml file

**Expected behavior**
An error occurs in console saying that its using a deprecated driver.

**Comment by wizjany** [comment]
sql is unsupported
