### ISSUE TITLE
Region flag respawn-anchors doesn't prevent block damage from the explosion in 1.17.1

### ISSUE THREAD

**Issue by d0gkiller87** [EngineHub/WorldGuard#1829]
**Versions**

<table>
<tr>
	<td>WorldEdit
	<td>7.2.6+4b2d1e7
<tr>
	<td>WorldGuard 
	<td>7.0.6-beta1+0b66f3e
<tr>
	<td>Platform
	<td>paper-1.17.1-255
</table>

**Describe the bug**
With `respawn-anchors` flag set to `deny`, respawn anchor still destroys blocks during explosion.

**To Reproduce**
1. Run command `/rg flag  __global__  respawn-anchors deny`
2. Charge a `respawn anchor` with `glowstone block` until it explodes and destroys blocks around it

**Expected behavior**
The region flag should prevent blocks from being destroyed by the respawn anchor's explosion.

**Screenshots**
`/wg report -p`: https://paste.enginehub.org/9-VVM0kjS.report
command was executed without error: https://cdn.discordapp.com/attachments/557486049832468481/885406109941239838/unknown.png

**Additional context**
1. In 1.16.5 setup, `/rg flag  __global__  respawn-anchors deny` was working fine.
2. In 1.17.1 setup, `/rg flag  __global__  ravager-grief deny` is working, but not the `/rg flag  __global__  respawn-anchors deny`.
3. No error messages in server console.

**Comment by stonar96** [comment]
The respawn-anchor flag (and sleep flag likewise) did never prevent block damage from exploding respawn anchors or beds and they are not meant to. These explosions are covered by the other-explosion flag, which is allowed by default.

- To prevent block damage from exploding respawn anchors (beds, etc.): Deny the other-explosion flag.
- To prevent block damage from exploding respawn anchors (beds, etc.) from outside a region: Deny the other-explosion flag for non-members.

**Comment by d0gkiller87** [comment]
> Deny the other-explosion flag.
You're right. It was our mistake, we accidentally reset other-explosion flag.
Thanks for the answer!
