### ISSUE TITLE
Can use glow_ink_sac in WG regions without permission

### ISSUE THREAD

**Issue by Spaex** [EngineHub/WorldGuard#1830]
**Versions**
WorldEdit version: Bikkot-Official(7.2.6+4b2d1e7)

WorldGuard version:  Bukkit-Official (7.0.6-beta1-0b66f3e)

Platform version: Paper version git-Paper-257(MC 1.17.1) 

**Describe the bug**
In protected WG-Regions people can't use dye's on signs if they don't have the permissions for that region (use) as it should. But in 1.17 you can place gow_ink_sac on signs which somehow doesn't get blocked by World Guard like the dyes. So players can glow up every sign on the server in protected regions.

**To Reproduce**
1. Create a WG-Region (with a sign in it) which you aren't allowed to build in
2. Use a glow_ink_sac on the sign and it will get the Glow Effect

**Expected behavior**
WG should block it with the message "Hey! Sorry, but you can't use that here."

**Comment by wizjany** [comment]
has been fixed in dev builds already
