### ISSUE TITLE
getting this error 

### ISSUE THREAD

**Issue by steda1985** [EngineHub/WorldGuard#1835]
**Versions**

WorldEdit version: 7.2.6+4b2d1e7

WorldGuard version: 7.0.6-beta1+0b66f3e

Platform version: This server is running Paper version git-Paper-130 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2f1f1b7)

**Describe the bug**
just an error spamming console

**To Reproduce**
Task #2149 for WorldGuard v7.0.6-beta1+0b66f3e generated an exception
22.09 16:56:34 [Server] INFO com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: zip file closed
22.09 16:56:34 [Server] INFO at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at com.sk89q.worldguard.session.AbstractSessionManager.get(AbstractSessionManager.java:181) ~[?:?]
22.09 16:56:34 [Server] INFO at com.sk89q.worldguard.bukkit.session.BukkitSessionManager.run(BukkitSessionManager.java:78) ~[?:?]
22.09 16:56:34 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
22.09 16:56:34 [Server] INFO Caused by: java.lang.IllegalStateException: zip file closed
22.09 16:56:34 [Server] INFO at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
22.09 16:56:34 [Server] INFO at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
22.09 16:56:34 [Server] INFO at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
22.09 16:56:34 [Server] INFO at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
22.09 16:56:34 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
22.09 16:56:34 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
22.09 16:56:34 [Server] INFO at net.goldtreeservers.worldguardextraflags.wg.wrappers.HandlerWrapper.initialize(HandlerWrapper.java:53) ~[?:?]
22.09 16:56:34 [Server] INFO at com.sk89q.worldguard.bukkit.session.TimedHandlerFactory$TimedHandler.initialize(TimedHandlerFactory.java:93) ~[?:?]
22.09 16:56:34 [Server] INFO at com.sk89q.worldguard.session.Session.initialize(Session.java:119) ~[?:?]
22.09 16:56:34 [Server] INFO at com.sk89q.worldguard.session.AbstractSessionManager.createSession(AbstractSessionManager.java:190) ~[?:?]
22.09 16:56:34 [Server] INFO at com.sk89q.worldguard.session.AbstractSessionManager.lambda$new$2(AbstractSessionManager.java:75) ~[?:?]
22.09 16:56:34 [Server] INFO at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:146) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[patched_1.17.1.jar:git-Paper-130]
22.09 16:56:34 [Server] INFO ... 14 more

**Expected behavior**
console no9t spamming

**Screenshots**

**Additional context**

**Comment by steda1985** [comment]
and why was this closed

**Comment by wizjany** [comment]
![](https://i.imgur.com/OgHdr5v.png)
