### ISSUE TITLE
Permission not working

### ISSUE THREAD

**Issue by awesomeguy36** [EngineHub/WorldGuard#1836]
WorldGuard version: 7.0.6

Platform version: Bukkit

For some reason, all the permissions under "Per-Region Commands" (https://worldguard.enginehub.org/en/latest/permissions/) aren't working for my Moderator group. I've tried everything like removing the * which wouldn't make much sense but I figured maybe just using the base permission would work but no luck. I also tried adding the worldguard.* to see if I was missing something and it still didn't work. I also updated the plugin to the newest version but it still will not work. All the other permissions I've added have worked like worldguard.region.define.

**Comment by me4502** [comment]
You should use your permissions plugin's verbose mode for this - but realistically this is something you'd have to ask for assistance with from your permission plugin. Permissions in WorldGuard definitely work, so it's up to how you've set it up.

Issues are also for bug reports, not asking for assistance.
