### ISSUE TITLE
Error produced on Blacklist dispense logging.

### ISSUE THREAD

**Issue by Raesak** [EngineHub/WorldGuard#1837]
Minecraft: 1.17.1
Paper: 278
WG: 7.0.7-SNAPSHOT

This error occurs when a blacklisted dispense event is logged. As a result of this error, the action is not logged, AND also not denied if the deny action is configured:
https://pastebin.com/QrhUFRZ8

I used the code:
```
# Test
[stone]
on-dispense=deny,notify,log
```

**Comment by JOO200** [comment]
Fixed in https://github.com/EngineHub/WorldGuard/commit/9b665136d0beb92ce2d251acc4919df92f1754c1
