### ISSUE TITLE
mob-spawning flag set to deny does not prevent zombie/skeleton horses from being spawned

### ISSUE THREAD

**Issue by marvjosh1** [EngineHub/WorldGuard#1840]
**Versions**

WorldEdit version:
FAWE Build 277
WorldGuard version:
7.0.6-SNAPSHOT+2152-51fa25d
Platform version:
Purpur 1.17.1-R0.1-SNAPSHOT

**Describe the bug**
When the mob-spawning flag is set to deny, it does not prevent zombie horses and skeleton horses from being spawned with spawn eggs

**To Reproduce**
1. Set up a region
2. Set the mob-spawning flag to deny
3. Try spawning various mobs with spawn eggs, they will not spawn
4. Try spawning zombie horses and skeleton horses with spawn eggs, they will spawn

**Expected behavior**
Zombie and Skeleton Horses should be prevented from spawning aswell

**Screenshots**
https://i.imgur.com/XcS5wZu.png - /rg info
https://www.youtube.com/watch?v=QJkzVswF9fM - video of this happening

**Comment by me4502** [comment]
We do not support forks of WorldEdit, or forks of Paper. Both are known to cause major issues in plugins.

Try using WorldEdit and Paper
