### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by ver151set** [EngineHub/WorldGuard#1843]
**Versions**

WorldEdit version:
7.2.6
WorldGuard version:
7.0.7
Platform version:
1.17.1
Java 16

**Describe the bug**
Server crashes on boot unless I delete Worldguard cache

Relevant crash log - https://pastebin.com/Eb5it0er

**To Reproduce**
1. Reboot server without deleting cache

**Comment by wizjany** [comment]
duplicate
