### ISSUE TITLE
Improve Horse Disembark in Protected Region

### ISSUE THREAD

**Issue by Strahilchu** [EngineHub/WorldGuard#1846]
**Is your feature request related to a problem? Please describe.**
 A current feature in WG is "Added a check so players can no longer disembark in a region from their tamed animal if they don't have permission to get back on." This left a player stuck in someone's region with no way out (auto door closed behind them) 

**Describe the solution you'd like**
 Make it so player can get on and off their horse if they are the owner of it, or if they entered the region while riding a mob to let them get on and off that particular entity. 

**Describe alternatives you've considered**
Not sure what the best solution is for this but if it could teleport them out of the region or give them access to mount particular entity when attempting to disembark it would work.

**Comment by wizjany** [comment]
horse ownership is entirely non-binding for gameplay purposes, which means another player can still steal a horse they don't own. I suggest if you want ownership to be actually useful, you set the ride flag to allow in WG (so WG no longer protects any of it) and find a separate plugin for "horse protection" or whatever.
