### ISSUE TITLE
DeepCode AI detected potential high risk vulnerability

### ISSUE THREAD

**Issue by Strahilchu** [EngineHub/WorldGuard#1848]
![WGDeepCode](https://user-images.githubusercontent.com/69178324/139775178-99a8072e-535e-4b44-8168-3d6d0ba9845d.JPG)

**Comment by me4502** [comment]
The SQL backend is unsupported.

**Comment by wizjany** [comment]
not even an sql thing. this is literally our input data being read back in.

**Comment by Strahilchu** [comment]
Good to know it's nothing serious, just wanted it to be seen just in case!
