### ISSUE TITLE
guarded region reverse thinking

### ISSUE THREAD

**Issue by MsKiller01** [EngineHub/WorldGuard#1849]
**Is your feature request related to a problem? Please describe.**

When making a region guarded, allowing and denying actions in that region, should it not be open to added owners and or members?

**Describe the solution you'd like**

Making a region guarded and deny or allow actions inside should be inactive for co-owners and members by choice.

**Describe alternatives you've considered**

preciousstones has this if I am correct. So why protecting or making an area so that still owners,members and non-owners and non-members can do the same?

**Additional context**

I hope this is a bug or simply my fault for not understanding how its intentions are, but I would surely like to protect an area and lift the protection for co-owners and members... that's all....

Thanks.

**Comment by JOO200** [comment]
I suggest to read the [quickstart guide](https://worldguard.enginehub.org/en/latest/regions/quick-start/).

Regions are already protected by default, you don't need to set any flags. Only (region) members and owners can build in that region then. You shouldn't need to "deny actions" inside a region as the region is already protected.

For further support visit the discord, GitHub Issues are not a help channel.

**Comment by MsKiller01** [comment]
oh, ok, but I was adding a suggestion, and because this is possible here and put issues here too, so I thought that THIS was the right place.... Sorry if I was not aware there are other places to look for support.....
