### ISSUE TITLE
Tileentities Protection Bug (Item Frames, Paintings, Armor stands..)

### ISSUE THREAD

**Issue by ConaII** [EngineHub/WorldGuard#1850]
**Versions**

WorldEdit version:
  FastAsyncWorldEdit-1.17-390
WorldGuard version:
 WorldGuard 7.0.5 (MC 1.16.5)

Platform version:
 git-Purpur-1171 (MC: 1.16.5) 

**Describe the bug**

**To Reproduce**

1. Protect a selected area.
2. Place empty item frames, paintings and armor stands. 
3. Deop or remove permissions, change to user group, whatever.
4. Try breaking them, it sends a message that you can't break that here, but, it will break anyways.
(Sometimes armor stands can't be broken and sometimes they can, idk.)

**Expected behavior**

The tileenties can't be broken, as expected for the protection...

**Screenshots**

**Additional context**

**Comment by me4502** [comment]
a) Those are not tile entities, they're entities
b) We do not support neither FAWE or Purpur

**Comment by ConaII** [comment]
Right, sorry, i forgot that tileentities are only signs, chests., etc
Blocks that hold data, my bad.

The issue was FAWE, im going to report it there.
