### ISSUE TITLE
invincible flag is not working with EssentialsX

### ISSUE THREAD

**Issue by rona-tombo** [EngineHub/WorldGuard#1852]
**Versions**

WorldEdit version:
`7.2.7+9f3e795`
WorldGuard version:
`7.0.6+1cff55f`
Platform version:
`git-Paper-280 (MC: 1.17.1`

**Describe the bug**

`invincible` flag is not working with EssentialsX.
**To Reproduce**

1. Install WorldEdit / WorldGuard / EssentialsX to the server and start it.
2. Define a region (`/rg define test`) and set a invincible flag (`rg flag test invincible allow`)

**Expected behavior**

Player made as invincible

**Screenshots**

![image](https://user-images.githubusercontent.com/41550858/141840839-f0e85053-db74-4f08-98a1-721d9a65a790.png)

**Additional context**

**Comment by wizjany** [comment]
does this imply that it is working without EssX? in that case you'd have to ask them what they're doing/report it to them. not much we can do about other plugins.
