### ISSUE TITLE
NullPointer

### ISSUE THREAD

**Issue by TheKlimoT** [EngineHub/WorldGuard#1853]
**Versions**
WorldEdit version: 7.2.7

WorldGuard version: 7.0.5

Platform version: 1.16.5 Mohist

**Describe the bug**
I using mod TConstruct, and use EFLN or another item, and console spam error

**To Reproduce**

1. Take EFLN or another shooting item
2. Shoot him, and console spam
Error: https://www.toptal.com/developers/hastebin/romugoyugo.properties

**Comment by JOO200** [comment]
Unsupported platform, Mohist is not supported.
