### ISSUE TITLE
Extinguishing or lighting a campfire is considered placing or breaking a block

### ISSUE THREAD

**Issue by tarmael** [EngineHub/WorldGuard#1865]
### WorldEdit Version

7.2.8

### WorldGuard Version

7.0.6

### Platform Version

paper-1.18.1-105

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

In a region with the following set:
  block-place Deny
  block-break Deny
  lighter Allow
  interact Allow
  use Allow

Trying to light a campfire with a flint and steel says, "Sorry you can't place that block here"

If I set block-place Allow, then I can light the campfire.

No other mods are installed other than WorldEdit and WorldGuard

### Expected Behavior

Campfire should light with lighter Allow

### Reproduction Steps

In a region with the following set:
  block-place Deny
  block-break Deny
  lighter Allow
  interact Allow
  use Allow

**Comment by wizjany** [comment]
that's expected behavior and not unique to campfires at all. very many things in bukkit use block change events which are handled as a break+place.
