### ISSUE TITLE
block-plugin-spawning: false, mythicmobs mobs still can't spawn

### ISSUE THREAD

**Issue by MithrandirCraft** [EngineHub/WorldGuard#1871]
### WorldEdit Version

FAWE 2.0.0

### WorldGuard Version

7.0.7

### Platform Version

Paper version git-Paper-132 (MC: 1.18.1)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Using in config.yml:
`block-plugin-spawning: false`
MythicMobs still can't spawn in `mob-spawning deny` flagged regions.

### Expected Behavior

MythicMobs should be able to spawn it's mobs, even in regions flagged against mob spawning, as long as this config is false.

### Reproduction Steps

1. Install MythicMobs, FAWE & WorldGuard on a Paper 1.18.1 MC server.
2. Create a new region, and deny mob-spawning in it with the flag.
3. Spawn a mythicmob. You will get a denial message indicating for you to check on other plugins blocking spawn.

### Anything Else?

I had to mark "I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)", but in truth, I am using it.

I am confused, I thought WorldGuard started supporting FAWE recently. In any case, this issue is also present using WorldEdit instead (which I highly doubt is relevant).

**Comment by wizjany** [comment]
we've literally never support WE forks.
we also can't do anything about the way MM handles spawns. you'll have to go bug them about it.
