### ISSUE TITLE
wither

### ISSUE THREAD

**Issue by Shagbanov** [EngineHub/WorldGuard#1872]
### WorldEdit Version

7.2.6

### WorldGuard Version

7.0.6

### Platform Version

PaperSpigot 1.17.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

wither does not break blocks in the region 

### Expected Behavior

wither must break blocks in the region 

### Reproduction Steps

1)The player creates a wieser
2)The player leads the wieser to a foreign region
3)Wieser does not break blocks in a foreign region 

### Optional WorldGuard-Report

https://paste.enginehub.org/XfgUFZrPd.report

**Comment by JOO200** [comment]
Try to reproduce it with only worldedit and worldguard without AWE.
You're using AsyncWorldEdit which is a fork from WorldEdit. We don't give support with installed worldedit forks.

**Comment by Shagbanov** [comment]
https://paste.enginehub.org/lakcUwjOa.report

**Comment by wizjany** [comment]
works as intended. non-members of regions shouldn't be able to grief protected regions.

**Comment by Shagbanov** [comment]
I want to make it so that they can destroy blocks in other people's private using wither

**Comment by wizjany** [comment]
that's not supported by WG
