### ISSUE TITLE
Red Sand still falls when no-physics-sand: true

### ISSUE THREAD

**Issue by BlueLord444** [EngineHub/WorldGuard#1877]
### WorldEdit Version

7.2.8

### WorldGuard Version

7.0.6

### Platform Version

Paper 1.18.1 Build #152

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I currently have both 'no-physics-sand: true' and 'no-physics-gravel: true'

Currently it looks like red sand doesn't qualify under these conditions.

See link below for demo.
https://imgur.com/a/Tv459CV

### Expected Behavior

I would expect that red sand also get its physics removed when switching 'no-physics-sand: true'

Either red sand needs to be added into this flag or needs a new flag entirely. Also it looks like there have been suggestions to add concrete powder and anvils into this physics flag category.

### Reproduction Steps

1. In the config.yml, set 'no-physics-sand: true'
2. Normal Sand works but Red Sand doesn't

**Comment by wizjany** [comment]
has been covered before

**Comment by wizjany** [comment]
er wait, are you saying normal sand does work? because it's been reported multiple times that the option doesn't work at all because spigot broke how physics events work.

**Comment by BlueLord444** [comment]
Yes, gravel and sand work fine. I am on 1.18.1 Paper and had no issues with it

**Comment by BlueLord444** [comment]
So nothing is going to be done about this?
