### ISSUE TITLE
WorldGuard seemingly taking up CPU time unnecessarily.

### ISSUE THREAD

**Issue by ZepsiZola** [EngineHub/WorldGuard#1878]
### WorldEdit Version

7.2.8+6008-1246d61

### WorldGuard Version

7.0.6+1cff55f

### Platform Version

Purpur 1504

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

![image](https://user-images.githubusercontent.com/49735083/150527431-e52d169a-8177-4740-b5b0-f5c2198af76e.png)
https://timings.aikar.co/?id=6e4a56bb791349b59ac3732290d171aa
I feel like WorldGuard shouldn't be taking this much processing with Hoppers. I don't see how it is necessary.

### Expected Behavior

WorldGuard shouldn't have such a big impact on performance because of hoppers.

### Reproduction Steps

Just run hoppers on your server with worldguard and do `/timings paste`.

**Comment by JOO200** [comment]
You can disable it for hoppers in your config.
https://worldguard.enginehub.org/en/latest/config/?highlight=hopper#event-handling

WG prevents item grief from chests with hoppers, therefore it has to listen for those events.
