### ISSUE TITLE
Extinguishing candles shouldn't depend on the interact flag

### ISSUE THREAD

**Issue by TheoRetisch1** [EngineHub/WorldGuard#1880]
### WorldEdit Version

7.2.9-SNAPSHOT

### WorldGuard Version

7.0.7-SNAPSHOT+2174-4abf971

### Platform Version

git-Paper-173 (MC: 1.18.1)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description
The extinguishing of candles depends on the interact flag. This should not be the case because extinguishing candles is more equivalent to destruction than simple interaction. While other objects affected by the interact flag can be restored to their original state with another click, candles require permissions to relight them. Thus, extinguishing candles does not correspond to the original intention of the interact flag. Furthermore, it is highly incosequent to include lighting and extinguishing candles in different flags. Would be cool if interacting with candles could be bound to building rights.

### Expected Behavior

Extinguishing candles only should be possible with building rights.

### Reproduction Steps

1. Protect a region.
2. Set interact to allow.
2. Right click a candle without building rights -> the candle goes out

**Comment by stonar96** [comment]
Still works just fine for me. (https://discord.com/channels/80853743897149440/470410381597343753/919566207093461002)

**Comment by TheoRetisch1** [comment]
Thanks for testing, let's change the title of the bug report:
The extinguishing of candles depends on the interact flag. This shouldn't be the case because extinguishing candles is more equivalent to destruction than simple interaction. While other objects affected by the interact flag can be restored to their original state with another click, candles require permissions to relight them. Thus, extinguishing candles does not correspond to the original intention of the interact flag. Furthermore, it is highly incosequent to include lighting and extinguishing candles in different flags. Would be cool if interacting with candles could be bound to building rights.
