### ISSUE TITLE
LuckPerms Contexts Integration

### ISSUE THREAD

**Issue by ArcticRaven** [EngineHub/WorldGuard#1883]
### The Problem

I would like to be able to use regions as a context within LuckPerms. This would allow the negation of certain plugin abilities while in regions and make things much easier for server setups and map making. 

### A Solution

The ability to inject custom contexts already exists - its documented on LuckPerms wiki (url)https://luckperms.net/wiki/Developer-API-Usage#the-basics-of-context

### Alternatives

We could implement a custom solution with a 3rd party plugin and  bridging the gap with both parties APIs - however that solution doesn't benefit the general server administrative community. 

### Anything Else?

Waifus <3

**Comment by wizjany** [comment]
do a bit of research at least, cmon.
