### ISSUE TITLE
Looms aren't denied

### ISSUE THREAD

**Issue by Nononitas** [EngineHub/WorldGuard#1887]
### WorldEdit Version

7.2.9+e20e013

### WorldGuard Version

7.0.7+2183-79a3b70

### Platform Version

Paper-409 (1.17.1)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I can use looms, although interact is on denyand chest-access is on deny

### Expected Behavior

I can't use looms

### Reproduction Steps

Using the global region with these flags https://pastebin.com/MmaGZtYA
Player doesn't have * or any worldguard perms

**Comment by wizjany** [comment]
not a bug, this is the same as all non-inventory crafting blocks.

**Comment by Nononitas** [comment]
Hmm, could then be a flag added for these?
