### ISSUE TITLE
Wrong UUID is retrieved

### ISSUE THREAD

**Issue by r4nx** [EngineHub/WorldGuard#1892]
### WorldEdit Version

7.2.10

### WorldGuard Version

7.0.7

### Platform Version

git-Paper-274

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

First of all, the server is running in offline mode, I guess it matters here. Player Il_Magellano claimed the region with `/rg claim` and complained he couldn't access it. I've checked the `/rg info`, there was his name in owners list, but at the same time `/rg list -p Il_Magellano` was empty.

Then I looked into `regions.yml`, found the region and the owner UUID was totally different - `594ed714-aba5-3204-960d-b196bf0cd60b`, it doesn't appear anywhere on the server, while his real UUID is `ab473d9f-21a9-3790-8fb1-dedd22f14648`.

I changed the UUID manually, reloaded WorldGuard and the player gained access to his region. Meanwhile, `profiles.sqlite` contained the following:
![image](https://user-images.githubusercontent.com/30746510/161402140-c8cf8941-039e-406f-8930-4a1838f57a14.png)

### Expected Behavior

Correct UUID retrieval

### Reproduction Steps

Unknown, maybe claiming the region with this particular name and offline mode enabled will reproduce the bug

**Comment by wizjany** [comment]
piracy is not supported.

**Comment by r4nx** [comment]
> piracy is not supported.

The server is running on local network without global Internet access and offline mode is officially supported legit feature, why would you talk about piracy at all?

**Comment by TheUserDead** [comment]
@wizjany 
The whle time from bukkit 1.4.* version, everyone works for great ideas and plugins. Someone buy them, someone donate to deelopers. And now in 1.18.* at this time you remember about piracy?
i think you little mismatched the whole idea and Open Source things. Not all offline mode players pirates game\server\anything.
Why oficially game has this funcrion? If developers choose totally remove "illigal use" it's been hard to play, patch, download game\servers, but they don't.
What if your donations accepted from fun\pirated server? You are not in this boat?
Please review your choose or maybe need to stop work on open source?
And at least [remember this ](https://www.forbes.com/sites/davidthier/2012/01/12/minecraft-creator-notch-tells-players-to-pirate-his-game/?sh=1cd96dff4eb6)
Maybe i'm not right. I didn't mean to offend you.
