### ISSUE TITLE
Heads can be broken and collected in a protected region via water/lava buckets.

### ISSUE THREAD

**Issue by accLarson** [EngineHub/WorldGuard#1898]
### WorldEdit Version

7.2.9

### WorldGuard Version

7.0.7

### Platform Version

git-purpur-1606

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Heads can be broken and collected by players who do not have permission by spam placing water or lava in the same block space as the head while standing on the head. In my testing you must spam click via rebinding the `use` key from `right mouse button` to `space bar` to simulate incredibly fast "click speed". 

I speculate that the need for the player to stand on the head has something to do with the players hit box dropping into the heads hit box for a moment while world guard attempts to cancel the head breaking, causing some hit box placement issue. This confused me because in my testing, heads were the only block that this worked on. I attempted similar blocks such as end rods and flowerpots which also break when in contact with water/lava and have a hit box but this bug did not work on those items.

### Expected Behavior

Head remains unbroken when spammed with water/lava placement.

### Reproduction Steps

1. Create a world guard protected region.
2. Place a head in the region.
3. Switch to an account without wg permissions.
4. Rebind the `use` key from `right mouse button` to `space bar` to simulate incredibly fast "click speed".
5. Stand atop the placed head holding a water or lava bucket.
6. Hold space bar to repeatedly spam water or lava into the same block space as the head (aim for an adjacent solid block)
7. RESULT: Head will pop off and can be collected.

### Anything Else?

Note that if the head is positioned in such a way that the only blocks adjacent to it are able to be waterlogged, you will not be able to replicate as you need to place water into the same block space as the head itself and that is only possible by placing on adjacent blocks.

**Comment by wizjany** [comment]
can't repro and even if you could somehow this would be a server bug not a WG one.

**Comment by accLarson** [comment]
Hmm, I've tested on a few random servers and it worked on all of them, are you certain?

**Comment by wizjany** [comment]
most i've managed is to get a ghost water block client side, but the head doesn't pop off, the water doesn't flow, etc. again, as long as bukkit is giving us events, we're cancelling them. if *somehow* packet spam is managed to place blocks without an event getting thrown, it's a server issue, not a WG one.
