### ISSUE TITLE
Entry deny bypass permission

### ISSUE THREAD

**Issue by Korwey** [EngineHub/WorldGuard#1907]
### The Problem

I'm using WorldGuard as a dependency for ProtectionStones on my survival server, and players are able to set flags to their regions. If they set the entry to deny, staff can't enter their regions.

### A Solution

There should be a bypass permission for only the entry flag.

**Comment by me4502** [comment]
Just set the flag state correctly, https://worldguard.enginehub.org/en/latest/regions/flags/

**Comment by stonar96** [comment]
@Korwey there is an extended discussion and solution regarding your issue on Discord [here](https://discord.com/channels/80853743897149440/540076527593717760/968123416525832233).
