### ISSUE TITLE
PVP dosent work

### ISSUE THREAD

**Issue by REDKING-11** [EngineHub/WorldGuard#1908]
### WorldEdit Version

7.2.10

### WorldGuard Version

7.0.7

### Platform Version

spigot

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

pvp dosent work in area but ewerywhere else

### Expected Behavior

pvp dosent work in area but ewerywhere else

### Reproduction Steps

made reguin
configured region
pvp didint work

### Optional WorldGuard-Report

https://paste.enginehub.org/0Pr8h6wgG.report

### Anything Else?

nope

**Comment by wizjany** [comment]
"doesn't work" isn't a proper bug report. best guess is some other plugin messing with things. try reproducing with just WE+WG, otherwise please amend your report with proper reproduction and description.
