### ISSUE TITLE
Doors cannot be interacted with when Interact and Use are set to Allow

### ISSUE THREAD

**Issue by DrekiLunin** [EngineHub/WorldGuard#1910]
### WorldEdit Version

7.2.10+1742f98

### WorldGuard Version

7.0.7+216b061

### Platform Version

Paper Latest (Java 17 - Current 1.18.2 #332)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When `Interact` and `Use` are both set to `Allow` doors cannot be opened. by non-OP'd players.

### Expected Behavior

Doors can be interacted with. 

### Reproduction Steps

1. Set `Interact` and `Use` to `Allow` in a defined region
2. deop the player
3. Attempt to open a door within the defined region

### Optional WorldGuard-Report

https://paste.enginehub.org/K8S5nc1gB.report

**Comment by wizjany** [comment]
report shows you're not even in a region.
