### ISSUE TITLE
Config option to disable events

### ISSUE THREAD

**Issue by WarnDa** [EngineHub/WorldGuard#1911]
### The Problem

Worldguard is always at the top list of plugins in spark
![image](https://user-images.githubusercontent.com/31826333/168262317-f21853e0-38e7-4e1e-b1d7-9a4039aeacf8.png)

### A Solution

Add more events to config that can be disabled.
For example : 
- pistons
- fluids
- dispensers

(I got no world where player could place piston and try to push items in regions they can't build, same with fluids)
As I only got a world spawn, and a world for their island (and superior already protect for this)

**Comment by WarnDa** [comment]
I already have : 
> protect-against-liquid-flow: false

but it still checks for fluids

**Comment by WarnDa** [comment]
Spark of 1hr to show that worldguard consume the most : 
https://spark.lucko.me/Jr1ueGjUfI
![image](https://user-images.githubusercontent.com/31826333/169817762-a9400091-e95d-4f06-8cc0-d08b1ba17c25.png)

**Comment by me4502** [comment]
Honestly if you're trying to perform micro-optimisations like that, write a plugin to remove WorldGuard's event handlers from the Bukkit events.

These amounts are tiny and don't justify adding in configuration options that will lead to confused users. The existing ones are for situations where a trade-off between protection accuracy and speed can result in substantial TPS improvements, not minor savings. Users already change these settings and get confused why things don't work like they want; adding more without strong justification just doesn't make sense.

**Comment by WarnDa** [comment]
"micro-optimisation", it would make worldguard consume 0.2% instead of 1% (so 5x less), I'm sure a lot of owner would be happy of that.

And you could change config to set a section where player see all events that can be disabled and 1-2 lines that explain what it means, so it wouldn't be a random settings in the middle of the config.

**Comment by wizjany** [comment]
yea ngl really considering removing the existing configs entirely because it either leads to people using the flags and not understanding why they aren't working (high freq flags), or turning off things like use-player-move and wondering why session flags aren't working.
