### ISSUE TITLE
Mod worldguard

### ISSUE THREAD

**Issue by joaoespanhol** [EngineHub/WorldGuard#1912]
### The Problem

currently there is no mod that protects the world, like making worldguard.
The idea is to conventer the plugin to mod, as was done by worldedit.

### A Solution

Worldguard also lets players select an area anywhere in the world and protect it, so other players don't steal or steal like another mod or plugin.

**Comment by JOO200** [comment]
That's not easily possible. You can't protect everything against mods and many mods do some weird modification of worlds.

Therefore we can't port WorldGuard easily to Fabric or Forge.
