### ISSUE TITLE
The 'rg define' command requests to add Chinese support

### ISSUE THREAD

**Issue by yebanme** [EngineHub/WorldGuard#1918]
### The Problem

Currently, the plugin cannot name the new area in Chinese when defining it. Once the Chinese name is used, the plugin will prompt that the characters that are not allowed appear

### A Solution

I don't know how the plug-in should support Chinese, but I think it may be related to the file coding

**Comment by JOO200** [comment]
The rg id is meant to be unique and for maintanance reasons and other reasons we won't change the current limitations.

It is not related to file encoding, WorldGuard works fine with utf8 encoded stuff.

You can use utf8 (with Chinese language support) for StringFlags such as deny-message, greeting and farewell. If you want to show the region name somewhere you should consider using a custom flag for that.
