### ISSUE TITLE
Allays are not correctly protected

### ISSUE THREAD

**Issue by Joo200** [EngineHub/WorldGuard#1923]
### WorldEdit Version

7.0.11-SNAPSHOT

### WorldGuard Version

7.0.8-SNAPSHOT

### Platform Version

all

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Allays are not correctly protected.
They can pickup items in a region with the flag item-pickup set to deny.

### Expected Behavior

EntityPickupItemEvent should be denied when the Allay's owner can't pickup items at that place.

### Reproduction Steps

1. Create a region with item-pickup deny
2. Spawn an Allay
3. Drop items

**Comment by wizjany** [comment]
think we might also have to protect against people being able to add/remove the item the allay is "holding" as well?
