### ISSUE TITLE
New Flag - define what blocks cant be broken within the block-break flag

### ISSUE THREAD

**Issue by DrWackyBob** [EngineHub/WorldGuard#1928]
### The Problem

On a server i manage we are using the plugin to stop players from taking diamond blocks away from the diamond pile at the shopping district. To do this we are using the block-place flag so they can add a diamond block but then not remove any to stop stealing.

### A Solution

It would be great if you could define what block can't be broken within the block-break flag so that players can still use shulker boxes around the pile.

### Anything Else?

Thanks for the great plugin!

**Comment by wizjany** [comment]
duplicate
