### ISSUE TITLE
Can't click links in chat while WorldGuard is active (default server + plugin setup)

### ISSUE THREAD

**Issue by MithrandirCraft** [EngineHub/WorldGuard#1929]
### WorldEdit Version

7.2.10

### WorldGuard Version

7.0.7

### Platform Version

git-Paper-359 (MC: 1.18.2)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

While WorldGuard is installed + active on a Paper server, you can't click any chat hyperlinks.

I haven't tested this extensively, but it is posible some links are clickable, I just couldn't do it on my test server.

On my main server, some voting links are clickable, while or website's link isn't.

It doesn't seem to matter if the hyperlink is using the https://www., http://www, or mere www prefixes, the hyperlink block can still happen.

### Expected Behavior

Hyperlinks should be clickable.

### Reproduction Steps

1. Start a new 1.18.2 Paper server
2. Log into it and test hyperlinks in chat by writing a few website dns's.
3. Stop the server, install WorldEdit + WorldGuard
4. Start the server, log into it and test hyperlinks in chat.

### Anything Else?

Hyperlinks are not clickable in step 4 because WorldGuard is installed. This has been tested by many diferent clients (on my main server), all of which had hyperlinks enabled in their config.

**Comment by wizjany** [comment]
upstream issue as noted https://github.com/EssentialsX/Essentials/issues/4970#issuecomment-1380731664
