### ISSUE TITLE
Debug stick bug

### ISSUE THREAD

**Issue by Nubet** [EngineHub/WorldGuard#1932]
### WorldEdit Version

 7.2.11 

### WorldGuard Version

7.0.8-SNAPSHOT

### Platform Version

paper 1.19

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Like you now debug stick is a item that you can get only using commands, but in situation when plugin allow to craft this item player without op can succefully use this item on protected region withouts op permissions

### Expected Behavior

Block using debug stick at region protected by world guard user without op

### Reproduction Steps

1. ...
2. ...

### Anything Else?

example of plugin allowing to craft debug stick https://www.spigotmc.org/resources/debug-stick-in-survival.102837/

**Comment by wizjany** [comment]
there's a reason it's an op-only item generally. kinda on you for giving it to players.
