### ISSUE TITLE
rg flags

### ISSUE THREAD

**Issue by TOWUK** [EngineHub/WorldGuard#1935]
### WorldEdit Version

WE latest

### WorldGuard Version

latest from ur website

### Platform Version

papermc 1.19 latest

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

add flag deny use workbech! (interact/build/use not deny use crafting table!!!)

### Expected Behavior

allow/deny crafting table

i deny for all use/interact/build and bedrock users can use it!!!
but another deny like a beacon/forge/...

### Reproduction Steps

![image](https://user-images.githubusercontent.com/28830162/178360042-4247b3e3-eebe-4edb-95f0-c6d3732f997e.png)
![image](https://user-images.githubusercontent.com/28830162/178360137-343c7400-f2ec-4054-a7e7-9328dc8d4213.png)
![image](https://user-images.githubusercontent.com/28830162/178360570-a1914b69-060f-44fd-9c79-95c4a6a5b146.png)

### Optional WorldGuard-Report

https://paste.enginehub.org/t4sbg7zqo.report

**Comment by JOO200** [comment]
You just ignored the report template because you're using a WorldEdit fork. And we do not support servers in offline mode.

**Comment by TOWUK** [comment]
Okay, i use online mode server, with online mode proxy, fawe similar plugin...
