### ISSUE TITLE
Problem with minecart hopper

### ISSUE THREAD

**Issue by DjeyMute** [EngineHub/WorldGuard#1938]
### WorldEdit Version

7.2.11 SNAPSHOT 6202

### WorldGuard Version

7.0.8 SNAPSHOT 2202

### Platform Version

Paper-61 Mc 1.19

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I create a claim the minecart hopper no longer retrieves items from chests.

### Expected Behavior

It is necessary that even in a claim the minecart hopper can continue to take the items in the chests

### Reproduction Steps

1. ...
2. ...

**Comment by wizjany** [comment]
https://github.com/EngineHub/WorldGuard/issues?q=is%3Aissue+hopper+minecart

**Comment by DjeyMute** [comment]
So I don't have a solution?
None of the other threads answer my problem.
I started the configuration from scratch.
No flag is set and should be set to do this basic action.
