### ISSUE TITLE
Flag bypass (for staff uses)

### ISSUE THREAD

**Issue by rockrevenchy** [EngineHub/WorldGuard#1941]
### The Problem

Having a specific group (or multiple specific groups) be allowed to bypass only one flag on any regions from a server or a world is kinda complicated and sometimes straight up impossible in servers such as skyblocks, plots managers or chunk claiming survivals.

Sometimes players are allowed to deny entry or prevent picking up items, killing animals / monsters etc. and staff ends up getting stuck trying to fix issues until admins or other staff with full permissions gets in (we dont always want to give all region perms to a helper for example but we still dont want them to be denied entry)

### A Solution

The idea would be to extend worldguard.region.bypass permission to allow bypassing specific flags. something like worldguard.region.bypass.entry or worldguard.region.bypass.entry.\<world\>

### Anything Else?

(im on engine hub discord, my name is RockRevenchy#6969 if you want to contact me there instead)

**Comment by wizjany** [comment]
this has been covered quite a few times before and basically it's a big no. you either trust people with bypass or you set up regions properly for exactly your use case.
