### ISSUE TITLE
Grindstones interactable even when Interact set to Deny

### ISSUE THREAD

**Issue by notenoughbees** [EngineHub/WorldGuard#1942]
### WorldEdit Version

7.2.11-beta-01

### WorldGuard Version

7.0.8-beta-01

### Platform Version

paper-1.19-81

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

In a region, if you set the Interact flag to Deny, any grindstones in the region are still usable by players. They can open the menu, put items in, and repair/disenchant them. I've tried denying multiple other flags like chest-access and build (even though Interact should work by itself), but grindstones are still always usable by everyone.

### Expected Behavior

Expected behaviour is that when you set Interact to Deny, players should be completly unable to use grindstones, not even being able to open them.

### Reproduction Steps

1. Make a region
2. Place a grindstone in it
3. Set the Interact flag to Deny
4. Have a player who isn't a member of the region try to use the grindstone: they can.

### Anything Else?

No messages pop up saying "Hey! You can't use that here" when using the grindstone.

Also, when I try /wg debug testinteract <player> on a grindstone when Interact is denied, chat says that no plugins cancelled the 
event, but it does for chests, furnaces etc.
![2022-07-31_13 22 28](https://user-images.githubusercontent.com/62003733/182005681-c0dfb0ed-eeea-41b3-a3dc-8699b803a1a8.png)
![2022-07-31_13 26 37](https://user-images.githubusercontent.com/62003733/182005784-c9a51e4d-23a9-4f02-81d9-93f2792fbbe8.png)

**Comment by wizjany** [comment]
not a bug. this is consistent behavior with all crafting stations.
note that crafting stations aren't inventories like chests and furnaces, so that bit is entirely irrelevant.
