### ISSUE TITLE
/stack command doesn't work

### ISSUE THREAD

**Issue by crumpkatrina** [EngineHub/WorldGuard#1943]
### WorldEdit Version

7.2.11 Build 6232

### WorldGuard Version

7.0.8 Build 2204

### Platform Version

Paper 1.19.1 Build 91

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

The /stack command does not seem to function at all, yet is listed here (https://worldguard.enginehub.org/en/latest/permissions/) as well as here (https://github.com/EngineHub/WorldGuard/blob/de22a5cd255aadbd8c9bd1e8d45429aa3a775291/worldguard-core/src/main/java/com/sk89q/worldguard/commands/GeneralCommands.java#L232) We have used LuckPerms verbose, and it seems that no permission is even being checked here for worldguard.stack. Has this command been discontinued or is it simply broken? We have tried /worldguard:stack as well to no avail. All that is shown upon using /stack is (https://i.imgur.com/EhyTv7K.png). No other errors in game or in console. 

### Expected Behavior

Command to exist and function (?)

### Reproduction Steps

1. Use /stack

**Comment by mibby** [comment]
Also affecting ``/god`` and some other worldguard commands.

**Comment by wizjany** [comment]
this affects everything in GeneralCommands, which is registered a tick late due to commandbook compat. presumably we can rip commandbook compat out nowadays, but given that we didn't change anything on our end this sounds like a server bug with how commands are handled. guessing upstream changed something at some point.

**Comment by mibby** [comment]
> presumably we can rip commandbook compat out nowadays

Is this something planned or should I report the issue upstream in Paper? Some of these commands are a bit critical to have working in my environment and it's a little late for me to downgrade now.

**Comment by me4502** [comment]
Either way it makes sense to report the fact that delayed registration fails to Paper, as that's a bug

**Comment by mibby** [comment]
Is it just this that needs to be ripped out of WorldGuard to fix commands registering? As I don't think it is going to be fixed upstream anytime soon.

```
        getServer().getScheduler().scheduleSyncDelayedTask(this, () -> {
            if (!platform.getGlobalStateManager().hasCommandBookGodMode()) {
                reg.register(GeneralCommands.class);
            }
        }, 0L);

        getServer().getScheduler().scheduleSyncRepeatingTask(this, sessionManager, BukkitSessionManager.RUN_DELAY, BukkitSessionManager.RUN_DELAY);
```

**Comment by Castiella** [comment]
> 

Hi, did this work? We are trying to fix the same issue.
