### ISSUE TITLE
WG not properly listening to the SignChangeEvent

### ISSUE THREAD

**Issue by Laukage** [EngineHub/WorldGuard#1944]
### WorldEdit Version

Worldedit 7.2.11-beta-01+6200-0877589

### WorldGuard Version

7.0.8-snapshot+2201-6efdb10

### Platform Version

Purpur-1732 (1.19)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

The open sign event is not checking on the correct event, so it isn't properly blocked.
currently its on the "use" event, and denying that flag alone doesn't block it - the "interact" flag has to be not set to "allow" or else players will still be able to open signs in areas they don't have access.
https://github.com/EngineHub/WorldGuard/blob/master/worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/listener/EventAbstractionListener.java#L615

### Expected Behavior

For it to check on the "build" event instead as other "Claiming" plugins does this.

### Reproduction Steps

**1)** Little John places a sign down.
**2)** John gets the edit sign dialog screen.
**3)** Karen comes over and claims that area.
**4)** Karen then removes build permissions from John.
**5)** John finished editing the sign and clicks Done.
**6)** WorldGuard doesn't seem to listen to the SignChangeEvent, so John is allowed to edit that sign.

### Optional WorldGuard-Report

Not relevant.

**Comment by SiuanSong** [comment]
Not sure if related, but players can change sign colors with dye in regions they don't have access to as well.

**Comment by wizjany** [comment]
don't think this is an issue anymore as of 1.20 changes, see also #2026
