### ISSUE TITLE
world names with `w` at the start breaks command block usage

### ISSUE THREAD

**Issue by Josh-65** [EngineHub/WorldGuard#1945]
### WorldEdit Version

7.2.11

### WorldGuard Version

7.07

### Platform Version

1.18.2 Paper 387

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I have my worlds setup so that w is infront of the name. It cause issue as when using a command block i have to specify the world name if i put this in `/region flag whub-all pvp allow` but adding `-wwhub` say it already got a word name specified.

### Expected Behavior

`-w` should have everything after be a string and should not count `w` as a world name parameter

### Reproduction Steps

Create a world with w infont
Change a flag with a command block adding the -wworld-name

**Comment by me4502** [comment]
You're not writing the command correctly. There is a space after flag keys, if you enter it as you are, it's parsing them as extra flags not as the argument for the flag

**Comment by Josh-65** [comment]
Can you give me an example of how its suppose to look since im following the formatting shown in game when doing /rg flag

**Comment by me4502** [comment]
`-w worldname`

**Comment by Josh-65** [comment]
Thanks
