### ISSUE TITLE
Can I just create a region with a single command, without needs for WorldEdit positions?

### ISSUE THREAD

**Issue by AllayBreeze** [EngineHub/WorldGuard#1949]
### The Problem

I want to create regions on the console but it doesn't work for there's no selected WorldEdit areas. So I wish there's a single command that can create regions directly.

### A Solution

Just like this:

/rg normalcreate \<pos1x\> \<pos1y\> \<pos1z\> \<pos2x\> \<pos2y\> \<pos2z\> \<name\> \<owner\>

### Anything Else?

Maybe it's hard to achieve? Anyway, I wish this may become true some day.

**Comment by me4502** [comment]
Why would we add an overly complex command that has substantially less features just to prevent having to do multiple commands? I don't understand the use case at all
