### ISSUE TITLE
The incoming YAML document exceeds the limit

### ISSUE THREAD

**Issue by crumpkatrina** [EngineHub/WorldGuard#1953]
### WorldEdit Version

WorldEdit v7.2.13-SNAPSHOT+6259-7e61ff1

### WorldGuard Version

WorldGuard v7.0.8-SNAPSHOT+2208-cb100bb

### Platform Version

Paper 1.19.2 Build 175

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

New paper limits + big region files break servers.
https://pastebin.com/raw/5tZFAk6n

### Expected Behavior

To load the file or migrate to new system.

### Reproduction Steps

1. Use big regions.yml file with latest paper.

### Anything Else?

Any temporary solutions you can advise?

**Comment by wizjany** [comment]
https://github.com/EngineHub/WorldEdit/issues/2193
