### ISSUE TITLE
Add Members trough /teams instead of Groups

### ISSUE THREAD

**Issue by t0g3pii** [EngineHub/WorldGuard#1955]
### The Problem

We're using the Vanilla /teams command to handle teams on our server, so there are no groups created by any permissions system. therefore we are not able to use `/rg addmember -w lobby spawn g:builder sk89q`

### A Solution

Maybe we could add a t: flag for that?
`/rg addmember -w lobby spawn t:teamname sk89q`

### Alternatives

N/A

**Comment by t0g3pii** [comment]
NOTE: found this Feature Request of 2018
https://github.com/EngineHub/WorldGuard/issues/1425

**Comment by wizjany** [comment]
duplicate, as you already found.

**Comment by t0g3pii** [comment]
Oh, haven't seen #1866 as it uses the word Domain^^ How would i implement my own team with that once it is in? 
Idk what the Vanilla Domain for teams would look like in the end? Something like minecraft_teams:teamname?

**Comment by wizjany** [comment]
"via api" means other plugins (i.e. code) can add it. not that end users can.

**Comment by t0g3pii** [comment]
Welp, gonna hope there's going to be a documentation for that one^^ 
Going to write an own Plugin then :3 Ty for the fast reply^
