### ISSUE TITLE
Grindstone Placement in blacklist.txt

### ISSUE THREAD

**Issue by AnimeDrache** [EngineHub/WorldGuard#1957]
### WorldEdit Version

Bukkit-Official(7.2.12+6240-87f4ae1)

### WorldGuard Version

Bukkit-Official (7.0.7+216b061)

### Platform Version

paper-1.19.2-210.jar

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Greetings,

I have a creative world and had to disable some objects so people can't abuse them. But I noticed a problem with the grindstone. I wanted it to be able to be placed but not used (people were able to use it to gain xp by removing enchantments from items). So what I tried is to give the permission to still place it but not use / interact with it. But I ended up noticing that no existing method would give me a working solution for this.

If I use "on-use" it wont allow me to place it
If I use "on-interact" it wont allow me to break it
all other options are not relevant to what I need.

### Expected Behavior

Being able to place and remove a grindstone in a creative world without being able to interact with it (so people can use it to build decorations but not to actually use its functionality)

### Reproduction Steps

1. Blacklist the item in the used creative world in it's "blacklist.txt" file like this:
# Name
[grindstone]
on-use=deny,tell,notify
(OR: "on-interact=deny,tell,notify")
2. Try to place the grindstone and break it again

**Comment by wizjany** [comment]
duplicate
