### ISSUE TITLE
mangrove propagules growth

### ISSUE THREAD

**Issue by ggMatze** [EngineHub/WorldGuard#1958]
### The Problem

Expected that crop growth block HANGING mangrove propagules from growing.

### A Solution

Add mangrove propagules to this flag

### Alternatives

 Create a separate flag, that prevents growing of those.

### Anything Else?

Since this is kinda a sapling and has a hanging and not hanging variant iam not sure which type it fits more.
Crop or sapling

**Comment by wizjany** [comment]
they are most certainly saplings - they belong to the sapling tag already, and as far as i know grow in the same way as saplings (ie via structuregrow, into trees). i see no compelling argument to designate these as crops instead.
