### ISSUE TITLE
In-Config Setting To Disable FailedLoadRegionSet Actions

### ISSUE THREAD

**Issue by EnderGamingFilms** [EngineHub/WorldGuard#1960]
### The Problem

When using unsupported world managers such as SlimeWorldManager world guard does not detect that created worlds are "real" and thus they will not receive any regions including `__global__` normally this would not be an issue except for the fact that World Guard will then proceed to spam players and "protect" those area by default.

### A Solution

Have a setting to simple not protect those undefined areas and to disable the message sent by `FailedLoadRegionSet`

### Alternatives

I have not found any alternative solutions.

**Comment by JOO200** [comment]
WorldGuard listen to the WorldLoadEvent. If your `unsupported` world manager doesn't call that event, WorldGuard will not create the needed sessions.

Use a world manager which calls correct bukkit events.

**Comment by EnderGamingFilms** [comment]
> WorldGuard listen to the WorldLoadEvent. If your `unsupported` world manager doesn't call that event, WorldGuard will not create the needed sessions.
> 
> Use a world manager which calls correct bukkit events.

I use `unsupported` as in  I have experienced this multiple times. The advantage of SlimeWorldManager is that it only saves chuncks that contain blocks which results in extremely efficient load/unloading of worlds. Outside of this I am fairly sure it doesn't necessarily change how Bukkit loads/unloads worlds or calls events.

I did not create that plugin so I do not know. It is open source on GitHub. But I still believe that the messages sent from WorldGuard should still be configurable.

**Comment by wizjany** [comment]
failure cases don't need configuration, they need to be fixed. in this case, by the plugin not using the bukkit api properly.

**Comment by EnderGamingFilms** [comment]
> failure cases don't need configuration, they need to be fixed. in this case, by the plugin not using the bukkit api properly.

Why is it up to world guard to decide what should be done in a failure case, and not a server admin?

**Comment by wizjany** [comment]
feel free to maintain your own fork.
