### ISSUE TITLE
Errors on enable due to YAML file size limit

### ISSUE THREAD

**Issue by JackSinkoMK** [EngineHub/WorldGuard#1961]
### WorldEdit Version

WorldEdit version 7.2.12

### WorldGuard Version

WorldGuard v7.0.8-SNAPSHOT+2208-cb100bb

### Platform Version

Paper-232

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Since updating to Paper 1.19.2-(162 or greater) from Paper 1.19.2-161 WorldGuard doesn't load as the regions.yml file for my main world is above 3mb. 
This is because Paper updated SnakeYaml which introduces a file size limit.
Paper has overriden the default to 64MB if using the built-in Bukkit configuration API, however the default SnakeYaml limit is 3MB, which is what I assume is happening.

See full error on enable: https://pastebin.com/1v2MzPFG

### Expected Behavior

WorldGuard enables with no errors.

### Reproduction Steps

1. Have regions.yml file greater than 3MB and start with latest WorldGuard and Paper builds.

### Anything Else?

This seems to be the exact same issue as the popular plugin 'citizens' which was solved by increasing the snakeyaml file size limit. See this link https://github.com/CitizensDev/Citizens2/issues/2898

**Comment by JOO200** [comment]
That's fixed in a dev build from worldedit available [here](https://builds.enginehub.org/job/worldedit).
