### ISSUE TITLE
bypassing world guard

### ISSUE THREAD

**Issue by IKAKUN12345** [EngineHub/WorldGuard#1962]
### WorldEdit Version

7.2.12+6240-87f4ae1

### WorldGuard Version

idk world guard version(im not server admin)

### Platform Version

PAPER 1.19.2(WaterFall) #256

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

can broke Item Frame

### Expected Behavior

cannot break item frame

### Reproduction Steps

Sorry, im not well english 
1.place boat with chest (i don't known with boat)
2.Move closer to Item Frame
3.attack boat with sword.
if you don't know please watch video

### Anything Else?

Video: https://drive.google.com/file/d/1Tvc3RUvbXBgMiUZ-F_DsRuSM85fF658j/view

**Comment by wizjany** [comment]
duplicate
