### ISSUE TITLE
TNT cart still does a lot of damage despite using the worldguard

### ISSUE THREAD

**Issue by Juliods** [EngineHub/WorldGuard#1965]
### WorldEdit Version

WorldEdit v7.2.12+6240-87f4ae1

### WorldGuard Version

WorldGuard v7.0.8-beta-01+cbb2ba7

### Platform Version

git-Paper-263 

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I enabled the worldguard on an aternos server i'm running to prevent griefing, however it has come to my attention the plugin doesn't prevent TNT carts from damaging the enviroment at all when someone had the bright idea to make a nuke with the things.

I'd really appreciate some help. It does block regular TNT and creepers, but not mine carts.

### Expected Behavior

The TNT cart shouldn't make giant explosion craters 

### Reproduction Steps

1. ... Create a free aternos server
2. ... Download the latest world edit and worldguard
3. ... Start the server
4. ... Put lots of TNT carts on a activator rail
5. ... Give the rail redstone signal

**Comment by wizjany** [comment]
given your reproduction steps, it doesn't block anything, because WG does nothing by default. if you've changed some config or set up some regions, you'll need to specify that and preferably just provide the full report as the template asks you to.
