### ISSUE TITLE
Hey! Sorry, but you can't use that here.

### ISSUE THREAD

**Issue by Pumkinhead** [EngineHub/WorldGuard#1967]
### WorldEdit Version

7.2.11

### WorldGuard Version

7.0.6

### Platform Version

Spigot 1.17.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Everytime anyone tries to mine amethyst in the region with block-break allow they get the issue "Hey! Sorry, but you can't use that here."

### Expected Behavior

The amethyst should break, instead I get the error "Hey! Sorry, but you can't use that here."

### Reproduction Steps

1. Grab a region
2. block-break allow
3. deop and mine amethyst there

**Comment by wizjany** [comment]
update wg
