### ISSUE TITLE
Conditional Entry Flag

### ISSUE THREAD

**Issue by sleafr** [EngineHub/WorldGuard#1968]
### The Problem

A conditional flag for conditional entry or exit of players in regions can be beneficial for some servers. And it has a lot of potential if used with PlaceholderAPI, from simple things to some pretty complex conditions with PAPI "JavaScript" or "Math" extensions.

For example, denying a player holding a sword from entering a safezone

### A Solution

I believe the most versatile way would be to use placeholders from PlaceholderAPI.
Maybe something like 

conditional-entry-deny= %player_item_in_hand% == wooden_sword

**Comment by JOO200** [comment]
That's not in the scope of WorldGuard.

You can create a third party plugin with such a flag but such specific things will not be implemented in WorldGuard.
