### ISSUE TITLE
More specifc use-x flags

### ISSUE THREAD

**Issue by accLarson** [EngineHub/WorldGuard#1969]
### The Problem

When protecting spawn regions with WorldGuard, I often find myself having to create many small regions for covering aesthetic trapdoors (applying `use: false`) while still generally allowing door usage (`use: true`). Alternatively, generally disallowing `use` and allowing it in many small regions where I'd like players to use a door.

### A Solution

Split the `use` flag into more specific cases.

Similar to flags like `use-anvil` and `use-dripleaf`, I'd like to see 
`use-door`, 
`use-trapdoor`,
 `use-button`, 
`use-lever`,
` use-pressureplate`

The `interact` flag could be broken up as well. It's my understanding that the `interact` flag covers essentially every concept of interacting with a block such a chests, furnaces, etc. I suggest these be broken up as well.

**Comment by accLarson** [comment]
I imagine the `use` and `interact` flag could be kept as more general overarching flags; The proposed specific flags could override the overarching `use`/`interact` flags.

**Comment by wizjany** [comment]
the existing ones are a stopgap because interacting with those things can actually modify the region (i.e. break blocks). we will not be adding dozens of flags for every interactive block. maybe in the future there will be a mapflag for this, but there's more issues for that.

**Comment by prototype464** [comment]
> the existing ones are a stopgap because interacting with those things can actually modify the region (i.e. break blocks). we will not be adding dozens of flags for every interactive block. maybe in the future there will be a mapflag for this, but there's more issues for that.

Something for doors / trapdoors specifically would be very nice, trapdoors are a very common decorational block and it's annoying when people flip them constantly in areas they shouldn't be. Sometimes there's also buttons in places, and I'd like to disable trapdoors but allow buttons / levers etc.
