### ISSUE TITLE
Wither explosion damage no longer harms Endermen

### ISSUE THREAD

**Issue by totemo** [EngineHub/WorldGuard#1981]
### WorldEdit Version

7.2.13+46576cc

### WorldGuard Version

7.0.8-beta-01+cbb2ba7

### Platform Version

git-Paper-386, git-Paper-367

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Wither explosions no longer seem to harm endermen. Our players are using an enclosed wither to kill endermen in a grinder, relying on the our server-wide WorldGuard block damange protections to prevent the enclosure from being destroyed.

The wither skull explodes slightly before the enderman and there is no effect. Occasionally an enderman will get the wither potion effect and take periodic damage.

### Expected Behavior

> I expect you to *die*, Mr ~~Bond~~ Enderman.

### Reproduction Steps

I have stripped the problem back to a minimal test setup, as follows:

 * Enclosing structure built in the vanilla end dimension.
 * Paper for 1.19.3 (latest build and a previous build, listed in the questionnaire).
 * Only two plugins: WorldEdit and WorldGuard.
 * Explosion block damage is disabled in `config.yml`. I have set `explosion-flags-block-entity-damage: false`.
 * Protection region over the build with `wither-damage ALLOW` and `ghast-fireball ALLOW`. Also `mob-damage ALLOW` even though that is apparently irrelevant.

According to the Minecraft wiki, the wither skull explosions should inflict damage on most mob types except the undead. In this setup, it will quite happily kill piglins, creepers and farm animals, but endermen take no explosion damage.

I have reviewed the gamerules and don't see any suspicious settings.

### Optional WorldGuard-Report

https://paste.enginehub.org/m06t2deQ1.report

**Comment by me4502** [comment]
To clarify, you’ve confirmed that they do take damage without this WorldGuard setup?

**Comment by totemo** [comment]
Thanks. That's a good question that I wish I had thought to ask myself. They used to take damage, prior to updating WG for 1.19.3.

However, they don't take damage in vanilla 1.19.3. That is very surprising.

**Comment by totemo** [comment]
To complete the paper trail: https://bugs.mojang.com/browse/MC-258561
