### ISSUE TITLE
Please add a way to change the super childish "Hey!" messages!

### ISSUE THREAD

**Issue by Secret-chest** [EngineHub/WorldGuard#1983]
### The Problem

title

### A Solution

add a config file to edit all messages shown in chat when you're not allowed to do something

Example message I would like to edit:
> Hey! Sorry, but you can't break that block here.

### Alternatives

there's no alternative

**Comment by me4502** [comment]
You can already do this with the deny message flag.

**Comment by Secret-chest** [comment]
Could you give an example? Thanks

**Comment by wizjany** [comment]
read the docs. this isn't a support forum.
