### ISSUE TITLE
McMMO and WorldGuard

### ISSUE THREAD

**Issue by GGMarket** [EngineHub/WorldGuard#1984]
### WorldEdit Version

7.2.12

### WorldGuard Version

7.0.7

### Platform Version

purpur 1.19.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Hello.
There is a problem with the mcmmo plugin and regions that do not have pvp on.
When the player hits another player a lot in an area where pvp is disabled, he takes bleeding damage (McMMO) even though he is in an area with pvp disabled and damage disabled (pvp deny and invincible allow) and there are other skills that also deal damage in pvp like ax explosion.
There is also another bug in the latest version.
Players can't open anvil, I have to create a region with build allow so they can access anvils in common areas.
No console errors.

### Expected Behavior

Fully secure the area with pvp off and invincibility on.
And be able to access anvil.

### Reproduction Steps

Put the latest version of mcmmo classic.
Together with the latest version of worldguard

**Comment by JOO200** [comment]
Anvils are protected by default because using them may change the anvil's health state or break them. Use the anvil flag (use-anvil or anvil-use).

It's up to McMMO to stop those effects. WorldGuard can only cancel bukkit pvp events, we don't have support for third party plugins and we will not add stuff for that.
