### ISSUE TITLE
enderchest wont open if not have region on it

### ISSUE THREAD

**Issue by CaptainSmoker-dev** [EngineHub/WorldGuard#1990]
### WorldEdit Version

Bukkit-Official(7.2.13+46576cc)

### WorldGuard Version

Bukkit-Official (7.0.7+216b061)

### Platform Version

purpur

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When i have op and my friend try open an enderchest notn nworking! and when i deop is working!

### Expected Behavior

idk

### Reproduction Steps

1. ...
2. ...
jkjk

### Anything Else?

.........
kjjlkjjj

**Comment by wizjany** [comment]
nothing to do with WG. this is how minecraft's op status and spawn protection work.
