### ISSUE TITLE
Deprecated timing handlers on Paper

### ISSUE THREAD

**Issue by SlimeDog** [EngineHub/WorldGuard#1991]
### WorldEdit Version

7.2.15-SNAPSHOT+6372-93c0d36

### WorldGuard Version

7.0.8-SNAPSHOT+2231-bddfbdd

### Platform Version

git-Paper-482 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bf92f3e)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

On server start-up with newer Paper versions
```
[07:09:03] [Server thread/WARN]: Plugin 'ForceResourcepacks' is creating timing 'Session Handlers' - this is deprecated behavior, please report it to the authors: Phoenix616
[07:09:03] [Server thread/WARN]: Plugin 'ForceResourcepacks' is creating timing 'WorldGuard7Handler' - this is deprecated behavior, please report it to the authors: Phoenix616
```
Phoenix616 states that ForceResourcepacks does not create timing handlers, so WG is likely the cause.

These messages are reported only on Paper; Spigot starts cleanly.

### Expected Behavior

No deprecated methods

### Reproduction Steps

1. Start Paper server
2. Read log

These reports started only within the last few days, as Paper has been updated. I suspect the timing code has been altered to prepare for Folia.

**Comment by wizjany** [comment]
In the meantime, `extra-timings.session-handlers` can be set to `false` in config.

> These reports started only within the last few days, as Paper has been updated. I suspect the timing code has been altered to prepare for Folia.

Actually entirely unrelated to Folia. Paper's been slowly deprecating timings for a while, guess they just dropped some warnings suddenly which is unfortunately rather spammy.

**Comment by SlimeDog** [comment]
> In the meantime, extra-timings.session-handlers can be set to false in config.

Thanks.
