### ISSUE TITLE
Region members are added lowercase, but only when player is not in the game

### ISSUE THREAD

**Issue by ktunkiewicz** [EngineHub/WorldGuard#1994]
### WorldEdit Version

FastAsyncWorldEdit 2.5.2

### WorldGuard Version

7.0.7

### Platform Version

git-Purpur-1931 (MC: 1.19.3)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When adding a region member, like for example:
`/rg addmember foo MrBean123`

And MrBean123 is not currently logged in, it always ends up adding `mrbean123` as the region member.

No mater if I try re-adding, removing and readding, it always ends up lowercased.

However, when the player is logged in, I type `/rg addmember foo MrBean123` and the player name `MrBean123` gets added as region member.

That's pretty annoying, because we need to wait for given player to enter the game to add him to a region.

### Expected Behavior

When I type `/rg addmember foo MrBean123`, I expect `MrBean123` to be added to region, not `mrbean123`

### Reproduction Steps

1. try adding a username with mixed-case name, while that player is not currently logged in:
`/rg addmember foo MrBean123`
2. see the list of members in `/rg info` - it will be `mrbean123` instead

### Anything Else?

I checked the boxes for "latest MC version" and "not using FAWE" after asking a question in Discord if I can report bugs for 1.19.3+FAWE. And from what I understood in the response, was that I *can* do it, and these checkboxes are there to prevent people from submitting FAWE bugs here.

However this doesn't look like related to FAWE or version of Minecraft at all, so I report it.

**Comment by Joo200** [comment]
Offline mode is not supported

**Comment by ktunkiewicz** [comment]
For people looking this up with Google:

For offline servers, instead using names you can use UUIDs of users, if they are offline when you try to add/remove them from the region. 

I guess any dev from EngineHub knows this, so the answer above is really a middle finger to your users, as many of them will have this problem.
