### ISSUE TITLE
worldguard + pvpmanager

### ISSUE THREAD

**Issue by frogglen** [EngineHub/WorldGuard#1999]
### WorldEdit Version

worldedit-bukkit-7.2.15-SNAPSHOT-dist.jar

### WorldGuard Version

worldguard-bukkit-7.0.8-SNAPSHOT-dist.jar

### Platform Version

git-Paper-#511 (MC: 1.19.4)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

pvpmanager plugin developer and I found a possible bug in his plugin, when 2 pvp enabled players are inside a protection, the owner of the protection can start PVP, but the one who is not owner of the protection can not start pvp, when the owner of the protection attacks the other player is tagged and at that moment is when he can fight against the player who owns the region.

### Expected Behavior

both players can start pvp, when they have pvp enabled

### Reproduction Steps

1. ... install worldguard, worldedit
2. ... install pvpmanager
3. ... create a region
4. ... enable pvp and test

**Comment by wizjany** [comment]
not sure what you're trying to say the worldguard bug is here. worldguard does what it's supposed to just fine.
