### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by Zapry** [EngineHub/WorldGuard#2001]
### WorldEdit Version

FastAsyncWorldEdit-357

### WorldGuard Version

WorldGuard 7.0.7

### Platform Version

Purpur

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Crops can be duplicated if they are in someone else's protection. Here I leave a video. (See from minute 2:00 to 3:00) https://www.youtube.com/watch?v=7-tblvlgUHA&t=120s

### Expected Behavior

Crops can be duplicated if they are in someone else's protection. Here I leave a video. (See from minute 2:00 to 3:00) https://www.youtube.com/watch?v=7-tblvlgUHA&t=120s

### Reproduction Steps

Crops can be duplicated if they are in someone else's protection. Here I leave a video. (See from minute 2:00 to 3:00) https://www.youtube.com/watch?v=7-tblvlgUHA&t=120s

**Comment by me4502** [comment]
Not a WorldGuard bug, and you’ve lied multiple times on the issue template
