### ISSUE TITLE
Premission issue with worldguard.region.define 

### ISSUE THREAD

**Issue by PanetiX** [EngineHub/WorldGuard#2004]
### WorldEdit Version

worldedit-bukkit-7.2.14

### WorldGuard Version

7.0.8-SANPSHOT+2231-bddfbdd

### Platform Version

Paper 1.19.3 git-Paper-445

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Hey, i have a problem with WorldGuard Version 7.0.8-SANPSHOT+2231-bddfbdd
I want that a group can use the /rg define command so i give this group the permission  worldguard.region.define 
When a user in this group now use the command, nothing happen. No error, no rg will be defined ...
when i give this group the permission worldguard.region.* it worked but i don't want to give this group the full region * permission, just worldguard.region.define

### Expected Behavior

That users in the specific group can use /rg define who has the permission worldguard.region.define 

### Reproduction Steps

create a permission group e.g "cityowner"
give this group permission "worldguard.region.define"
add the user to the group "cityowner"
the user can't run the command /region define <REGION-NAME>

**Comment by wizjany** [comment]
if they're not even getting an error message sounds like something else is wrong besides permissions
