### ISSUE TITLE
worldguard causes server crashes

### ISSUE THREAD

**Issue by lKJD** [EngineHub/WorldGuard#2005]
### WorldEdit Version

Bukkit-Official(7.2.13+46576cc)

### WorldGuard Version

7.0.5

### Platform Version

git-Purpur-1171(MC: 1.16.5) - 1.16.5-R0.1-SNAPSHOT

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I'm not sure why the error occurred

### Expected Behavior

Restoration

### Reproduction Steps

i dont know..

### Optional WorldGuard-Report

https://paste.enginehub.org/vSg-pCGkh.report

### Anything Else?

not

**Comment by Joo200** [comment]
Can you provide the logs and the crash report? Without that we can't analyze anything.

**Comment by lKJD** [comment]
https://drive.google.com/file/d/1XdTGhmIBXuE4HNCrciBDwQsDHiWHnS8C/view?usp=sharing

**Comment by wizjany** [comment]
a 282 MB log hints that your server has other problems. not gonna bother even downloading that but chances are this isn't a worldguard bug. if you can get a minimal repro, ask in discord for support instead.

**Comment by lKJD** [comment]
But the crash log contains worldguard

**Comment by me4502** [comment]
Join the discord and provide a log that’s not going to crash 99% of text editors it’s opened in
