### ISSUE TITLE
Bug with MythicMobs AOE damage 

### ISSUE THREAD

**Issue by BuchNieZyje** [EngineHub/WorldGuard#2006]
### WorldEdit Version

7.2.13+46576cc

### WorldGuard Version

7.0.8-SNAPSHOR and 7.0.8-beta-01 (both tested)

### Platform Version

SlimeWorldManager-"404e96d" 1.19.3 (paper fork for world memory leak)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

If there are 2 regions overlapping (even without flags) AOE skills from MythicMobs only deal damage to the target

### Expected Behavior

Like AOE skills, damage to all enemy of the area

### Reproduction Steps

1. create 2 overlapping regions ( test region on __global__ works)
2. just try to mythicmob to cast aoe skill

### Anything Else?

i already reported it to mythic mobs, not sure where i should report it so i write here too (Tested on newest MM version (5.2.6))

**Comment by wizjany** [comment]
unclear why this would be a WG bug.
