### ISSUE TITLE
Flag chest-access blocking owner access to chest

### ISSUE THREAD

**Issue by KoNekoD** [EngineHub/WorldGuard#2007]
### WorldEdit Version

7.2.14

### WorldGuard Version

7.0.8

### Platform Version

paper-1.19.4-524

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I set the flag chest-access: DENY in the spawn-inner region, because it lies in the spawn region (so that players can not open chests in the "inner" region). But surprisingly after that neither owner, nor member have access to ALL chests in the "inner" region

### Expected Behavior

In the "inner" region access to chests will be banned, and in the spawn region flowing around it everything will remain the same

### Reproduction Steps

1. create region spawn
2. set flag chest-access ALLOW
3. create region spawn-inner
4. set flag chest-access DENY
5. owner/member need to open chest

### Optional WorldGuard-Report

https://paste.enginehub.org/PY68tog57.report

**Comment by KoNekoD** [comment]
![image](https://github.com/EngineHub/WorldGuard/assets/108808201/af8e8be1-24ba-4cd7-86b1-b59541a2e5ac)

**Comment by KoNekoD** [comment]
Also when creating a test region with chest-access DENY I have a similar problem

**Comment by KoNekoD** [comment]
![image](https://github.com/EngineHub/WorldGuard/assets/108808201/4375e22c-26a2-4421-a0e0-cdce6c2d0bbc)

**Comment by KoNekoD** [comment]
Here are all the permissions for worldguard

**Comment by wizjany** [comment]
not a bug. read the docs if you don't understand how flags work.

**Comment by KoNekoD** [comment]
Then how do I solve my problem?
