### ISSUE TITLE
1.20 Support

### ISSUE THREAD

**Issue by yomanwasup** [EngineHub/WorldGuard#2016]
### WorldEdit Version

7.2.3

### WorldGuard Version

7.0.5

### Platform Version

Paper1.20-9

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

1.20 Support since 7.0.5 doesn't work with the latest version. Dev builds are out for Bukkit

### Expected Behavior

7.0.5 doesn't work with the latest version of MC

### Reproduction Steps

7.0.5 doesn't work with the latest version of Minecraft/Bukkit

**Comment by Joo200** [comment]
#2011
