### ISSUE TITLE
Ability to /rg bypass others

### ISSUE THREAD

**Issue by Shrek069** [EngineHub/WorldGuard#2017]
### The Problem

Ability to /rg bypass <username>

### A Solution

Ability to /rg bypass <username>

so someone else can bypass the region protection just with commands. 

### Alternatives

Permissions exist :) But commands would be great :D

**Comment by wizjany** [comment]
they need the permissions to bypass anyway. the command doesn't remove or grant the actual bypass permission.
i can't see any valid use-case where you trust someone to bypass regions but not to toggle that status.
