### ISSUE TITLE
not sure whats happening?

### ISSUE THREAD

**Issue by CaptainSnickerz** [EngineHub/WorldGuard#2018]
### WorldEdit Version

7.2.10

### WorldGuard Version

7.0.7-dist

### Platform Version

paper 1.18.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

hi, not sure whats going on with my world guard, its having a complete meltdown and i dont understand whats in a zip folder...

i put the error in pastebin, but not sure how to fix it, any help would be amazing, let me know if you need any more info
https://pastebin.com/R7PKVT2A

### Expected Behavior

cannot access beyond page 7 on flags list and getting this error

### Reproduction Steps

1. /rg flags
2. click next til page 7
3. deny click next page 
4. "unexpected error see console"

### Anything Else?

happened after i restarted, not sure what changed as i havnt changed anything

**Comment by me4502** [comment]
Not a WorldGuard issue/error - see this post for possible causes, https://madelinemiller.dev/blog/minecraft-zip-file-closed/

**Comment by CaptainSnickerz** [comment]
ive deleted worldguard and the issue went away, but ive noticed its something to do with an npc that was trying to sit

**Comment by me4502** [comment]
As I said it's unrelated to WorldGuard - the post I linked explains what it is

**Comment by CaptainSnickerz** [comment]
ive checked the post, i have not made any of these changes, do you have any idea what else could have caused it?

**Comment by CaptainSnickerz** [comment]
console is saying its the player mount event from world guard conflicting with citizens, just not sure how to fix it without removing world guard :/ sorry to be a pain

**Comment by me4502** [comment]
A bad server host or Java bug. This is not a WorldGuard error, it's a Java error. It can happen with any plugin, Paper, or the server itself. You should use the Paper Discord for support with this, not the WorldGuard issue tracker.

**Comment by CaptainSnickerz** [comment]
thank you thats perfect
