### ISSUE TITLE
Camel spawn eggs usable within a region with mob-spawning denied

### ISSUE THREAD

**Issue by ToeDev** [EngineHub/WorldGuard#2022]
### WorldEdit Version

7.2.15

### WorldGuard Version

7.0.9-beta1

### Platform Version

Paper-43 1.20.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When attempting to spawn a camel via a spawn egg within a region that has mob-spawning: deny set, the camel successfully spawns every time.  This is only happening with the camel egg, no others.

### Expected Behavior

The camel should not be able to spawn.

### Reproduction Steps

1. Set /rg flag __global__ mob-spawning deny
2. Right click ground with camel spawn egg

**Comment by wizjany** [comment]
as mentioned already, there's no WG bug here.
mojang for whatever reason decided to make camels tamed when you spawn them with a spawn egg, so you'll need to turn off allow-tamed-spawns in WG config or whatever it is.

**Comment by ToeDev** [comment]
Well you actually did not mention that. You just said "doesn't sound like a WG issue then" and "not sure how you figure everything is pointing to WG".  Thanks for actually giving an answer though. It would have been nice for you to do that originally instead of simply writing everything I said off without explanation.

**Comment by wizjany** [comment]
i told you it wasn't a WG issue because that's the extent of what i knew when i said it.
