### ISSUE TITLE
WorldGuard - Error occurred (in the plugin loader)

### ISSUE THREAD

**Issue by Incluuu** [EngineHub/WorldGuard#2023]
### WorldEdit Version

worldedit-bukkit-7.2.15

### WorldGuard Version

WorldGuard v7.0.9-beta1+2249-223b80c

### Platform Version

git-Purpur-2004 (MC: 1.20.1)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Start the server and shut it down: https://pastebin.com/cuxPrJhK

### Expected Behavior

no errors

### Reproduction Steps

1. start server
2. stop server

**Comment by me4502** [comment]
> ru.tehkode.permissions.backends.PermissionBackend

Not a WorldGuard error, it's whatever plugin that is
