### ISSUE TITLE
Copper fade flag does not work

### ISSUE THREAD

**Issue by GavvyDizzle** [EngineHub/WorldGuard#2025]
### WorldEdit Version

7.2.15

### WorldGuard Version

7.0.9-beta1

### Platform Version

git-Paper-49 (1.20.1)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

The copper-fade flag does not stop copper fading. I have the flag set to `DENY` and copper still oxidizes in the world.

### Expected Behavior

Copper should not oxidize when the flag is set to `DENY`

### Reproduction Steps

1. Create a WorldGuard region
2. Make the copper-fade flag `DENY`
3. Watch the copper oxidize in that region

**Comment by me4502** [comment]
The code within WorldGuard is all fine. There have been a large number of bugs within Spigot 1.20 that have slowly been fixed around the BlockFadeEvent not being called with correct block states, so this is most likely a Spigot bug. Make sure you're using the latest Paper build, as it's very possible it's already been fixed as you're on a fairly outdated build.

**Comment by me4502** [comment]
It looks like in fixing this in Spigot they made a different (non-logical) event now what is called (BlockFormEvent, what gets called when snow forms etc). Unsure if this is intentional or if it'll move back to BlockFadeEvent

**Comment by Joo200** [comment]
It didn't move back to BlockFadeEvent so looks like this is intended. Fixed in 5934e49489e01f2ea0363e6e9322c2f17f042445 .
