### ISSUE TITLE
You can edit signs on 1.20 in protected areas

### ISSUE THREAD

**Issue by JHarris12345** [EngineHub/WorldGuard#2026]
### WorldEdit Version

7.2.15

### WorldGuard Version

7.0.9

### Platform Version

This server is running Pufferfish+ version git-PufferfishPlus-9 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

You can edit signs by right clicking them in areas you do not have permission to build

### Expected Behavior

You shouldn't be able to do this

### Reproduction Steps

1. Protect a region
2. Have someone edit a sign

**Comment by Joo200** [comment]
Please provide the wg report (/wg report -p)  and the Logs from your server.

**Comment by JHarris12345** [comment]
https://paste.enginehub.org/HZDDBT55E.report

**Comment by Joo200** [comment]
You're not in any region at all.

Try to reproduce it with the newest paper version and only wg and we installed.

**Comment by JHarris12345** [comment]
Sorry I did not realise I had to be in the region:

https://paste.enginehub.org/1MuY-seE4.report

It seems to be replicable on later versions too

**Comment by Joo200** [comment]
I can't reproduce this issue. I'm able to click the sign and edit text however when I apply the change it's correctly rejected.
