### ISSUE TITLE
Worldguard error: `method 'void <init>()' not found`

### ISSUE THREAD

**Issue by Engineer152** [EngineHub/WorldGuard#2027]
### WorldEdit Version

7.2.15

### WorldGuard Version

7.0.8

### Platform Version

paper-1.20.1-80

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When starting up my server i am currently getting the following error:

`14.07 12:21:17 [Server] INFO Enabling WorldGuard v7.0.8+33cdb4a
14.07 12:21:17 [Server] INFO (07.23-world) TNT ignition is PERMITTED.
14.07 12:21:17 [Server] INFO (07.23-world) Lighters are PERMITTED.
14.07 12:21:17 [Server] INFO (07.23-world) Lava fire is PERMITTED.
14.07 12:21:17 [Server] INFO (07.23-world) Fire spread is UNRESTRICTED.
14.07 12:21:17 [Server] INFO Loaded configuration for world '07.23-world'
14.07 12:21:17 [Server] INFO (07.23-world_nether) TNT ignition is PERMITTED.
14.07 12:21:17 [Server] INFO (07.23-world_nether) Lighters are PERMITTED.
14.07 12:21:17 [Server] INFO (07.23-world_nether) Lava fire is PERMITTED.
14.07 12:21:17 [Server] INFO (07.23-world_nether) Fire spread is UNRESTRICTED.
14.07 12:21:17 [Server] INFO Loaded configuration for world '07.23-world_nether'
14.07 12:21:17 [Server] INFO Loading region data...
14.07 12:21:17 [Server] ERROR Error occurred while enabling WorldGuard v7.0.8+33cdb4a (Is it up to date?)
14.07 12:21:17 [Server] INFO java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
14.07 12:21:17 [Server] INFO at com.sk89q.worldguard.protection.managers.storage.file.YamlRegionFile.<clinit>(YamlRegionFile.java:92) ~[worldguard-bukkit-7.0.8-dist.jar:?]
14.07 12:21:17 [Server] INFO at com.sk89q.worldguard.protection.managers.storage.file.DirectoryYamlDriver.get(DirectoryYamlDriver.java:79) ~[worldguard-bukkit-7.0.8-dist.jar:?]
14.07 12:21:17 [Server] INFO at com.sk89q.worldguard.protection.managers.RegionContainerImpl.createAndLoad(RegionContainerImpl.java:136) ~[worldguard-bukkit-7.0.8-dist.jar:?]
14.07 12:21:17 [Server] INFO at com.sk89q.worldguard.protection.managers.RegionContainerImpl.load(RegionContainerImpl.java:115) ~[worldguard-bukkit-7.0.8-dist.jar:?]
14.07 12:21:17 [Server] INFO at com.sk89q.worldguard.bukkit.BukkitRegionContainer.load(BukkitRegionContainer.java:117) ~[worldguard-bukkit-7.0.8-dist.jar:?]
14.07 12:21:17 [Server] INFO at com.sk89q.worldguard.protection.regions.RegionContainer.loadWorlds(RegionContainer.java:175) ~[worldguard-bukkit-7.0.8-dist.jar:?]
14.07 12:21:17 [Server] INFO at com.sk89q.worldguard.protection.regions.RegionContainer.initialize(RegionContainer.java:64) ~[worldguard-bukkit-7.0.8-dist.jar:?]
14.07 12:21:17 [Server] INFO at com.sk89q.worldguard.bukkit.BukkitRegionContainer.initialize(BukkitRegionContainer.java:66) ~[worldguard-bukkit-7.0.8-dist.jar:?]
14.07 12:21:17 [Server] INFO at com.sk89q.worldguard.bukkit.BukkitWorldGuardPlatform.load(BukkitWorldGuardPlatform.java:143) ~[worldguard-bukkit-7.0.8-dist.jar:?]
14.07 12:21:17 [Server] INFO at com.sk89q.worldguard.WorldGuard.setup(WorldGuard.java:91) ~[worldguard-bukkit-7.0.8-dist.jar:?]
14.07 12:21:17 [Server] INFO at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onEnable(WorldGuardPlugin.java:151) ~[worldguard-bukkit-7.0.8-dist.jar:?]
14.07 12:21:17 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
14.07 12:21:17 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-80]
14.07 12:21:17 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-80]
14.07 12:21:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
14.07 12:21:17 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.1.jar:git-Paper-80]
14.07 12:21:17 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.1.jar:git-Paper-80]
14.07 12:21:17 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-80]
14.07 12:21:17 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-80]
14.07 12:21:18 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-80]
14.07 12:21:18 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-80]
14.07 12:21:18 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-80]
14.07 12:21:18 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
14.07 12:21:18 [Server] INFO Disabling WorldGuard v7.0.8+33cdb4a`

### Expected Behavior

For worldguard to start normally.

### Reproduction Steps

1. Load World Edit & WorldGuard into plugin folder
2. Start Server

**Comment by dajack05** [comment]
I ran into the same issue.

What worked for me was to download the latest beta instead of the default download.

I downloaded the one labeled "WorldGuard 7.0.9 Beta 1 (MC 1.20+)" and it seems to be working just fine.

<img width="1225" alt="Screenshot 2023-07-17 at 13 23 15" src="https://github.com/EngineHub/WorldGuard/assets/8793629/ef46fbde-b4ff-4165-8d62-edce8153e0c2">

**Comment by rktfier** [comment]
I'm suffering from the same issue.

https://mclo.gs/jygZsMU

**Comment by Joo200** [comment]
WG 7.0.8 doesn't support MC 1.20, use the beta release instead.

**Comment by jakeyjr** [comment]
i have the same issue, and im using the beta release 
world edit and world guard disables itself
log: https://mclo.gs/9SL6u7s
