### ISSUE TITLE
TNT explosion bug

### ISSUE THREAD

**Issue by ConnorServers** [EngineHub/WorldGuard#2029]
### WorldEdit Version

FAWE 2.7.1 SNAPSHOT-b540

### WorldGuard Version

7.0.9

### Platform Version

Spigot 1.20.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [ ] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

TNT explosion breaks blocks in regions with TNT deny, Other-explosions deny, Creeper-explosions deny

### Expected Behavior

Blocks don't break

### Reproduction Steps

1. create region
2. TNT deny, Other-explosions deny, Creeper-explosions deny
3. ignite tnt in that region

**Comment by ConnorServers** [comment]
https://paste.enginehub.org/oF8ttMr2i.report

**Comment by wizjany** [comment]
maybe you're op or something, but either way definitely not a WG bug.

**Comment by ConnorServers** [comment]
It is a WG bug.
I tested on 1.20.1 with only 2 plugins, latest WG and WE and bug still occurred.
Being operator doesn't change how tnt in regions behave.

**Comment by ConnorServers** [comment]
> maybe you're op or something, but either way definitely not a WG bug.

It is a WG bug.
I tested on 1.20.1 with only 2 plugins, latest WG and WE and bug still occurred.
Being operator doesn't change how tnt in regions behave.
