### ISSUE TITLE
Worldguard overrides own heal-command

### ISSUE THREAD

**Issue by DevJoey** [EngineHub/WorldGuard#2031]
### WorldEdit Version

7.2.15+6463-5ca4dff

### WorldGuard Version

7.0.9+5934e49

### Platform Version

git-Paper-108 (MC: 1.20.1)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I cannot register a own heal comand because Worldguard overwrites it.

If i do the following:
```
getServer().getCommandMap().getKnownCommands().remove("heal");
getServer().getCommandMap().getKnownCommands().remove("worldguard:heal");
```
My command gets registered. If i remove WorldGuard my command also works. 

### Expected Behavior

Heal command of worldguard should not override other commands. Add an option to the config to disable the worldguard heal command.

### Reproduction Steps

1. Write a plugin that has a /heal command
2. Install worldguard
3. Run /heal

**Comment by me4502** [comment]
See https://github.com/EngineHub/WorldGuard/issues/2013#issuecomment-1584379859

**Comment by leJulxan** [comment]
Hat vielleicht nichts hiermit zutun, aber könntest du mir eventuell helfen, einen Client zu schreiben, muss nicht unbedingt ein Hackclient sein, aber ich kriege es nicht richtig hin, den richtig aufzusetzen
