### ISSUE TITLE
Cant define spawn while in middle of ocean

### ISSUE THREAD

**Issue by AqueleHaru** [EngineHub/WorldGuard#2035]
### WorldEdit Version

7.2.15

### WorldGuard Version

7.0.9

### Platform Version

Purpur 2060 1.20.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Cant protect region while in middle of ocean? when i do /rg info it says im not in region, even if i set the spawn correctly using /rg define spawn

### Expected Behavior

region to work and flags.

### Reproduction Steps

1. ... go to 100000 150 100000
2. ... create a square and try to define it as spawn, it will define but when you do /rg info it will not show youre in spawn.

<img width="496" alt="image" src="https://github.com/EngineHub/WorldGuard/assets/61639486/cbda7dbe-3fb4-4991-a760-e89b52642c74">

**Comment by wizjany** [comment]
use discord for support.
