### ISSUE TITLE
Region bypass not functioning properly with papet 1.20.2

### ISSUE THREAD

**Issue by MassaHex** [EngineHub/WorldGuard#2037]
### WorldEdit Version

7.3.0-BETA-1

### WorldGuard Version

7.0.9

### Platform Version

Paper-222 1.20.2

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When trying to break blocks with OP or with bypass perms it doesn't work and when I try to toggle region bypass with the command it returns a java.lang zip file error.

### Expected Behavior

Ability to break blocks

### Reproduction Steps

1. Use paper
2. Try to break blocks

### Optional WorldGuard-Report

/wg toggle-bypass

### Anything Else?

An image
![Screenshot_20231009_075432_Minecraft](https://github.com/EngineHub/WorldGuard/assets/105466578/e2920aef-633d-456c-b5a9-5a844f6e822f)

**Comment by me4502** [comment]
If you're referring to "zip file closed", that's not related to WorldGuard at all. It just means that something has modified the jar file while the server is running.

See https://madelinemiller.dev/blog/minecraft-zip-file-closed/ for more information

**Comment by MassaHex** [comment]
I'm still having the bug even after reading your forum. Don't close issue submissions without further information. First off I've already restarted my server. I've already replaced the worldguard file as well.

**Comment by me4502** [comment]
As I said, the error you're having is entirely unrelated to WorldGuard. There's no WorldGuard issue here, so having an issue open does not make sense.

All information about the error you received is in the linked article, there's nothing more I can say in relation to this issue as you've already been given all relevant information.

**Comment by Joo200** [comment]
The correct command is `/rg bypass`, not `/wg toggle-bypass`...
