### ISSUE TITLE
Heal command 

### ISSUE THREAD

**Issue by hiiamken** [EngineHub/WorldGuard#2038]
### WorldEdit Version

WorldEdit 7.3.0 Beta 1 (1.17.1 - 1.20.2)

### WorldGuard Version

7.0.9-beta1

### Platform Version

Paper 1.20.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

"How can I use the 'heal' command from Essentials instead of the 'heal' command from WorldGuard? I can't find it in the plugin's config.

![image](https://github.com/EngineHub/WorldGuard/assets/142149960/379045e5-a805-45ca-a8c9-5fcfbec7e020)

### Expected Behavior

I want to use the 'heal' command from Essentials because the WorldGuard 'heal' command doesn't have a cooldown. When I set the 'essentials.heal' permission for players, they can't use the '/heal' command. But if I also set the 'worldguard.heal' permission, players can use the command, but there's no cooldown.

### Reproduction Steps

1. Add perm essentials.heal. Player can't /heal
2. Add perm worldguard.heal. Player can /heal without cooldown

**Comment by wizjany** [comment]
https://github.com/EngineHub/WorldGuard/issues/2013#issuecomment-1584379859
