### ISSUE TITLE
I can't interact list guard! 

### ISSUE THREAD

**Issue by MeoNguOfficial** [EngineHub/WorldGuard#2045]
### WorldEdit Version

7.2.17

### WorldGuard Version

7.0.9

### Platform Version

PaperMC 1.20.2 #318

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I can't interact list of worldguard, when i use mouse move to list and click, no respond
I use older version of Minecraft Java but not effective
![image](https://github.com/EngineHub/WorldGuard/assets/135810477/c350ffb2-46c0-42fd-8c6d-98989ec05716)

### Expected Behavior

I have to type manual, but lost many time to make done

### Reproduction Steps

1. .../rg flags [spawn]
2. ...list flags but not interact
![image](https://github.com/EngineHub/WorldGuard/assets/135810477/2584486c-16a1-4374-a021-a8164a048bb5)

**Comment by me4502** [comment]
Usually something like this is caused either by:

* Broken client mods
* Broken proxy
* Broken protocol modifying plugins (think things like ViaVersion)
* Broken chat report removal plugins

**Comment by wizjany** [comment]
rule out all the things mentioned. this isn't a worldguard bug.
