### ISSUE TITLE
PlayerCommandPreProcessEvent on LOW priority

### ISSUE THREAD

**Issue by JHarris12345** [EngineHub/WorldGuard#2050]
### The Problem

I need to edit the commands players are using BEFORE worldguard sees it. Currently, as worldguard is on the LOWEST priority, it makes it hard to edit commands prior to worldguard seeing. I ask for this because there is a way you can bypass blocked commands in worldguard:

- If you block the command /spawn (for example), you can bypass it by using / spawn (just add spaces after the slash)
- My plugin edits commands to remove the spaces after the slash. But as worldguard works on the LOWEST priority, it doesn't see the altered commands and lets it happen

### A Solution

Put the event on the LOW priority so commands can be altered prior

### Alternatives

N/A

### Anything Else?

N/A

**Comment by wizjany** [comment]
the space thing was reported to paper ages ago, as it's a paper-specific..."feature". either they should fix it to work how MC and CB work, or we need to make some hacky fix on our end for their problems.

messing with other plugins and changing priorities is *not* a solution here.
