### ISSUE TITLE
Why is latest build of WorldGuard flagged as a trojan by 10 different security vendors?

### ISSUE THREAD

**Issue by drlaserdev** [EngineHub/WorldGuard#2051]
### WorldEdit Version

7.2.18

### WorldGuard Version

7.0.9

### Platform Version

-

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Whenever I submit and rescan the latest release of WorldGuard (Which is 7.0.9) to VirusTotal, 10 different security vendors flag it as malicious (Most likely trojan). Are these all false positives? The previous release (7.0.8) doesn't get flagged at all, so what makes this release so different? I'm too lazy to decompile the binary or try to run it in a vm so please explain wtf is this.

### Expected Behavior

Not getting flagged as malicious.

### Reproduction Steps

1. Go to VirusTotal
2. Submit the .jar file

**Comment by wizjany** [comment]
this isn't even a bug report. also dunno ask them, prob some false positive on some lib we use. /shrug
nothing we can do there.
