### ISSUE TITLE
Cant teleport to other world

### ISSUE THREAD

**Issue by EpicJosch** [EngineHub/WorldGuard#2052]
### WorldEdit Version

7.3.0

### WorldGuard Version

7.0.9

### Platform Version

git-Paper-186

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When i switch the world and walk then i get teleported to the Spawn. I know that its because of worldguard because this happens only to players that are not owner of the region where i try to teleport away from. I already tried without flags etc..

### Expected Behavior

Not teleporting to spawn

### Reproduction Steps

1. Install WorldGuard and WorldEdit
2. Setup a region and stand inside of it
3. Remove worldguard permissions from you
4. Teleport to another world

**Comment by EpicJosch** [comment]
is there anything done about this? The plugin is pretty useless for all users while this bug is occuring

**Comment by wizjany** [comment]
unless you omitted something very important from your reproduction steps (e.g. setting exit deny on the region, in which case intended behavior), this isn't a WG issue.
