### ISSUE TITLE
'Decorated Pot' does not have the intended protection

### ISSUE THREAD

**Issue by BangXi** [EngineHub/WorldGuard#2054]
### WorldEdit Version

7.3.0

### WorldGuard Version

7.0.9

### Platform Version

purpur-1.20.4-2113.jar

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Cannot prevent projectiles from destroying Decorated Pots

### Expected Behavior

Stranger projectiles cannot destroy Decorated Pots ...

### Reproduction Steps

Egg snowball bow shot at the Decorated Pot

**Comment by wizjany** [comment]
if this is anything like previous issues with arrows being able to break things like chorus plants and change target blocks, it will need support from the server itself. likely worldguard will immediately protect it once spigot/paper/etc add proper events for it.

**Comment by BangXi** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/292ec79e09e3b90358560dd9e571452c9da7500f

https://github.com/PaperMC/paper/commit/fe53b0e76fc640072ff7866da496b439032c1684
