### ISSUE TITLE
drop item was disspeared when drop item from shield slot.

### ISSUE THREAD

**Issue by Ecilpse** [EngineHub/WorldGuard#2062]
### WorldEdit Version

FAWE 2.8.4-SNAPSHOT-624;fe626a9

### WorldGuard Version

7.0.9+5934e49

### Platform Version

paper(318) 1.20.2-RO.1.SNAPSHOT

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

If player drop an item from shield slot while the inventory is full, the item disappears. (drop-item = deny)

### Expected Behavior

Please let the cancelled event item come back into the shield slot.

### Reproduction Steps

i reproduced in video

https://youtu.be/EEQFG2efMrc

**Comment by wizjany** [comment]
duplicate, not a WG issue, and don't lie on the template.

**Comment by Ecilpse** [comment]
> duplicate, not a WG issue, and don't lie on the template.

what is cause of this?
