### ISSUE TITLE
Custom entry flag registry

### ISSUE THREAD

**Issue by Rosstail** [EngineHub/WorldGuard#2064]
### The Problem

Hi there.

I would like to make flags affect players but it seems flags can only target all owner/member players or some being part of a permission group and nothing more. 

### A Solution

The solution would be the possibility to add custom flags entry with an id/name.

Exemple, I want a flag that target players in a Nodewar Team (one of my plugins team), the entry id/name would be something like `nw_<teamname>`.

I tried some things before posting this issue (check the Anything Else section). Since I already made some custom flags with WG API, I know that flags are really "rigged" in that way and I don't think you could do this feature without breaking everything ^^'.

### Anything Else?

I am working to rework on a territory/team plugin based on Worldguard regions.

I use Regions for:
- Territory layouts
- Target territory team members with group entry flags.

In order to make my teams compatible with the group entry flags, I've decided to use VaultAPI (compatible with many permission plugins) in order to create these groups to assign to players joining/creating a team (I cannot give group to a player through VaultAPI if the group doesn't exist).

But, it seems Vault seems not being able to create groups through code. And commands are not reliable since many perms plugin exist. (Plus the async command -> give group to player)

**Comment by wizjany** [comment]
this is already #1886, though dunno when 7.1 will be a thing.
