### ISSUE TITLE
Mobs going through the central end exit portal ends up at spawn even if protected by a worldguard region

### ISSUE THREAD

**Issue by snurre0** [EngineHub/WorldGuard#2071]
### WorldEdit Version

7.3.0-beta-03+d6d222e

### WorldGuard Version

7.0.10-SNAPSHOT+2260-c7319f1

### Platform Version

Paper version git-Paper-408 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: c5d168c)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I'm unsure if this is actually a bug, but for many years using WorldGuard, players who tried to move mobs(e.g. shulkers) from the end through the central exit portal to spawn, ended up having their mobs automatically vanish when doing so, because our spawn is protected by a WorldGuard region.
I assume that was happening because we have the deny-spawn flag set to true for the spawn area, but I am not entirely sure.
At some point quite a while ago, moving mobs from the end to spawn was suddenly possible again, and mobs started ending up at spawn.

### Expected Behavior

I would expect that setting the flag deny-spawn to true for a region covering the overworld spawn area, should prevent mobs from being teleported to spawn from the end through the portal.

### Reproduction Steps

1. Create a region covering the overworld spawn area and set deny-spawn to true for that region
2. Spawn a mob close to the central end exit portal and push it through the portal
3. Observe the mob appearing at spawn

**Comment by aurorasmiles** [comment]
This is technically not a bug, `deny-spawn` only affects spawning, but moving an entity through a portal is not spawning, it's teleporting.
Pretty similar to `deny-spawn enderman` - enderman won't spawn in that region, but they can still teleport there

**Comment by wizjany** [comment]
yea working as expected. there's separate feature requests to handle mob movement with flags but that's another can of worms entirely.
