### ISSUE TITLE
The interact and use flags are too vague / general

### ISSUE THREAD

**Issue by prototype464** [EngineHub/WorldGuard#2072]
### The Problem

`interact` and `use` stop players from using stuff that you can usually right click. Doors, trapdoors, buttons, signs, flower pots, etc.

The issue is that trapdoors are often used for decorative building and flower pots are used for, well, you get the idea. Sometimes we want players to be able to use buttons or pressure plates, but not doors, trapdoors, or flower pots.

### A Solution

A verbose, but perfect solution here is to split these into their own flags, or add new ones to control each separately. Given we can even stop dripstone creating lava, this probably isn't unrealistic to implement.

The flags would be as follows:
- use-doors
- use-trapdoors
- use-signs
- use-buttons
- use-pressure-plates
- use-pots (to cover both flower pots and decorated pots)
- use- (anything else that might go under this)

That's all.

### Alternatives

There are no alternatives, only suffering.

In seriousness, the only alternatives I can think of with this would be keeping the way it is right now or adding a couple extra, still general, flags.

### Anything Else?

pls help people keep stealing flowers from the flower pots in areas they're only supposed to be able to use buttons and please for the love of God could this guy stop spamming the trapdoors oh my-

**Comment by wizjany** [comment]
dupe

**Comment by prototype464** [comment]
?????

**Comment by prototype464** [comment]
Found this was closed in 2022
https://github.com/EngineHub/WorldGuard/issues/1969
