### ISSUE TITLE
WorldGuard error BlockFromToEvent on 1.21 Spigot Server

### ISSUE THREAD

**Issue by sinDeadman** [EngineHub/WorldGuard#2088]
### WorldEdit Version

worldedit-bukkit-7.3.3.jar

### WorldGuard Version

worldguard-bukkit-7.0.10-dist.jar

### Platform Version

spigot 1.21.jar

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I am getting the error stated in the title in my server console.  below is a full log from my most recent log file.

16.06 15:33:43 [Server] Server thread/ERROR Could not pass event BlockFromToEvent to WorldGuard v7.0.10+d9424b1
16.06 15:33:43 [Server] INFO org.bukkit.event.EventException: null
16.06 15:33:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
16.06 15:33:43 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
16.06 15:33:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
16.06 15:33:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
16.06 15:33:43 [Server] INFO at net.minecraft.world.level.material.FluidTypeFlowing.a(FluidTypeFlowing.java:186) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4214-Spigot-146439e-6ce1726]
16.06 15:33:43 [Server] INFO at net.minecraft.world.level.material.FluidTypeFlowing.a(FluidTypeFlowing.java:158) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4214-Spigot-146439e-6ce1726]
16.06 15:33:44 [Server] INFO at net.minecraft.world.level.material.FluidTypeFlowing.b(FluidTypeFlowing.java:488) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4214-Spigot-146439e-6ce1726]
16.06 15:33:44 [Server] INFO at net.minecraft.world.level.material.Fluid.a(SourceFile:79) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4214-Spigot-146439e-6ce1726]
16.06 15:33:44 [Server] INFO at net.minecraft.server.level.WorldServer.a(WorldServer.java:858) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4214-Spigot-146439e-6ce1726]
16.06 15:33:44 [Server] INFO at net.minecraft.world.ticks.TickListServer.a(SourceFile:215) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4214-Spigot-146439e-6ce1726]
16.06 15:33:44 [Server] INFO at net.minecraft.world.ticks.TickListServer.a(SourceFile:98) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4214-Spigot-146439e-6ce1726]
16.06 15:33:44 [Server] INFO at net.minecraft.server.level.WorldServer.a(WorldServer.java:401) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4214-Spigot-146439e-6ce1726]
16.06 15:33:44 [Server] INFO at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1472) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4214-Spigot-146439e-6ce1726]
16.06 15:33:44 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:406) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4214-Spigot-146439e-6ce1726]
16.06 15:33:44 [Server] INFO at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1321) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4214-Spigot-146439e-6ce1726]
16.06 15:33:44 [Server] INFO at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4214-Spigot-146439e-6ce1726]
16.06 15:33:44 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4214-Spigot-146439e-6ce1726]
16.06 15:33:44 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
16.06 15:33:44 [Server] INFO Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
16.06 15:33:44 [Server] INFO at com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockFromTo(WorldGuardBlockListener.java:114) ~[?:?]
16.06 15:33:44 [Server] INFO at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
16.06 15:33:44 [Server] INFO at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
16.06 15:33:44 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
16.06 15:33:44 [Server] INFO ... 17 more
16.06 15:33:44 [Server] INFO Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_MUSIC_DISCS' [in thread "Server thread"]
16.06 15:33:44 [Server] INFO at com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:867) ~[?:?]
16.06 15:33:44 [Server] INFO at com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockFromTo(WorldGuardBlockListener.java:114) ~[?:?]
16.06 15:33:44 [Server] INFO at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
16.06 15:33:44 [Server] INFO at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
16.06 15:33:44 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
16.06 15:33:44 [Server] INFO ... 17 more

### Expected Behavior

prior to switching from a paper server to spigot, I never had this error.

### Reproduction Steps

1. anytime I start the server with worldguard enabled

### Optional WorldGuard-Report

https://paste.enginehub.org/kJrJmKHpq.report

**Comment by aurorasmiles** [comment]
Worldguard isn't compatible with 1.21 yet

**Comment by Axiumyuyu** [comment]
when it will support 1.21
