### ISSUE TITLE
Add language file

### ISSUE THREAD

**Issue by Z3r0xh** [EngineHub/WorldGuard#2090]
### The Problem

The denial messages and their subtypes are only in English, I know that with the deny-message you can put a general one, but it would be nice to have more types of thought.

For pvp, redstone, doors etc.

### A Solution

Add a lang.yml file with all the worldguard messages and each one can translate them.

These messages, once translated, could be incorporated into a folder for other users.

**Comment by wizjany** [comment]
duplicate of #478
