### ISSUE TITLE
WorldEdit Commands able to bypass WorldGuard Protections

### ISSUE THREAD

**Issue by IngeniousCoder** [EngineHub/WorldGuard#2091]
### WorldEdit Version

7.3.3

### WorldGuard Version

7.0.10

### Platform Version

git-Paper-147

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When modifying blocks using WorldEdit, WorldGuard protections are completely ignored.

### Expected Behavior

WorldEdit commands should be prevented from successfully executing.

### Reproduction Steps

1. Ascertain you are unable to modify a block.
![image](https://github.com/EngineHub/WorldGuard/assets/29097583/a2d69887-34ce-4183-b3d5-bf3ea440be58)
2. Use WorldEdit to select a region and set block
![image](https://github.com/EngineHub/WorldGuard/assets/29097583/299198aa-8742-4331-a636-f4f884a66342)

### Anything Else?

It should be possible to determine who is the one who ran the worldedit command, given CoreProtect is able to do it.

**Comment by wizjany** [comment]
works as intended

**Comment by IngeniousCoder** [comment]
Possible to prevent this behavior?

**Comment by wizjany** [comment]
possible with the API. we won't be adding it as worldedit is not intended to be given to untrusted users in the first place.
