### ISSUE TITLE
Knockback from wind charges not handled

### ISSUE THREAD

**Issue by wizjany** [EngineHub/WorldGuard#2097]
### WorldEdit Version

7.3.4-beta1

### WorldGuard Version

7.0.11-beta1

### Platform Version

Paper-dev

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Even with wind-charge-burst deny cancelling EntityExplodeEvent, since no EntityDamageEvents are called, entities still get knocked back.

### Expected Behavior

Need to handle EntityKnockbackByEntityEvent most likely, probably combine pvp and wind-charge-burst flags.

### Reproduction Steps

1. wind-charge-burst deny
2. throw wind charge

**Comment by wizjany** [comment]
apparently the knockback event is paper-only. leaving this unprotected on spigot might be problematic though.

**Comment by xProMDFKx** [comment]
Pls fix it..

**Comment by Kocimietka7192** [comment]
I report the same problem, same steps ;)
And the same problem - continues to do kb

**Comment by bobhenl** [comment]
Confirming
