### ISSUE TITLE
Denying ghast-fireball prevents wind charges from working

### ISSUE THREAD

**Issue by LenderSchlender** [EngineHub/WorldGuard#2099]
### WorldEdit Version

WorldEdit 7.3.4 Beta 1

### WorldGuard Version

7.0.11-beta1

### Platform Version

Paper 1.21 Build 40

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Setting the `ghast-fireball` flag to `Deny` in a region causes this region to also block wind charges.

### Expected Behavior

Wind charges should not be affected by the `ghast-fireball` flag.

### Reproduction Steps

1. Set the `ghast-fireball` flag to `Deny`
2. Attempt to use a wind charge
This issue also occurs with Breezes

### Anything Else?

I suspect this issue occurs because `AbstractWindCharge` extends the `Fireball` interface, which is being used by WorldGuard to detect Ghast fireball explosions in the `onEntityExplode` method of the `WorldGuardEntityListener`.

**Comment by snurre0** [comment]
I can confirm this.

I can also add two more things regarding wind charges:
- Setting the flag wind-charge-burst to Deny doesn't block the use of wind charges
- Having the ghast-fireball flag set to Deny, and then using a wind charge, consumes the wind charge without it being used. Not sure if intended or not.

**Comment by ploppyperson** [comment]
>     * Setting the flag wind-charge-burst to Deny doesn't block the use of wind charges
This may be covered by #2097 ?
