### ISSUE TITLE
Dog armour can be broken by players inside claims

### ISSUE THREAD

**Issue by baailey** [EngineHub/WorldGuard#2104]
### WorldEdit Version

7.3.5-SNAPSHOT+6844

### WorldGuard Version

7.0.11-SNAPSHOT+2274

### Platform Version

Paper version 1.20.6-148

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When a dog is inside a claim with armour applied, a random player is able to go up to the dog and punch it to break the armour.

### Expected Behavior

For the armour durability to remain untouched when a player attempts to hit the dog

### Reproduction Steps

1. Tame a dog
2. Place it inside a claim
3. Have a user try punch the armour

### Anything Else?

**Comment by CatBang** [comment]
The latest build version of upstream Spigot/Paper has fixed this issue.

**Comment by aurorasmiles** [comment]
Yeah, seems like https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/66e78a96b65b15c41e3c180beaa72c390b9d6153#nms-patches%2Fnet%2Fminecraft%2Fworld%2Fentity%2Fanimal%2FEntityWolf.patch fixed it. nice
