### ISSUE TITLE
People can still place blocks in a claimed region (they are not added to the region)

### ISSUE THREAD

**Issue by giac10000** [EngineHub/WorldGuard#2105]
### WorldEdit Version

7.3.4

### WorldGuard Version

7.0.10

### Platform Version

4263-Spigot-491f367-bed1e3f

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [ ] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When creating a region and not modifying any flag even people not part of the region can place but not break blocks, this still happens if you put the flag "Build" or "Place-blocks" false.

### Expected Behavior

People shouldn't be able to place blocks inside the regions they are not added to.

### Reproduction Steps

1. create a region
2. just deop yourself and try to place blocks

**Comment by wizjany** [comment]
editing the issue template doesn't magic change what versions you're running.
