### ISSUE TITLE
setting this flag may have unintended consequences

### ISSUE THREAD

**Issue by radek2910** [EngineHub/WorldGuard#2112]
### WorldEdit Version

FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-847

### WorldGuard Version

*Bukkit-Official (7.0.10+d9424b1)

### Platform Version

git-Paper-497 (MC: 1.20.4)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

when i try clicking on the flags build, block-break and block-place it keeps saying setting this flag may have unintended consequences still when i have the latest version of worldguard what is the problem?

### Expected Behavior

![2024-07-19_21 40 31](https://github.com/user-attachments/assets/613b4ca9-2572-40f3-a55e-e95527c4c10a)

### Reproduction Steps

1. ...
2. ...

### Optional WorldGuard-Report

https://paste.enginehub.org/M8m1HX-pG.report

### Anything Else?

nah

**Comment by aurorasmiles** [comment]
Read the message, check the documentation, don't lie in the template

**Comment by radek2910** [comment]
aurorasmiles where can i find the documentation

**Comment by aurorasmiles** [comment]
https://worldguard.enginehub.org

**Comment by radek2910** [comment]
it didnt say anything about (setting this flag may have unintended consequences)
