### ISSUE TITLE
Mobs Breaking Decorated Pots Despite Protection Flags

### ISSUE THREAD

**Issue by Jeremylo1** [EngineHub/WorldGuard#2120]
### WorldEdit Version

WorldEdit 7.3.5

### WorldGuard Version

WorldGuard 7.0.11-SNAPSHOT

### Platform Version

Paper version 1.21-119-master@100d75a (2024-07-29T16:00:13Z)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I am encountering an issue where Decorated Pots in protected regions are being broken by mobs, despite having all protection flags enabled.

### Expected Behavior

Decorated Pots should not break from mob projectiles if protection flags are enabled.

### Reproduction Steps

1. Create a protected region with all protection flags enabled.
2. Place Decorated Pots within this region.
3. Have a mob (e.g., Skeleton or Blaze) target a player within the region.
4. Observe that if the mob's projectile (arrow or fireball) misses the player and hits a Decorated Pot, the pot breaks.

### Anything Else?

1. Players cannot break any blocks within the protected region, including Decorated Pots.
2. The issue only occurs with projectiles from mobs, not from players.
3. The region's protection settings should prevent all forms of block breaking.

Thanks :)

**Comment by wizjany** [comment]
can't reproduce this. perhaps an event was missing upstream and has since been fixed?

https://github.com/user-attachments/assets/b5e77c69-337d-46bf-81a8-f1694a882559

**Comment by Jeremylo1** [comment]
What flags are being used in this region, please? I want to make sure everything is fine on my side.

**Comment by wizjany** [comment]
nothing
