### ISSUE TITLE
/stack unstacking when put in chests/inventory

### ISSUE THREAD

**Issue by Castiella** [EngineHub/WorldGuard#2122]
### WorldEdit Version

worldedit-bukkit-7.3.6-SNAPSHOT

### WorldGuard Version

7.0.11-SNAPSHOT+2287-8ffc81a

### Platform Version

Paper version 1.21-123-master@0a1be9a (2024-07-31T02:57:35Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Since updating to 1.21 all previously stacked items have unstacked. If they were in a chest, they are all now singular items and if the chest is full they have just deleted completely. The same with any stacked items in inventories.

If you run /stack - the items stack but then once moved they all unstack again. 

### Expected Behavior

For things to remain stacked.

### Reproduction Steps

/stack
place stacked items in inventory or container.

**Comment by wizjany** [comment]
should only be an issue with bypassing max stack size as mojang now checks that per-item-stack.
