### ISSUE TITLE
Players can place books into lecterns

### ISSUE THREAD

**Issue by RealTriassic** [EngineHub/WorldGuard#2124]
### WorldEdit Version

7.3.5

### WorldGuard Version

7.0.11-beta1

### Platform Version

Paper version 1.21-127-master@4e6a2a1 (2024-08-07T12:50:10Z)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Players are able to place books into lecterns despite `chest-access`, `use` and `interact` being set to deny.

### Expected Behavior

Players should not be able to place books into lecterns.

### Reproduction Steps

1. Place a lectern.
2. Set `chest-access`, `use` and `interact` to deny.
3. Observe that you can still place books into lecterns.

**Comment by wizjany** [comment]
looks like spigot made some change so they no longer send block change events. no idea if this was intentional on their end but i made a workaround anyway cuz i cba to deal with their code.
