### ISSUE TITLE
RegionQuery.testBuild() using a lot of server resources and causing lag

### ISSUE THREAD

**Issue by trent304** [EngineHub/WorldGuard#2125]
### WorldEdit Version

7.3.5

### WorldGuard Version

7.0.9+5934e49

### Platform Version

Paper 1.20.4

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

![image](https://github.com/user-attachments/assets/79ec0d99-e033-4ed8-a8f1-3aa5b9af0312)
World guard is using a large amount of resources 

### Expected Behavior

World guard doesn't use nearly as much server resources

### Reproduction Steps

1. ...Install Token enchant
2. ...Mine blocks in a world guard protected region

**Comment by Joo200** [comment]
The mentioned plugin uses the WorldGuard api to query protection. We can't help with any excessive usage of our api since this plugin is closed source and you have to pay money to get and install the plugin.

Ask the plugin author for support.
