### ISSUE TITLE
People can break blocks?

### ISSUE THREAD

**Issue by zynk123456** [EngineHub/WorldGuard#2128]
### WorldEdit Version

Bukkit-Official(7.3.5+6880-8ba3d89)

### WorldGuard Version

Bukkit-Official(7.0.10+d9424b1)

### Platform Version

paper 1.20.4

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I make a region with /rg create or /rg define and i dont add flags, and people without op and in survival can still break blocks. I tried adding flags but it still didnt work.

### Expected Behavior

People should not be able to break blocks in my region

### Reproduction Steps

1. /rg define (name)
2. /rg flag (name) block-break deny

**Comment by me4502** [comment]
use a worldguard version that’s labelled to support your MC version. don’t lie on the issue template
