### ISSUE TITLE
Block-Place

### ISSUE THREAD

**Issue by GIDS214** [EngineHub/WorldGuard#2129]
### WorldEdit Version

Bukkit-Official(7.3.6+6892-3d660b8)

### WorldGuard Version

Bukkit-Official (7.0.10+d9424b1)

### Platform Version

1.21.1-13-master@7c9240f or 1.21.1-R0.1-SNAPSHOT idk

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

i set block-place and build and passthrough to deny
and even tried with __global__ but they litteraly dont work

### Expected Behavior

people shouldnt be able to place blocks

### Reproduction Steps

1. ...i dont know
2. ...i dont know
3. it litteraly just doesnt work

### Optional WorldGuard-Report

https://paste.enginehub.org/xzdwDpixC.report

**Comment by me4502** [comment]
use a version that’s actually compatible with your MC version
