### ISSUE TITLE
Copper Trapdoor

### ISSUE THREAD

**Issue by Incluuu** [EngineHub/WorldGuard#2130]
### WorldEdit Version

WorldEdit 7.3.6

### WorldGuard Version

WorldGuard 7.0.11 Beta 1

### Platform Version

Current Purpur Version: 1.21-2284-4e55e26 (MC: 1.21)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Copper Trapdoor isn't protect like wooden trapdoor

### Expected Behavior

protect Copper Trapdoor

### Reproduction Steps

1. make region /rg define trapdoor
2. place trapdoor
3. players can use copper trapdoor

**Comment by wizjany** [comment]
can't repro

https://github.com/user-attachments/assets/ddee19bb-8dbd-493c-b83d-a57f92a44f3f
