### ISSUE TITLE
broken blocks

### ISSUE THREAD

**Issue by Jaylee24k** [EngineHub/WorldGuard#2135]
### WorldEdit Version

7.3.6+68 92-3d660b8 i think

### WorldGuard Version

7.0.10+d9424b1 "i cant do '/wg version'   "

### Platform Version

paper

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [ ] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

i can break blocks even the region disabled block breaking

### Expected Behavior

when i mine a block the block breaks even tho the region has block breaking denied "not opped"

### Reproduction Steps

1. make the region
2. and then go to the flags and then "block-break deny"
3. and we can still break the region even tho were not opped
![an image "i use minehut"](https://github.com/user-attachments/assets/0d83ae68-f0b5-43be-9f9d-8c8b689615f4)

**Comment by Jaylee24k** [comment]
do i need to use an other version?

**Comment by Jaylee24k** [comment]
![what does this mean](https://github.com/user-attachments/assets/a38834be-77db-481c-be65-6983e7a45d8a)

**Comment by me4502** [comment]
stop spamming in the issue comments. don’t lie on the issue template, use a WG version actually labelled to support your MC version.
