### ISSUE TITLE
"WorldGuard 7.0.11 Beta 1 (MC 1.21)"

### ISSUE THREAD

**Issue by 10BamberJ** [EngineHub/WorldGuard#2136]
### WorldEdit Version

N/A

### WorldGuard Version

7.0.11 Beta 1 (MC 1.21)

### Platform Version

paper-1.21.1-57

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Console getting spammed when a player joins.

~ https://pastebin.com/Gry5Fuid

### Expected Behavior

Console not getting spammed when a player joins would be nice.

### Reproduction Steps

1. install version of worldgaurd
2. start and join server
3. look at console.

**Comment by aurorasmiles** [comment]
Your log shows you using a different version, update
