### ISSUE TITLE
1.21.1 warn console message

### ISSUE THREAD

**Issue by VentureStudios** [EngineHub/WorldGuard#2141]
### WorldEdit Version

7.3.6

### WorldGuard Version

7.0.11

### Platform Version

Pupperfish 1.21.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

[10:31:43 WARN]: [WorldGuard] "WorldGuard v7.0.11+068ad68" has registered a listener for org.bukkit.event.entity.EntityKnockbackByEntityEvent on method "public void com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onEntityKnockbackByEntity(org.bukkit.event.entity.EntityKnockbackByEntityEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [].

### Expected Behavior

Don't see the message

### Reproduction Steps

1. ...Start server
2. ...Read console

**Comment by me4502** [comment]
This message is due to an event that’s required to maintain Spigot compatibility. There’s not really an alternative beyond hiding the message.

**Comment by VentureStudios** [comment]
As long as it doesn't appear in the console

**Comment by wizjany** [comment]
` bukkit.yml` -> `settings.deprecated-verbose`
