### ISSUE TITLE
Flame enchant triggers damage event from shooting player to arrow

### ISSUE THREAD

**Issue by JHarris12345** [EngineHub/WorldGuard#2144]
### WorldEdit Version

7.3.6+6892-3d660b8

### WorldGuard Version

7.0.11+068ad68

### Platform Version

I've tested on spigot and paper multiple 1.21.1 versions

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When you you shoot a bow in an area you aren't allowed to build (or hurt entities) in, it says "You can't hit that here". I've attached a video 

https://github.com/user-attachments/assets/d0203d7a-23bd-4440-a11a-494cfc204287

### Expected Behavior

It shouldn't say this 

### Reproduction Steps

1. fire a bow
2. Watch the message

**Comment by wizjany** [comment]
can't repro. please provide a proper minimal reproducible example and steps if you think this is a WG issue.

**Comment by JHarris12345** [comment]
Here is my full startup log

https://paste.md-5.net/uwowapezix.md

**Comment by wizjany** [comment]
The issue is that WG doesn't even *listen* to uh... bow firing? projectile movement?

The message implies that the arrow is actually hitting something (entitydamage i guess?). Perhaps try turning on the [event logger](https://worldguard.enginehub.org/en/latest/advanced/event-logging/#displaying-internal-events) and provide the output of that so I can see what event and what target is triggering it.

**Comment by JHarris12345** [comment]
I will be able to do that as soon as I am back home :) 

For further info, the message is sent directly as the arrow is fired and not when it lands. So it implies that the player itself is the entity trigger it. But we will see with the debug later

**Comment by wizjany** [comment]
Ok so the issue is specifically the flame enchantment on the bow ... setting the arrow on fire. However, this doesn't appear to be changed behavior in WG. Has this only started happening recently?

**Comment by JHarris12345** [comment]
This has only happened since I updated to 1.21 from 1.20.4. I am using WG 7.0.9+5934e49 and WE 7.3.3+6788-6359df8 on my 1.20.4 servers and no issue there. So somewhere between those 2 vers is where the issue was created

**Comment by JHarris12345** [comment]
Awesome thanks! Glad we got to the bottom of it
