### ISSUE TITLE
Gamemode flag not functioning

### ISSUE THREAD

**Issue by iLemon** [EngineHub/WorldGuard#2146]
### WorldEdit Version

7.3.6+6892-3d660b8

### WorldGuard Version

7.0.12+829a4a4

### Platform Version

Sakura 1.21.1 (paper fork: https://github.com/Samsuik/Sakura)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

The `gamemode` flag is not working as intended

### Expected Behavior

The `gamemode` flag should update a player's gamemode while they are in the region

### Reproduction Steps

1. Create a region
2. Set the gamemode flag to adventure
3. Enter the region (either walk into or teleport into or join the server while already in region)
4. Your gamemode isn't updated

**Comment by wizjany** [comment]
can't repro. notably make sure you're not testing with bypass. use discord for support, there's definitely no bug here.

**Comment by iLemon** [comment]
Upon further testing, this is only a bug when using WE. When using FAWE, the gamemode flag works fine. But yeah may just be some config or permission issue I have. Thanks anyway!

**Comment by wizjany** [comment]
guarantee you it is not a bug in WE or WG lmao. what do you think I test with.
