### ISSUE TITLE
Wind Burst enchant not sending users back into the air

### ISSUE THREAD

**Issue by baailey** [EngineHub/WorldGuard#2147]
### WorldEdit Version

7.3.7-SNAPSHOT+6926-485bb41

### WorldGuard Version

7.0.13-SNAPSHOP+2301-d9716a5

### Platform Version

Paper 1.21.1-85-master

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When you drop down onto an entity and hit them with a Mace that has the Wind Burst enchant, it is not sending the user back into the air as it should.

### Expected Behavior

For the player to be sent into the air upon hitting an entity.

### Reproduction Steps

1. Give yourself a Mace
2. Enchant it with the Wind Burst enchant
3. Fall from a height above the entity and hit them while you are in mid-air

**Comment by wizjany** [comment]
the server doesn't even send an event for this so i'm unsure how WG could even be causing issues here. not sure if you think this is related to a region setup (your steps don't mention regions at all) or what, but it's working perfectly fine.

**Comment by baailey** [comment]
this was tested with only worldedit and worldguard in a global region with no flags. on a paper server with no plugins it works as intended, but after adding worldedit and worldguard it does not. unsure what other info I can provide for you here.

**Comment by baailey** [comment]
here is a 20 second clip showcasing all the necessary information, as well as an example of the enchant not functioning as intended. please let me know if there is anything else I can provide https://youtu.be/vB2YKx7iNl0

**Comment by wizjany** [comment]
https://github.com/user-attachments/assets/28ecf3c4-2976-438d-baf2-13f03d931ddf

![idea64_LkkrwQ2W9P](https://github.com/user-attachments/assets/4275855a-afca-4d24-b533-d77bd9cd2241)

**Comment by baailey** [comment]
it is caused by `block-other-explosions` being set to `true`. i guess the question is, would this be classed as working as intended or would you consider it a bug

**Comment by wizjany** [comment]
if it's a bug it's certainly not a worldguard one. if the server is telling us there's a block explosion (and a sourceless one at that) and you tell WG to prevent them, then it's doing its job.
