### ISSUE TITLE
WorldGuard region bypass perm is not working with some interactions

### ISSUE THREAD

**Issue by Miir420** [EngineHub/WorldGuard#2162]
### WorldEdit Version

7.3.8-snapshot

### WorldGuard Version

7.0.12

### Platform Version

Paper version 1.21.1-132-ver/1.21.1

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using a version of WorldGuard compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

WorldGuard region is blocking elevators (https://www.spigotmc.org/resources/elevator.67723/) with the use flag. When use flag is switched to ALLOW elevetor works. When the flag is set to DENY noone except OPed players can use elevators. Perm worldguard.region.bypass.* is not working for the elevators (but works for everything else like trapdoors etc.). When player uses elevator (even with the bypass perm) he gets "HEY! Sorry, but you can't use that elevator here."![Image](https://github.com/user-attachments/assets/d900b8a3-f774-41a2-a086-e2463a255a26)

### Expected Behavior

Bypass perm should allow for use of the elevator even when region use flag is set to DENY

### Reproduction Steps

1. Get Elevator
2. Get WorldEdit
3. Get WorldGuard
4. Get Luckperms or something for perms
5. Set region with use flag set to DENY
6. give yourself bypass perm for the world you are in
7. deop yourself
8. try using elevator

**Comment by wizjany** [comment]
answer has not changed, WG is not blocking it.
