### ISSUE TITLE
Could not pass event UseBlockEvent to WorldGuard v7.0.13

### ISSUE THREAD

**Issue by FatherWh0** [EngineHub/WorldGuard#2165]
### WorldEdit Version

7.3.9

### WorldGuard Version

7.0.13-SNAPSHOT+2318

### Platform Version

paper-1.21.4-15

### Confirmations

- [x] I am using the most recent Minecraft release.
- [ ] I am using a version of WorldEdit compatible with my Minecraft version.
- [ ] I am using a version of WorldGuard compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I'm currently testing with an install with only worldedit and worldguard in the plugins folder.
Shortly after successful launch the console begins to show the following error.
https://pastebin.com/8f5LBCPq

### Expected Behavior

After launch there should be no errors on the console.

### Reproduction Steps

1. Build a server with the three components shown above, paper 1.21.4, worldedit and worldguard.
2. Launch the server then wait for the errors.

### Optional WorldGuard-Report

https://paste.enginehub.org/Q8CaAQI_m.report

### Anything Else?

Before looking at my wg report remember this is a test server not my production server. I'm hosted with DedicatedMC.

**Comment by Joo200** [comment]
You're using a version which doesn't support 1.21.4. Use one from here:
https://builds.enginehub.org/job/worldguard?branch=feat/1.21.4
