### ISSUE TITLE
Could not pass event BlockFadeEvent

### ISSUE THREAD

**Issue by Jerlag01** [EngineHub/WorldGuard#2169]
### WorldEdit Version

7.3.10-beta-01

### WorldGuard Version

7.0.13-beta-1+2f13ae0

### Platform Version

4415-Spigot-33ece3e-c905a71 (MC: 1.21.4)

### Confirmations

- [x] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using a version of WorldGuard compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

console spam of the error that it can't pass the BlockFadeEvent to Worldguard

### Expected Behavior

No console spam and passing the event without any issue

### Reproduction Steps

1. install spigot 1.24.1
2. install the latest version of Worldedit and Worldguard
3. startup the server and join

### Optional WorldGuard-Report

http://node.jl-tech.be:7777/xipivipuwe.yaml

**Comment by Joo200** [comment]
7.0.13-beta 1 is not compatible with WG 1.21.4

**Comment by Jerlag01** [comment]
> 7.0.13-beta 1 is not compatible with WG 1.21.4

it says so on the dev.bukkit.org page ![Image](https://github.com/user-attachments/assets/dd37d112-a798-41fc-a188-2c83fecb592b)
